Repository flutter/devtools, pull requests merged in 2019-10, with the labels that each got.

#1106 Hummingbird build of DevTools with a tabbar immitating the current tab layout.
  packages/devtools_flutter/.gitignore
  packages/devtools_flutter/.metadata
  packages/devtools_flutter/.vscode/launch.json
  packages/devtools_flutter/fonts/Roboto/LICENSE.txt
  packages/devtools_flutter/fonts/Roboto/Roboto-Black.ttf
  packages/devtools_flutter/fonts/Roboto/Roboto-Bold.ttf
  packages/devtools_flutter/fonts/Roboto/Roboto-Light.ttf
  packages/devtools_flutter/fonts/Roboto/Roboto-Medium.ttf
  packages/devtools_flutter/fonts/Roboto/Roboto-Regular.ttf
  packages/devtools_flutter/fonts/Roboto/Roboto-Thin.ttf
  packages/devtools_flutter/lib/main.dart
  packages/devtools_flutter/lib/src/config.dart
  packages/devtools_flutter/lib/src/connect_screen.dart
  packages/devtools_flutter/lib/src/screen.dart
  packages/devtools_flutter/pubspec.yaml
  packages/devtools_flutter/test/connect_screen_test.dart
  packages/devtools_flutter/test/screen_test.dart
  packages/devtools_flutter/test/wrappers.dart
  packages/devtools_flutter/web/index.html
  tool/travis.sh
Labels: hummingbird

#1128 Enable mac embedder on package:devtools_flutter
  packages/devtools_flutter/lib/main.dart
  packages/devtools_flutter/macos/.gitignore
  packages/devtools_flutter/macos/AppDelegate.swift
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/Contents.json
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
  packages/devtools_flutter/macos/Base.lproj/MainMenu.xib
  packages/devtools_flutter/macos/Configs/Debug.xcconfig
  packages/devtools_flutter/macos/Configs/Release.xcconfig
  packages/devtools_flutter/macos/Configs/Warnings.xcconfig
  packages/devtools_flutter/macos/Flutter/Flutter-Debug.xcconfig
  packages/devtools_flutter/macos/Flutter/Flutter-Release.xcconfig
  packages/devtools_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  packages/devtools_flutter/macos/Info.plist
  packages/devtools_flutter/macos/MainFlutterWindow.swift
  packages/devtools_flutter/macos/Runner-DebugProfile.entitlements
  packages/devtools_flutter/macos/Runner-Release.entitlements
  packages/devtools_flutter/macos/Runner.xcodeproj/project.pbxproj
  packages/devtools_flutter/macos/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  packages/devtools_flutter/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  packages/devtools_flutter/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/devtools_flutter/macos/Runner.xcworkspace/contents.xcworkspacedata
  packages/devtools_flutter/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: hummingbird

#1142 Use LocalHistoryEntriess for tying the tab navigation with the route stack
  packages/devtools_flutter/lib/src/scaffold.dart
Labels: hummingbird

#1143 Introduce an SSE shim to enable building devtools on a flutter deskop embedder
  packages/devtools_app/lib/src/core/sse/_fake_sse.dart
  packages/devtools_app/lib/src/core/sse/sse_shim.dart
  packages/devtools_app/lib/src/server_api_client.dart
  packages/devtools_app/lib/src/service.dart
Labels: hummingbird

#1127 Test & build devtools_app with Flutter
  .travis.yml
  .vscode/launch.json
  .vscode/tasks.json
  CONTRIBUTING.md
  packages/devtools_app/dart_test.yaml
  packages/devtools_app/lib/html_main.dart
  packages/devtools_app/lib/main.dart
  packages/devtools_app/lib/src/server_api_client.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/integration_tests/integration.dart
  packages/devtools_app/test/integration_tests/integration_test.dart
  packages/devtools_app/test/integration_tests/server_test.dart
  packages/devtools_app/test/support/cli_test_driver.dart
  packages/devtools_app/test/support/devtools_server_driver.dart
  packages/devtools_app/web/index.html
  packages/devtools_app/web/main.dart
  packages/devtools_testing/lib/info_controller_test.dart
  packages/devtools_testing/lib/inspector_controller_test.dart
  packages/devtools_testing/lib/inspector_service_test.dart
  packages/devtools_testing/lib/logging_controller_test.dart
  packages/devtools_testing/lib/matchers/matchers.dart
  packages/devtools_testing/lib/memory_service_test.dart
  packages/devtools_testing/lib/service_manager_test.dart
  packages/devtools_testing/lib/support/file_utils.dart
  packages/devtools_testing/lib/support/flutter_test_environment.dart
  packages/devtools_testing/lib/timeline_controller_test.dart
  packages/devtools_testing/pubspec.yaml
  tool/travis.sh
  tool/update_goldens.sh
Labels: hummingbird

#1144 Connect to the VM Service
  packages/devtools_app/lib/services.dart
  packages/devtools_flutter/lib/main.dart
  packages/devtools_flutter/lib/src/config.dart
  packages/devtools_flutter/lib/src/connect_screen.dart
  packages/devtools_flutter/lib/src/scaffold.dart
  packages/devtools_flutter/pubspec.yaml
  packages/devtools_flutter/test/initializer_test.dart
Labels: hummingbird

#1158 Move devtools_flutter code into package:devtools_app
  .vscode/launch.json
  CONTRIBUTING.md
  packages/devtools_app/lib/main.dart
  packages/devtools_app/lib/services.dart
  packages/devtools_app/lib/src/flutter/app.dart
  packages/devtools_app/lib/src/flutter/connect_screen.dart
  packages/devtools_app/lib/src/flutter/scaffold.dart
  packages/devtools_app/lib/src/flutter/screen.dart
  packages/devtools_app/test/flutter/connect_screen_test.dart
  packages/devtools_app/test/flutter/initializer_test.dart
  packages/devtools_app/test/flutter/scaffold_test.dart
  packages/devtools_app/test/flutter/wrappers.dart
  packages/devtools_flutter/.gitignore
  packages/devtools_flutter/.metadata
  packages/devtools_flutter/.vscode/launch.json
  packages/devtools_flutter/fonts/Roboto/LICENSE.txt
  packages/devtools_flutter/fonts/Roboto/Roboto-Black.ttf
  packages/devtools_flutter/fonts/Roboto/Roboto-Bold.ttf
  packages/devtools_flutter/fonts/Roboto/Roboto-Light.ttf
  packages/devtools_flutter/fonts/Roboto/Roboto-Medium.ttf
  packages/devtools_flutter/fonts/Roboto/Roboto-Regular.ttf
  packages/devtools_flutter/fonts/Roboto/Roboto-Thin.ttf
  packages/devtools_flutter/lib/main.dart
  packages/devtools_flutter/macos/.gitignore
  packages/devtools_flutter/macos/AppDelegate.swift
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/Contents.json
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
  packages/devtools_flutter/macos/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
  packages/devtools_flutter/macos/Base.lproj/MainMenu.xib
  packages/devtools_flutter/macos/Configs/Debug.xcconfig
  packages/devtools_flutter/macos/Configs/Release.xcconfig
  packages/devtools_flutter/macos/Configs/Warnings.xcconfig
  packages/devtools_flutter/macos/Flutter/Flutter-Debug.xcconfig
  packages/devtools_flutter/macos/Flutter/Flutter-Release.xcconfig
  packages/devtools_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  packages/devtools_flutter/macos/Info.plist
  packages/devtools_flutter/macos/MainFlutterWindow.swift
  packages/devtools_flutter/macos/Runner-DebugProfile.entitlements
  packages/devtools_flutter/macos/Runner-Release.entitlements
  packages/devtools_flutter/macos/Runner.xcodeproj/project.pbxproj
  packages/devtools_flutter/macos/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  packages/devtools_flutter/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  packages/devtools_flutter/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/devtools_flutter/macos/Runner.xcworkspace/contents.xcworkspacedata
  packages/devtools_flutter/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  packages/devtools_flutter/pubspec.yaml
  packages/devtools_flutter/web/index.html
  tool/travis.sh
Labels: hummingbird

#1164 Fix broken css due to Flutter integration
  packages/devtools_app/lib/main.dart
  packages/devtools_app/web/index.html
Labels: bug

#1168 Switch to removing elements from the body that are not needed in flutter web
  packages/devtools_app/lib/main.dart
  packages/devtools_app/web/index.html
Labels: hummingbird

#1204 [In progress] Introduce a table view that can expand and collapse
  packages/devtools_app/lib/src/flutter/app.dart
  packages/devtools_app/lib/src/flutter/table.dart
  packages/devtools_app/lib/src/performance/flutter/performance_screen.dart
  packages/devtools_app/lib/src/profiler/cpu_profile_columns.dart
  packages/devtools_app/lib/src/profiler/html_cpu_profile_tables.dart
  packages/devtools_app/lib/src/table_data.dart
  packages/devtools_app/lib/src/trees.dart
  packages/devtools_app/test/flutter/scaffold_test.dart
  packages/devtools_app/test/flutter/table_test.dart
  packages/devtools_app/test/flutter/wrappers.dart
  packages/devtools_app/test/trees_test.dart
Labels: hummingbird

#1224 Slight cleanup for the table & add scrollbars
  packages/devtools_app/lib/src/flutter/table.dart
  packages/devtools_app/lib/src/info/flutter/info_screen.dart
Labels: hummingbird

#1238 Move server_test build to setUpAll to only run once instead of per-test
  packages/devtools_app/test/integration_tests/server_test.dart
Labels: testing

#1242 Introduce buttons for hot reload
  packages/devtools_app/lib/src/flutter/app.dart
  packages/devtools_app/lib/src/flutter/scaffold.dart
  packages/devtools_app/lib/src/service_registrations.dart
  packages/devtools_app/lib/src/ui/flutter/service_extension_widgets.dart
  packages/devtools_app/lib/src/ui/icons.dart
  packages/devtools_app/test/flutter/service_extension_widgets_test.dart
Labels: hummingbird

#1261 Introduce a vertical/horizontal split layout
  packages/devtools_app/lib/src/flutter/split.dart
  packages/devtools_app/test/flutter/split_test.dart
Labels: hummingbird

#1256 [Story of your layout] Experimental flag
  packages/devtools_app/lib/src/inspector/diagnostics_node.dart
  packages/devtools_app/lib/src/inspector/enum_utils.dart
  packages/devtools_app/lib/src/inspector/flutter/inspector_data_models.dart
  packages/devtools_app/lib/src/inspector/flutter/inspector_screen.dart
  packages/devtools_app/lib/src/inspector/flutter/inspector_screen_details_tab.dart
  packages/devtools_app/lib/src/inspector/flutter/inspector_tree_flutter.dart
  packages/devtools_app/lib/src/inspector/flutter/summary_tree_debug_layout.dart
  packages/devtools_app/lib/src/inspector/inspector_controller.dart
  packages/devtools_app/lib/src/inspector/inspector_text_styles.dart
  packages/devtools_app/lib/src/inspector/inspector_tree.dart
  packages/devtools_app/lib/src/inspector/inspector_tree_canvas.dart
  packages/devtools_app/lib/src/inspector/inspector_tree_html.dart
  packages/devtools_app/lib/src/ui/flutter/service_extension_widgets.dart
  packages/devtools_app/test/enum_utils_test.dart
  packages/devtools_app/test/flutter/inspector_screen_test.dart
  packages/devtools_app/test/inspector_data_models_test.dart
Labels: inspector page

#1275 Fix failing integration tests
  packages/devtools_app/test/integration_tests/integration.dart
Labels: testing

#1273 Update the flag list to be more visible in dark mode.
  packages/devtools_app/lib/src/flutter/common_widgets.dart
  packages/devtools_app/lib/src/info/flutter/info_screen.dart
Labels: hummingbird

#1270 Theme
  packages/devtools_app/lib/src/flutter/app.dart
  packages/devtools_app/lib/src/flutter/connect_screen.dart
  packages/devtools_app/lib/src/flutter/navigation.dart
  packages/devtools_app/lib/src/flutter/split.dart
  packages/devtools_app/lib/src/flutter/theme.dart
  packages/devtools_app/test/flutter/navigation_test.dart
  packages/devtools_app/test/flutter/wrappers.dart
Labels: hummingbird
