Repository flutter/devtools, pull requests merged in 2019-11, with the labels that each got.

#1237 Improve test error reporting
  packages/devtools_app/test/integration_tests/server_test.dart
Labels: testing

#1279 Load the VM service url from the given uri query parameter
  packages/devtools_app/lib/src/flutter/app.dart
  packages/devtools_app/lib/src/flutter/common_widgets.dart
  packages/devtools_app/lib/src/flutter/connect_screen.dart
  packages/devtools_app/lib/src/flutter/initializer.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/url_utils.dart
  packages/devtools_app/test/flutter/initializer_test.dart
  packages/devtools_app/test/url_utils_test.dart
Labels: hummingbird

#1295 Fix initializer error
  packages/devtools_app/lib/src/flutter/initializer.dart
  packages/devtools_app/lib/src/ui/flutter/service_extension_widgets.dart
Labels: hummingbird

#1324 Add docs for server API/launchDevTools vm service
  packages/devtools_server/docs/daemon.md
  packages/devtools_server/lib/src/server.dart
Labels: documentation, server

#1327 Add a flat logs table to the logging view.
  packages/devtools_app/lib/src/flutter/screen.dart
  packages/devtools_app/lib/src/flutter/table.dart
  packages/devtools_app/lib/src/logging/flutter/logging_screen.dart
  packages/devtools_app/lib/src/logging/logging_controller.dart
  packages/devtools_app/lib/src/utils.dart
  packages/devtools_app/test/flutter/table_test.dart
Labels: hummingbird

#1350 Determine profile/debug builds by service extension check - not eval.
  packages/devtools_app/lib/src/connected_app.dart
Labels: customer: dream (g3)

#1353 Prep for 0.1.12-dev.1 release.
  packages/devtools/CHANGELOG.md
  packages/devtools/pubspec.yaml
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
Labels: customer: dream (g3)

#1359 Alternately color table rows in light and dark mode.
  packages/devtools_app/lib/src/flutter/table.dart
  packages/devtools_app/lib/src/flutter/theme.dart
Labels: hummingbird

#1365 Allow launching DevTools directly over the JSON stdin API
  packages/devtools_app/test/integration_tests/server_test.dart
  packages/devtools_app/test/support/devtools_server_driver.dart
  packages/devtools_server/docs/daemon.md
  packages/devtools_server/lib/src/server.dart
Labels: server

#1390 Add animated opacity to the flex layout children.
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/flex.dart
  packages/devtools_app/test/flutter/story_of_layout/goldens/story_of_column_layout.png
  packages/devtools_app/test/flutter/story_of_layout/goldens/story_of_row_layout.png
Labels: hummingbird
