Repository flutter/devtools, pull requests merged in 2019-12, with the labels that each got.

#1424 [Story of Layout] Avoid eval errors and infinite loop
  packages/devtools_app/lib/src/inspector/flutter/inspector_service_flutter_extension.dart
  packages/devtools_app/lib/src/inspector/inspector_service.dart
Labels: hummingbird, inspector page

#1419 [Story of Layout] Visualize overflows, free space dimensions tooltip, revise image assets
  packages/devtools_app/assets/img/story_of_layout/cross_axis_alignment/column_center.png
  packages/devtools_app/assets/img/story_of_layout/cross_axis_alignment/column_end.png
  packages/devtools_app/assets/img/story_of_layout/cross_axis_alignment/column_start.png
  packages/devtools_app/assets/img/story_of_layout/cross_axis_alignment/column_stretch.png
  packages/devtools_app/assets/img/story_of_layout/cross_axis_alignment/row_center.png
  packages/devtools_app/assets/img/story_of_layout/cross_axis_alignment/row_end.png
  packages/devtools_app/assets/img/story_of_layout/cross_axis_alignment/row_start.png
  packages/devtools_app/assets/img/story_of_layout/cross_axis_alignment/row_stretch.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/column_center.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/column_end.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/column_spaceAround.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/column_spaceBetween.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/column_spaceEvenly.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/column_start.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/row_center.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/row_end.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/row_spaceAround.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/row_spaceBetween.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/row_spaceEvenly.png
  packages/devtools_app/assets/img/story_of_layout/main_axis_alignment/row_start.png
  packages/devtools_app/lib/src/inspector/flutter/inspector_data_models.dart
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/arrow.dart
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/flex.dart
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/overflow_indicator_painter.dart
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/utils.dart
  packages/devtools_app/test/flutter/story_of_layout/goldens/arrow_bidirectional_horizontal.png
  packages/devtools_app/test/flutter/story_of_layout/goldens/arrow_bidirectional_vertical.png
  packages/devtools_app/test/flutter/story_of_layout/goldens/arrow_unidirectional_down.png
  packages/devtools_app/test/flutter/story_of_layout/goldens/arrow_unidirectional_left.png
  packages/devtools_app/test/flutter/story_of_layout/goldens/arrow_unidirectional_right.png
  packages/devtools_app/test/flutter/story_of_layout/goldens/arrow_unidirectional_up.png
Labels: hummingbird, inspector page

#1446 [Story of Layout] Change wording and remove title in Layout tab
  packages/devtools_app/lib/src/inspector/flutter/inspector_screen.dart
  packages/devtools_app/lib/src/inspector/flutter/inspector_screen_details_tab.dart
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/flex.dart
  packages/devtools_app/lib/src/inspector/inspector_controller.dart
Labels: P0, hummingbird

#1443 Flame chart optimizations - remove tooltips and restructure gesture detection
  packages/devtools_app/lib/src/charts/flutter/flame_chart.dart
Labels: P0, hummingbird

#1447 Spelling fix for layout details
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/flex.dart
Labels: P0, hummingbird

#1445 Make the demo button navigate to the hummingbird app
  packages/devtools_app/lib/src/main.dart
Labels: P0, hummingbird

#1449 Reorder memory and performance tabs
  packages/devtools_app/lib/src/flutter/app.dart
Labels: hummingbird

#1441 [Story of Layout] Improve responsiveness & increase split initial ratio
  packages/devtools_app/lib/src/inspector/flutter/inspector_screen.dart
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/flex.dart
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/utils.dart
Labels: P0, hummingbird

#1450 Fix 2 blocking bugs in dart:html app.
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/main.dart
  packages/devtools_app/test/integration_tests/integration_test.dart
  packages/devtools_app/web/debugger_screen.html
  packages/devtools_app/web/index.html
  packages/devtools_app/web/styles.css
Labels: P0

#1448 [Story of Layout] Add helper text when currently selected widget is not Flex based
  packages/devtools_app/lib/src/inspector/flutter/inspector_screen_details_tab.dart
  packages/devtools_app/test/flutter/inspector_screen_test.dart
Labels: P0

#1453 [Story of Layout] Fix blending color in highlighted light theme
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/flex.dart
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/free_space.dart
Labels: P0

#1454 [Story of Layout] Limit the number of retry done in the eval
  packages/devtools_app/lib/src/inspector/flutter/inspector_service_flutter_extension.dart
  packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/flex.dart
Labels: P0

#1460 Inspector - Change ratio to 1.3 to enable vertical direction on smaller screen
  packages/devtools_app/lib/src/inspector/flutter/inspector_screen.dart
Labels: P0

#1476 Render overlapping async events properly.
  packages/devtools_app/lib/src/charts/flame_chart_canvas.dart
  packages/devtools_app/lib/src/profiler/html_cpu_profile_flame_chart.dart
  packages/devtools_app/lib/src/timeline/timeline_flame_chart.dart
  packages/devtools_app/lib/src/timeline/timeline_model.dart
  packages/devtools_app/lib/src/timeline/timeline_processor.dart
  packages/devtools_app/lib/src/trees.dart
  packages/devtools_app/test/timeline_model_test.dart
  packages/devtools_app/test/trees_test.dart
  packages/devtools_testing/lib/support/timeline_test_data.dart
Labels: customer: dream (g3), timeline page

#1482 Prep for 0.1.14-dev.1 release.
  packages/devtools/CHANGELOG.md
  packages/devtools/pubspec.yaml
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
Labels: customer: dream (g3)

#1489 [Layout Explorer] Change default FlexFit to FlexFit.tight instead of FlexFit.loose
  packages/devtools_app/lib/src/inspector/flutter/inspector_service_flutter_extension.dart
Labels: bug
