Repository flutter/devtools, pull requests merged in 2020-01, with the labels that each got.

#1507 Add timing and id information to event details summary.
  packages/devtools_app/lib/src/timeline/flutter/event_details.dart
  packages/devtools_app/lib/src/timeline/html_event_details.dart
  packages/devtools_app/test/flutter/event_details_test.dart
Labels: timeline page

#1552 Added tests for HttpRequestDataTableSource
  packages/devtools_app/lib/src/network/flutter/network_model.dart
  packages/devtools_app/lib/src/network/flutter/network_screen.dart
  packages/devtools_app/lib/src/network/network_controller.dart
  packages/devtools_app/test/http_request_data_table_source_test.dart
  packages/devtools_testing/lib/support/http_request_timeline_test_data.json
Labels: networking, testing

#1554 Added tests for NetworkController
  packages/devtools_app/lib/src/network/flutter/network_model.dart
  packages/devtools_app/lib/src/network/network_controller.dart
  packages/devtools_app/lib/src/network/network_service.dart
  packages/devtools_app/test/http_request_data_table_source_test.dart
  packages/devtools_app/test/network_controller_test.dart
  packages/devtools_app/test/support/mocks.dart
  packages/devtools_app/test/support/utils.dart
Labels: networking, testing

#1556 Added widget tests for NetworkScreen
  packages/devtools_app/lib/src/network/flutter/http_request_inspector.dart
  packages/devtools_app/lib/src/network/flutter/http_request_inspector_views.dart
  packages/devtools_app/lib/src/network/flutter/network_model.dart
  packages/devtools_app/lib/src/network/flutter/network_screen.dart
  packages/devtools_app/lib/src/network/network_controller.dart
  packages/devtools_app/lib/src/network/network_service.dart
  packages/devtools_app/lib/src/vm_service_wrapper.dart
  packages/devtools_app/test/flutter/network_profiler_test.dart
  packages/devtools_app/test/support/mocks.dart
Labels: networking, testing

#1569 use the repo_tool as part of the CI
  bin/repo_tool
  packages/devtools_app/tool/version_check.dart
  tool/lib/commands/list.dart
  tool/lib/commands/repo_check.dart
  tool/lib/model.dart
  tool/lib/repo_tool.dart
  tool/travis.sh
Labels: WIP
