Repository flutter/devtools, pull requests merged in 2023-09, with the labels that each got.

#6303 Enable and fix test, fix error handling and add new packages to upgrade.sh.
  packages/devtools_app/integration_test/run_tests.dart
  packages/devtools_app/integration_test/test/live_connection/eval_and_browse_test.dart
  packages/devtools_app/integration_test/test_infra/run/_chrome_driver.dart
  tool/upgrade.sh
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6304 Recommend to switch to desktop version in case of crashes.
  packages/devtools_app/lib/src/screens/memory/panes/diff/diff_pane.dart
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty1.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty2.png
Labels: release-notes-not-required, run-dcm-workflow

#6280 Bump to `package:extension_discovery` 2.0.0
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/bin/_build_and_copy.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6306 Add a helper script to update the SDK DEPS file.
  tool/pubspec.yaml
  tool/update_sdk_deps.dart
Labels: release-notes-not-required, run-dcm-workflow

#6305 Cleanup release notes instructions and template
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/README.md
  packages/devtools_app/release_notes/helpers/release_notes_template.md
Labels: autosubmit

#6089 Adds server api to retrieve android build variants
  packages/devtools_app/lib/src/shared/config_specific/server/_server_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_web.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/devtools_deeplink.dart
  packages/devtools_shared/lib/src/deeplink/deeplink_manager.dart
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/deeplink/deeplink_manager_test.dart
  packages/devtools_shared/test/server/server_api_test.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6318 Ensure release_helper.sh creates PRs on main repo
  tool/release_helper.sh
Labels: autosubmit

#6320 Update release instructions and clean up update deps helper
  packages/devtools_extensions/bin/_build_and_copy.dart
  tool/RELEASE_INSTRUCTIONS.md
  tool/bin/devtools_tool.dart
  tool/bots.sh
  tool/build_e2e.dart
  tool/lib/commands/update_dart_sdk_deps.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/utils.dart
  tool/pubspec.yaml
  tool/update_sdk_deps.dart
Labels: release-notes-not-required, run-dcm-workflow

#6321 Migrate the update_version.dart script to the devtools_tool command runner
  .github/workflows/daily-dev-bump.yaml
  tool/RELEASE_INSTRUCTIONS.md
  tool/bots.sh
  tool/lib/commands/pub_get.dart
  tool/lib/commands/update_version.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/model.dart
  tool/pub_upgrade.sh
  tool/release_helper.sh
Labels: release-notes-not-required, run-dcm-workflow

#6327 Add event direction to `DevToolsExtensionEventType` values
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devices.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
  packages/devtools_extensions/lib/src/api/api.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/test/api_test.dart
  packages/devtools_shared/test/deeplink/deeplink_manager_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6331 Add theme support for devtools extensions
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/extensions/embedded/controller.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
  packages/devtools_extensions/lib/src/api/api.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_connect_ui.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_controller.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/test/api_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6334 Catching up on current release by bumping minor and dev
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/images/logger_copy.png
  packages/devtools_test/pubspec.yaml
Labels: autosubmit, dcm-workflow

#6335 Pull vm service uri from extension iFrame query parameters
  packages/devtools_extensions/lib/src/template/extension_manager.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6332 Fix minor updates so that the template properly resets
  tool/analysis_options.yaml
  tool/lib/commands/update_version.dart
Labels: release-notes-not-required, run-dcm-workflow

#6338 Fix some DCM lints and replace stub openDevToolsPage with a generic no-op handler
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
Labels: release-notes-not-required, run-dcm-workflow

#6343 Add back removed release notes image
  packages/devtools_app/release_notes/images/logger_copy.png
Labels: autosubmit

#6330 Convert release_helper from sh to dart
  tool/RELEASE_INSTRUCTIONS.md
  tool/analysis_options.yaml
  tool/lib/commands/release_helper.dart
  tool/lib/commands/rollback.dart
  tool/lib/commands/update_dart_sdk_deps.dart
  tool/lib/commands/update_version.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/utils.dart
  tool/pubspec.yaml
  tool/release_helper.sh
  tool/update_perfetto_assets.dart
Labels: release-notes-not-required, run-dcm-workflow

#6358 Refresh available extensions when the main isolate changes.
  packages/devtools_app/lib/src/extensions/extension_service.dart
Labels: release-notes-not-required, run-dcm-workflow

#6356 Ensure vm service connection is established on page refresh.
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/lib/src/framework/initializer.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/routing.dart
  packages/devtools_app/test/debugger/debugger_codeview_statistics_test.dart
  packages/devtools_app/test/debugger/debugger_codeview_test.dart
  packages/devtools_app/test/debugger/debugger_screen_breakpoints_test.dart
  packages/devtools_app/test/debugger/debugger_screen_call_stack_test.dart
  packages/devtools_app/test/debugger/debugger_screen_dap_variables_test.dart
  packages/devtools_app/test/debugger/debugger_screen_explorer_hidden_test.dart
  packages/devtools_app/test/debugger/debugger_screen_explorer_visibility_test.dart
  packages/devtools_app/test/debugger/debugger_screen_explorer_visible_test.dart
  packages/devtools_app/test/debugger/debugger_screen_paused_test.dart
  packages/devtools_app/test/debugger/debugger_screen_variables_test.dart
  packages/devtools_app/test/debugger/debugger_scripts_test.dart
  packages/devtools_app/test/extensions/extension_settings_test.dart
  packages/devtools_app/test/performance/timeline_events/legacy/event_details_test.dart
  packages/devtools_app/test/primitives/utils_test.dart
  packages/devtools_app/test/shared/editable_list_test.dart
  packages/devtools_app/test/shared/scaffold_debugger_test.dart
  packages/devtools_app/test/shared/scaffold_debugging_controls_test.dart
  packages/devtools_app/test/shared/scaffold_no_app_test.dart
  packages/devtools_app/test/shared/scaffold_profile_test.dart
  packages/devtools_app/test/shared/scaffold_test.dart
  packages/devtools_app/test/test_infra/goldens/codeview_scrollbars.png
  packages/devtools_app/test/vm_developer/object_inspector/class_hierarchy_explorer_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_code_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_object_pool_display_test.dart
  packages/devtools_app_shared/lib/src/service/service_manager.dart
  packages/devtools_app_shared/lib/src/utils/utils.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_test/lib/src/mocks/fake_service_manager.dart
  packages/devtools_test/lib/src/wrappers.dart
Labels: release-notes-not-required, run-dcm-workflow

#6367 Add development flag for debugging devtools extensions without a server connection
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_web.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/macos/Runner.xcodeproj/project.pbxproj
  packages/devtools_app/test/shared/development_helpers_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6362 Remove top buttons from VS Code sidebar
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
Labels: release-notes-not-required, run-dcm-workflow

#6344 Provide more context on release notes
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/helpers/release_notes_template.md
Labels: autosubmit

#6363 Add Hot Reload + Hot Restart functionality to sidebar
  packages/devtools_app/lib/src/service/service_registrations.dart
  packages/devtools_app/lib/src/shared/constants.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
Labels: release-notes-not-required, run-dcm-workflow

#6368 Add an action to force a reload of a DevTools extension
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/embedded/controller.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/extension_screen_controls.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/test/extensions/extension_screen_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6373 Add end to end integration test for DevTools extensions
  packages/devtools_app/integration_test/test/live_connection/app_test.dart
  packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart
  packages/devtools_app/integration_test/test/live_connection/devtools_extensions_test.dart
  packages/devtools_app/integration_test/test/live_connection/eval_and_browse_test.dart
  packages/devtools_app/integration_test/test/live_connection/performance_screen_event_recording_test.dart
  packages/devtools_app/integration_test/test/live_connection/service_connection_test.dart
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/test/test_infra/goldens/integration_inspector_errors_2_error_selected.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_except_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_scene_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_showAll_diff.png
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#6383 Add extension setting to show only enabled extension screens
  packages/devtools_app/integration_test/test/live_connection/devtools_extensions_test.dart
  packages/devtools_app/lib/src/extensions/extension_screen_controls.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/extensions/extension_settings.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/preferences.dart
  packages/devtools_app/test/extensions/extension_settings_test.dart
  packages/devtools_app/test/shared/preferences_controller_test.dart
  packages/devtools_app/test/test_infra/goldens/extensions/settings_state_modified.png
  packages/devtools_app/test/test_infra/goldens/extensions/settings_state_none.png
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
  packages/devtools_test/lib/src/mocks/generated_mocks_factories.dart
Labels: release-notes-not-required, run-dcm-workflow

#6384 Enable DevTools Extension support by default.
  packages/devtools_app/integration_test/test/live_connection/app_test.dart
  packages/devtools_app/integration_test/test/live_connection/devtools_extensions_test.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/images/example_devtools_extension.png
Labels: run-dcm-workflow

#6385 Shard flutter integration tests
  .github/workflows/build.yaml
  packages/devtools_app/integration_test/run_tests.dart
  packages/devtools_app/integration_test/test/live_connection/devtools_extensions_test.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  tool/bots.sh
Labels: release-notes-not-required, run-dcm-workflow

#6390 Fix leaking listeners added to the `html.window` element.
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_web.dart
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_controller.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6393 Fix latency issue with showing banner message from DevTools extension
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/shared/banner_messages.dart
Labels: release-notes-not-required, run-dcm-workflow

#6364 Convert Fix Goldens to dart script
  .github/workflows/build.yaml
  tool/fix_goldens.sh
  tool/lib/commands/fix_goldens.dart
  tool/lib/devtools_command_runner.dart
Labels: release-notes-not-required, run-dcm-workflow

#6402 Update `devtools_extensions` readme
  packages/devtools_app/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6403 Fix isolate selector theme bug
  packages/devtools_app/lib/src/framework/status_line.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: run-dcm-workflow

#6404 Add a more clear description to the extension enablement prompt
  packages/devtools_app/lib/src/extensions/extension_screen_controls.dart
Labels: release-notes-not-required, run-dcm-workflow

#6380 Improve the VS Code sidebar UI
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devices.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
Labels: release-notes-not-required, run-dcm-workflow

#6406 Add `ignoreIfAlreadyDismissed` parameter to extensions `showBannerMessage` API
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/shared/banner_messages.dart
  packages/devtools_app/test/shared/banner_messages_test.dart
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/flutter_service_worker.js
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/index.html
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/main.dart.js
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/main.dart
  packages/devtools_extensions/lib/src/api/model.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
Labels: release-notes-not-required, run-dcm-workflow

#6418 Add IDE to pre-filled issue description
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#6417 Add `forceReload` endpoint to the extensions API
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/extensions/embedded/controller.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/api/api.dart
  packages/devtools_extensions/lib/src/api/model.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_controller.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/test/api_test.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6420 Update the extension iFrame's query parameters for theme and vm service uri changes
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
  packages/devtools_app/lib/src/shared/preferences.dart
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_connect_ui.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
Labels: release-notes-not-required, run-dcm-workflow

#6426 Clean up lint violations across packages
  packages/analysis_options.yaml
  packages/devtools_app/analysis_options.yaml
  packages/devtools_app_shared/analysis_options.yaml
  packages/devtools_app_shared/lib/src/service/service_manager.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/analysis_options.yaml
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/lib/src/extensions/extension_enablement.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/lib/src/test/chrome.dart
  packages/devtools_shared/lib/src/test/cli_test_driver.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#6428 Move integration test runner code to devtools_shared
  packages/devtools_app/integration_test/run_tests.dart
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/devtools_test_utils.dart
  packages/devtools_shared/lib/src/test/chrome.dart
  packages/devtools_shared/lib/src/test/chrome_driver.dart
  packages/devtools_shared/lib/src/test/integration_test_runner.dart
  packages/devtools_shared/lib/src/test/io_utils.dart
  packages/devtools_shared/lib/src/test/utils_io.dart
  packages/devtools_shared/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6429 Refactor devtools_extensions example
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/main.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/foo_devtools_extension.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/pubspec.yaml
  packages/devtools_shared/lib/src/extensions/extension_enablement.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#6424 Tidy up sidebar + use screen metadata
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/standalone_ui/standalone_screen.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devices.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/test/shared/screens_test.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code_mock_editor.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
Labels: release-notes-not-required, run-dcm-workflow

#6405 Adds more deeplink apis
  packages/devtools_app/lib/src/shared/config_specific/server/_server_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_web.dart
  packages/devtools_app/test/shared/screens_test.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/devtools_deeplink.dart
  packages/devtools_shared/lib/src/deeplink/app_link_settings.dart
  packages/devtools_shared/lib/src/deeplink/deeplink_manager.dart
  packages/devtools_shared/lib/src/deeplink/universal_link_settings.dart
  packages/devtools_shared/lib/src/deeplink/xcode_build_options.dart
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/deeplink/deeplink_manager_test.dart
  packages/devtools_shared/test/server/server_api_test.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6440 Add stack trace to error reporting from notifications
  packages/devtools_app/lib/src/framework/app_error_handling.dart
  packages/devtools_app/lib/src/shared/notifications.dart
Labels: release-notes-not-required, run-dcm-workflow

#6433 Add an integration test for `package:devtools_extensions`
  .github/workflows/build.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/assets/FontManifest.json
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/assets/fonts/MaterialIcons-Regular.otf
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/flutter_service_worker.js
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/index.html
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/main.dart.js
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/foo_devtools_extension.dart
  packages/devtools_extensions/integration_test/run_tests.dart
  packages/devtools_extensions/integration_test/test/simulated_environment_test.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_connect_ui.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_controller.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_extensions/test_driver/integration_test.dart
  tool/bots.sh
Labels: release-notes-not-required, run-dcm-workflow

#6341 Show hot restart and hot reload button based on service availability
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/service_extension_manager.dart
  packages/devtools_app_shared/lib/src/service/service_manager.dart
  packages/devtools_app_shared/pubspec.yaml
Labels: run-dcm-workflow

#6442 Disable DevTools extensions in g3
  packages/devtools_app/lib/src/shared/feature_flags.dart
Labels: release-notes-not-required, run-dcm-workflow

#6448 Some cleanup for the VS Code mock editor
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code_mock_editor.dart
Labels: release-notes-not-required, run-dcm-workflow

#6444 Add analytics to VS Code sidebar panel actions
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/utils.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devices.dart
Labels: release-notes-not-required, run-dcm-workflow

#6452 Fix analytics bug from the migration to GA4
  packages/devtools_app/web/index.html
Labels: release-notes-not-required, run-dcm-workflow

#6455 Fix index out of range error when animating to a tab
  packages/devtools_app/lib/src/framework/scaffold.dart
Labels: release-notes-not-required, run-dcm-workflow

#6454 Hide the isolate selector on extension screens
  packages/devtools_app/lib/src/extensions/extension_screen.dart
Labels: release-notes-not-required, run-dcm-workflow

#6453 Clean up analytics for DevTools extensions
  packages/devtools_app/lib/src/extensions/embedded/view.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/extension_screen_controls.dart
  packages/devtools_app/lib/src/extensions/extension_settings.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_stub.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_extension_constants.dart
  packages/devtools_app/web/devtools_analytics.js
Labels: release-notes-not-required, run-dcm-workflow

#6450 Handle isolate disappearing while loading isolate state
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/isolate_manager.dart
Labels: run-dcm-workflow

#6465 Remove flag for sidebar
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code.dart
Labels: release-notes-not-required, run-dcm-workflow

#6436 Reselect main isolate when hot restarting
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app_shared/lib/src/service/isolate_manager.dart
Labels: run-dcm-workflow

#6451 Protect service restoration against SentinelException
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app_shared/lib/src/service/service_extension_manager.dart
Labels: autosubmit, run-dcm-workflow

#6434 Widget inspector should operate on main isolate, not selected isolate
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: autosubmit, run-dcm-workflow

#6466 Use Google Tag id for analytics setup instead of GA4 property id
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/gtags.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/web/devtools_analytics.js
  packages/devtools_app/web/index.html
Labels: release-notes-not-required, run-dcm-workflow

#6471 Prepare for release 2.28.0
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6474 Refactor analytics constants using part files - 1
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_cpu_profiler_constants.dart
Labels: release-notes-not-required, run-dcm-workflow

#6475 Refactor analytics constants using part files - 2
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_memory_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_performance_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_vs_code_sidebar_constants.dart
Labels: release-notes-not-required, run-dcm-workflow

#6478 Fix bug in `build_and_copy` executable
  packages/devtools_app/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/bin/_build_and_copy.dart
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6485 Flip debugAnalytics flag to false and prepare 2.28.1 release
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/shared/development_helpers_test.dart
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6487 Add debug flag for debugging DevTools survey
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/survey.dart
  packages/devtools_app/test/shared/development_helpers_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6483 Fixes to release process
  .github/workflows/daily-dev-bump.yaml
  tool/RELEASE_INSTRUCTIONS.md
  tool/bin/devtools_tool
  tool/bots.sh
  tool/lib/commands/update_dart_sdk_deps.dart
Labels: release-notes-not-required, run-dcm-workflow

#6147 Add Deep link validation tool home page with fake data
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/fake_data.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/ui/colors.dart
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
Labels: release-notes-not-required, run-dcm-workflow

#6490 Tweak Windows instructions to mirror macOS
  tool/RELEASE_INSTRUCTIONS.md
  tool/bin/devtools_tool.bat
  tool/lib/commands/list.dart
Labels: tool, release-notes-not-required, run-dcm-workflow
