Repository flutter/devtools, pull requests merged in 2023-06, with the labels that each got.

#5872 Fix version collision.
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#5875 Improves app bar navigation by adding an overflow menu
  packages/devtools_app/lib/src/framework/app_bar.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/screens/memory/shared/primitives/instance_context_menu.dart
  packages/devtools_app/lib/src/screens/memory/shared/shared_memory_widgets.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/lib/src/shared/screen.dart
  packages/devtools_app/lib/src/shared/theme.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/primitives/utils_test.dart
  packages/devtools_app/test/shared/scaffold_test.dart
Labels: run-dcm-workflow

#5866 Fix scrolling to selected stack frame
  packages/devtools_app/lib/src/screens/debugger/call_stack.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart
Labels: release-notes-not-required, run-dcm-workflow

#5876 Scaffolding cleanup
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/framework/app_bar.dart
  packages/devtools_app/lib/src/framework/initializer.dart
  packages/devtools_app/lib/src/framework/landing_screen.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/shared/routing.dart
Labels: release-notes-not-required, run-dcm-workflow

#5865 Add support for routing to a standalone screen
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/lib/src/standalone_ui/standalone_screen.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
Labels: release-notes-not-required, run-dcm-workflow

#5854 Add a debugger panel integration test
  packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart
  packages/devtools_app/macos/Runner.xcodeproj/project.pbxproj
  packages/devtools_app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/devtools_app/test/test_infra/fixtures/flutter_app/lib/main.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_app/lib/src/other_classes.dart
Labels: release-notes-not-required, run-dcm-workflow

#5880 Prepare for weak references in inspector.
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/ui/layout_explorer_widget.dart
Labels: release-notes-not-required, run-dcm-workflow

#5895 Fix for new multi view hitTestInView behaviour
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_web.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/drag_and_drop.dart
Labels: release-notes-not-required, run-dcm-workflow

#5907 Consolidate dcm-label paths
  .github/workflows/dcm-label.yaml
Labels: release-notes-not-required, run-dcm-workflow

#5905 Fix broken integration test
  .gitignore
  packages/devtools_app/integration_test/README.md
  packages/devtools_app/integration_test/test/live_connection/app_test.dart
  packages/devtools_app/integration_test/test/live_connection/eval_and_browse_test.dart
  packages/devtools_app/integration_test/test_infra/run/_io_utils.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_stub.dart
  packages/devtools_app/test/shared/scaffold_test.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#5914 Fix icon to be g3 compatible
  packages/devtools_app/lib/src/framework/app_bar.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#5916 Move some service manager tests to a proper integration test
  packages/devtools_app/integration_test/test/live_connection/service_connection_test.dart
  packages/devtools_app/integration_test/test_infra/run/_io_utils.dart
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_app/lib/initialization.dart
  packages/devtools_app/lib/main.dart
  packages/devtools_app/lib/src/service/service.dart
  packages/devtools_app/lib/src/shared/globals.dart
  packages/devtools_app/test/shared/service_manager_test.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#5913 Stop referencing inspector_service from diagnostics_node to simplify mental model.
  packages/analysis_options.yaml
  packages/devtools_app/lib/src/screens/inspector/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/flex/flex.dart
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/ui/layout_explorer_widget.dart
  packages/devtools_app/lib/src/shared/console/console_service.dart
  packages/devtools_app/lib/src/shared/console/widgets/description.dart
  packages/devtools_app/lib/src/shared/diagnostics/diagnostics_node.dart
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/lib/src/shared/diagnostics/object_group_api.dart
  packages/devtools_app/lib/src/shared/diagnostics/tree_builder.dart
  packages/devtools_app/lib/src/shared/diagnostics/variable_factory.dart
  packages/devtools_app/test/inspector/diagnostics_test.dart
  packages/devtools_test/lib/src/mocks/generated.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#5925 Use `github.event.pull_request.head.sha` as PR reference in DCM workflow
  .github/workflows/dcm.yaml
  .github/workflows/flutter-prep.yaml
Labels: autosubmit

#5926 Move filter to memory shared, to use it for memory profile.
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/class_data.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/classes_table_diff.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/classes_table_single.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/profile_view.dart
  packages/devtools_app/lib/src/screens/memory/panes/tracing/class_table.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/class_filter.dart
  packages/devtools_app/lib/src/screens/memory/shared/widgets/class_filter.dart
  packages/devtools_app/lib/src/screens/memory/shared/widgets/shared_memory_widgets.dart
  packages/devtools_app/test/memory/diff/widgets/class_filter_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#5917 Run integration tests connected to a `chrome` device
  packages/devtools_app/integration_test/run_tests.dart
  packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_app/lib/main.dart
  tool/bots.sh
Labels: release-notes-not-required, run-dcm-workflow

#5918 Pass 'valueId' (Diagnosticable) instead of 'objectId' (DiagnosticsNode) to inspector API.
  packages/devtools_app/lib/src/screens/inspector/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/ui/layout_explorer_widget.dart
  packages/devtools_app/lib/src/shared/console/eval/eval_service.dart
  packages/devtools_app/lib/src/shared/diagnostics/diagnostics_node.dart
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/test/shared/diagnostics/diagnostics_node_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#5919 Migrate `service_mananger_test.dart` test cases to proper integration test
  packages/devtools_app/integration_test/test/live_connection/service_connection_test.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/framework/status_line.dart
  packages/devtools_app/lib/src/screens/debugger/codeview_controller.dart
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
  packages/devtools_app/lib/src/shared/device_dialog.dart
  packages/devtools_app/test/shared/device_dialog_test.dart
  packages/devtools_app/test/shared/service_manager_test.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#5939 Migrate DevTools analytics to GA4
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/metrics.dart
  packages/devtools_app/web/devtools_analytics.js
  packages/devtools_app/web/index.html
Labels: release-notes-not-required, run-dcm-workflow

#5940 Fix failing bots at master.
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_list.dart
  packages/devtools_app/lib/src/screens/provider/instance_viewer/instance_viewer.dart
Labels: release-notes-not-required, run-dcm-workflow

#5941 Make InstanceViewWithContextMenu not opinionated about menu actions.
  packages/devtools_app/integration_test/test/live_connection/eval_and_browse_test.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/sampler.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/class_details/instances_menu.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/instances.dart
  packages/devtools_app/lib/src/screens/memory/shared/primitives/instance_context_menu.dart
Labels: release-notes-not-required, run-dcm-workflow

#5943 Add dart doc to custom analytics metrics
  packages/devtools_app/lib/src/shared/analytics/metrics.dart
Labels: release-notes-not-required, run-dcm-workflow

#5945 Add method for testing release notes and update readme
  packages/devtools_app/lib/src/framework/release_notes/release_notes.dart
  packages/devtools_app/release_notes/README.md
Labels: release-notes-not-required, run-dcm-workflow

#5942 Import web-only APIs from dart:ui_web
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#5957 Clean up logs.
  .gitignore
  packages/devtools_app/flutter_01.log
  packages/devtools_app/flutter_02.log
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#5966 Fix lint warnings at master.
  packages/devtools_app/test/test_infra/fixtures/flutter_app/lib/main.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_app/lib/overflow_errors.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_app/lib/src/other_classes.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_error_app/lib/main.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_error_app/lib/missing_material_error.dart
Labels: release-notes-not-required, run-dcm-workflow

#5956 Releasing from 2.25.0-dev.5 to 2.25.0
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_shared/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#5964 Add verbose debugging logging to the `shouldShowScreen` method
  packages/devtools_app/lib/src/shared/screen.dart
Labels: release-notes-not-required, run-dcm-workflow

#5972 Fix the debugger panel integration test
  packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_app/lib/main.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_app/lib/src/other_classes.dart
Labels: release-notes-not-required, run-dcm-workflow

#5969 Add more verbose logging to the service manager
  packages/devtools_app/lib/src/service/service_manager.dart
Labels: release-notes-not-required, run-dcm-workflow

#5971 Use `package:args` to parse integration test arguments
  packages/devtools_app/integration_test/run_tests.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#5968 Updating from 2.25.0 to 2.26.0-dev.0
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_shared/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: autosubmit, run-dcm-workflow

#5816 feat(Network profiler): create response selector for http response
  packages/devtools_app/lib/src/screens/network/network_controller.dart
  packages/devtools_app/lib/src/screens/network/network_request_inspector.dart
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/network/network_profiler_test.dart
  packages/devtools_app/test/network/network_request_inspector_test.dart
Labels: run-dcm-workflow

#5976 Start chromedriver once for running all integration tests
  packages/devtools_app/integration_test/run_tests.dart
  packages/devtools_app/integration_test/test_infra/run/_chrome_driver.dart
  packages/devtools_app/integration_test/test_infra/run/_utils.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#5981 Add Dart CLI test target to integration tests
  .github/workflows/build.yaml
  packages/devtools_app/integration_test/run_tests.dart
  packages/devtools_app/integration_test/test_infra/run/_chrome_driver.dart
  packages/devtools_app/integration_test/test_infra/run/_in_file_args.dart
  packages/devtools_app/integration_test/test_infra/run/_io_utils.dart
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_app/test/integration_test_infra/in_file_args_test.dart
  tool/bots.sh
Labels: release-notes-not-required, run-dcm-workflow

#5975 Expand notifications to fill the space they block
  packages/devtools_app/lib/src/framework/notifications_view.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: run-dcm-workflow
