Repository flutter/devtools, pull requests merged in 2023-07, with the labels that each got.

#5982 Fix lints and warnings.
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
  packages/devtools_app/test/network/network_request_inspector_test.dart
  packages/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#5965 Initial structure for offline memory screen.
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/framework/landing_screen.dart
  packages/devtools_app/lib/src/screens/memory/framework/README.md
  packages/devtools_app/lib/src/screens/memory/framework/connected/connected_screen_body.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_protocol.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_tabs.dart
  packages/devtools_app/lib/src/screens/memory/framework/memory_screen.dart
  packages/devtools_app/lib/src/screens/memory/framework/static/static_screen_body.dart
  packages/devtools_app/lib/src/screens/memory/memory_screen.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/chart_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/interval_dropdown.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_android_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_charts.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_events_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_vm_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/secondary_controls.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/lib/src/shared/routing.dart
  packages/devtools_app/test/memory/control/settings_dialog_test.dart
  packages/devtools_app/test/memory/diff/widgets/diff_pane_test.dart
  packages/devtools_app/test/memory/memory_service_test.dart
  packages/devtools_app/test/memory/profile/allocation_profile_table_view_test.dart
  packages/devtools_app/test/memory/tracing/tracing_view_test.dart
  packages/devtools_app/test/shared/error_badge_manager_test.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#5998 Stop logging http to timeline by default and warn users about memory implications
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/connected_screen_body.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frames_chart.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_view.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/screens/provider/provider_screen.dart
  packages/devtools_app/lib/src/shared/banner_messages.dart
  packages/devtools_app/lib/src/shared/globals.dart
  packages/devtools_app/lib/src/shared/http/http_service.dart
  packages/devtools_app/lib/src/shared/ui/vm_flag_widgets.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/cpu_profiler/cpu_profiler_test.dart
  packages/devtools_app/test/memory/memory_screen_test.dart
  packages/devtools_app/test/performance/flutter_frames/flutter_frames_chart_test.dart
  packages/devtools_app/test/provider/provider_screen_test.dart
  packages/devtools_app/test/shared/banner_messages_test.dart
  packages/devtools_app/test/shared/scaffold_debugger_test.dart
  packages/devtools_app/test/shared/scaffold_debugging_controls_test.dart
  packages/devtools_app/test/shared/scaffold_no_app_test.dart
  packages/devtools_app/test/shared/scaffold_profile_test.dart
  packages/devtools_app/test/shared/scaffold_test.dart
  packages/devtools_app/test/shared/vm_flag_widgets_test.dart
  packages/devtools_app/test/test_infra/scenes/cpu_profiler/default.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
  packages/devtools_app/test/test_infra/scenes/performance/default.dart
  packages/devtools_app/test/vm_developer/object_inspector/class_hierarchy_explorer_test.dart
  packages/devtools_test/lib/src/wrappers.dart
Labels: run-dcm-workflow

#5997 Add a context menu to rename or delete a heap snapshot from the list
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/diff_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/item_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_list.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/memory/diff/widgets/diff_pane_test.dart
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty1.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty2.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_selected_class.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_custom_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_custom_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_except_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_except_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_only_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_only_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_scene_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_scene_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_showAll_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_showAll_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_three_snapshots1.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_three_snapshots2.png
Labels: run-dcm-workflow

#6003 Move import action from landing screen to toolbar
  packages/devtools_app/lib/src/framework/landing_screen.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/import_export.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/shared/landing_screen_test.dart
  packages/devtools_app/test/shared/scaffold_test.dart
Labels: run-dcm-workflow

#6004 Add connection info widgets and clean up device dialog
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/framework/landing_screen.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/connection_info.dart
  packages/devtools_app/lib/src/shared/device_dialog.dart
  packages/devtools_app/lib/src/shared/dialogs.dart
  packages/devtools_app/lib/src/shared/ui/vm_flag_widgets.dart
  packages/devtools_app/lib/src/shared/utils.dart
  packages/devtools_app/test/shared/device_dialog_test.dart
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_custom.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_except.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_only.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_showAll.png
Labels: release-notes-not-required, run-dcm-workflow

#5999 Create a new shared `AnalyticsDropDownButton`
  packages/devtools_app/lib/src/shared/ui/drop_down_button.dart
  packages/devtools_app/lib/src/shared/ui/vm_flag_widgets.dart
  packages/devtools_app/test/shared/vm_flag_widgets_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6008 Update Object Inspector selector to use a drop down instead of a tab bar
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_inspector_view.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/ui/drop_down_button.dart
  packages/devtools_app/test/vm_developer/object_inspector/object_inspector_view_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6009 Fix UI bugs in Object Inspector
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_common_widgets.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_developer_common_widgets_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_library_display_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6010 Add support for static tooling in DevTools and add a "Home" screen
  packages/devtools_app/integration_test/test/live_connection/eval_and_browse_test.dart
  packages/devtools_app/integration_test/test/live_connection/service_connection_test.dart
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/initialization.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/framework/app_bar.dart
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/framework/status_line.dart
  packages/devtools_app/lib/src/screens/app_size/app_size_screen.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_screen.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/connected_screen_body.dart
  packages/devtools_app/lib/src/screens/memory/framework/memory_screen.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen.dart
  packages/devtools_app/lib/src/screens/provider/provider_screen.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_tools_screen.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/import_export.dart
  packages/devtools_app/lib/src/shared/console/widgets/display_provider.dart
  packages/devtools_app/lib/src/shared/device_dialog.dart
  packages/devtools_app/lib/src/shared/primitives/simple_items.dart
  packages/devtools_app/lib/src/shared/screen.dart
  packages/devtools_app/lib/src/shared/ui/vm_flag_widgets.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/images/home_screen.png
  packages/devtools_app/release_notes/images/load_data.png
  packages/devtools_app/test/shared/connection_info_test.dart
  packages/devtools_app/test/shared/home_screen_test.dart
  packages/devtools_app/test/shared/landing_screen_test.dart
  packages/devtools_app/test/shared/scaffold_test.dart
  packages/devtools_app/test/shared/visible_screens_test.dart
  packages/devtools_app/test/shared/vm_flag_widgets_test.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: run-dcm-workflow

#6001 Remove tooltip during variable inspection
  packages/devtools_app/lib/src/shared/console/widgets/display_provider.dart
  packages/devtools_app/test/debugger/debugger_screen_variables_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6012 Fix text selection behavior in object inspector views
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_inspector_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_common_widgets.dart
  packages/devtools_app/test/vm_developer/object_inspector/class_hierarchy_explorer_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_class_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_developer_common_widgets_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_field_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_function_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_ic_data_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_library_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_object_pool_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_script_display_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6015 Color DevTools footer to indicate app connection state
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/framework/about_dialog.dart
  packages/devtools_app/lib/src/framework/report_feedback_button.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/framework/settings_dialog.dart
  packages/devtools_app/lib/src/framework/status_line.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/import_export.dart
  packages/devtools_app/test/shared/scaffold_debugger_test.dart
  packages/devtools_app/test/shared/scaffold_debugging_controls_test.dart
  packages/devtools_app/test/shared/scaffold_no_app_test.dart
  packages/devtools_app/test/shared/scaffold_profile_test.dart
  packages/devtools_app/test/shared/scaffold_test.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#6022 Add skeleton for deep link validation tool
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/lib/src/shared/screen.dart
Labels: release-notes-not-required, run-dcm-workflow

#6027 Remove one test from provider_screen_integration_test.dart
  packages/devtools_app/test/provider/provider_screen_integration_test.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6020 Debugger panel text selection improvements
  packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/screens/debugger/codeview.dart
  packages/devtools_app/lib/src/shared/console/console.dart
  packages/devtools_app/lib/src/shared/console/widgets/display_provider.dart
  packages/devtools_app/lib/src/shared/primitives/selection_controls.dart
  packages/devtools_app/lib/src/shared/tree.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/debugger/debugger_screen_test.dart
  packages/devtools_app/test/debugger/debugger_screen_variables_test.dart
  packages/devtools_app/test/debugger/variables_test.dart
Labels: run-dcm-workflow

#6028 Fix routing issue when refreshing DevTools
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_screen.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/routing.dart
  packages/devtools_app/lib/src/shared/screen.dart
  packages/devtools_app/test/shared/initializer_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6038 Remove uses of `shrinkWrap` in DevTools
  packages/devtools_app/lib/src/screens/debugger/program_explorer.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/legend.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_charts.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_events_pane.dart
  packages/devtools_app/lib/src/shared/console/widgets/expandable_variable.dart
  packages/devtools_app/lib/src/shared/tree.dart
  packages/devtools_app/lib/src/shared/ui/search.dart
Labels: release-notes-not-required, run-dcm-workflow

#6034 workflow for updating flutter candidate
  .github/workflows/daily-dev-bump.yaml
  .github/workflows/flutter-candidate-update.yaml
  flutter-candidate.txt
  tool/README.md
Labels: autosubmit, dake-test, release-notes-not-required, run-dcm-workflow

#6039 Add support for new timeline event names `LAYOUT (root)` and `PAINT (root)`
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_analysis_model.dart
  packages/devtools_app/test/performance/frame_analysis/frame_hints_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#5986 Set properties to null when none are available
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/box/box.dart
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/ui/layout_explorer_widget.dart
Labels: release-notes-not-required, run-dcm-workflow, Multi View

#6046 Clean up duplicate connection available indicator in service manager
  packages/devtools_app/lib/src/extensions/README.md
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/lib/src/framework/initializer.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_controller.dart
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/screens/provider/instance_viewer/eval.dart
  packages/devtools_app/lib/src/screens/provider/provider_screen.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/preferences.dart
  packages/devtools_app/lib/src/shared/scripts/script_manager.dart
  packages/devtools_app/test/shared/initializer_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_code_display_test.dart
  packages/devtools_test/lib/src/mocks/fake_service_manager.dart
Labels: release-notes-not-required, run-dcm-workflow

#6052 Update goldens and devtools_app README
  packages/devtools_app/README.md
  packages/devtools_app/test/inspector/inspector_integration_test.dart
  packages/devtools_app/test/memory/diff/widgets/class_filter_test.dart
  packages/devtools_app/test/test_infra/flutter_test_environment.dart
  packages/devtools_app/test/test_infra/goldens/instance_viewer/bool.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/collasped_list.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/collasped_map.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/collasped_object.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/edit.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/edit_esc.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/enum.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/error.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/expanded_list.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/expanded_map.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/expanded_object.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/loading.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/null.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/num.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/show_internal_properties.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/string.png
  packages/devtools_app/test/test_infra/goldens/integration_animated_physical_model_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_richtext_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_scaffold_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center_details_tree.png
Labels: release-notes-not-required, run-dcm-workflow

#6048 Add logic to conditionally show available extensions
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/extensions/extension_model.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/extensions/ui/extension_screen.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/lib/src/shared/globals.dart
Labels: release-notes-not-required, run-dcm-workflow

#6053 UI polish for the DevTools app bar and "page not found" screen
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/framework/app_bar.dart
  packages/devtools_app/lib/src/shared/screen.dart
Labels: release-notes-not-required, run-dcm-workflow

#6057 Fix breakages from latest flutter.
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/flex/flex.dart
  packages/devtools_app/lib/src/shared/charts/chart.dart
  packages/devtools_app/test/shared/extent_delegate_test.dart
  packages/devtools_app/test/test_infra/goldens/integration_animated_physical_model_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_errors_1_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_errors_2_error_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_richtext_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_scaffold_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center_details_tree.png
  packages/devtools_app/test/test_infra/utils/rendering_tester.dart
Labels: release-notes-not-required, run-dcm-workflow

#6055 Initial commit for `package:devtools_extensions`
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
  packages/devtools_extensions/.gitignore
  packages/devtools_extensions/.metadata
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/LICENSE
  packages/devtools_extensions/README.md
  packages/devtools_extensions/devtools_extensions.iml
  packages/devtools_extensions/lib/devtools_extensions.dart
  packages/devtools_extensions/lib/src/api.dart
  packages/devtools_extensions/lib/src/model.dart
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_extensions/test/devtools_extensions_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6054 Add skeleton for extension screen views and controllers
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/extensions/embedded/_controller_desktop.dart
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_desktop.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/extensions/embedded/controller.dart
  packages/devtools_app/lib/src/extensions/embedded/view.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/ui/extension_screen.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/screen.dart
  packages/devtools_app/test/extensions/extension_screen_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6060 Add embedded iFrame logic for DevTools extensions
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/extensions/embedded/_controller_desktop.dart
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/extensions/embedded/controller.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/framework/app_bar.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/test_infra/test_data/cpu_profiler/cpu_profile.dart
  packages/devtools_extensions/lib/src/model.dart
Labels: release-notes-not-required, run-dcm-workflow

#6067 Fix hover background shape for `DebuggerButton`s
  packages/devtools_app/lib/src/screens/debugger/controls.dart
Labels: release-notes-not-required, run-dcm-workflow

#6069 Add `example` to `devtools_extensions` package
  packages/devtools_extensions/example/foo_devtools_extension/.gitignore
  packages/devtools_extensions/example/foo_devtools_extension/README.md
  packages/devtools_extensions/example/foo_devtools_extension/lib/main.dart
  packages/devtools_extensions/example/foo_devtools_extension/pubspec.yaml
  packages/devtools_extensions/example/foo_devtools_extension/web/favicon.png
  packages/devtools_extensions/example/foo_devtools_extension/web/icons/Icon-192.png
  packages/devtools_extensions/example/foo_devtools_extension/web/icons/Icon-512.png
  packages/devtools_extensions/example/foo_devtools_extension/web/icons/Icon-maskable-192.png
  packages/devtools_extensions/example/foo_devtools_extension/web/icons/Icon-maskable-512.png
  packages/devtools_extensions/example/foo_devtools_extension/web/index.html
  packages/devtools_extensions/example/foo_devtools_extension/web/manifest.json
Labels: release-notes-not-required, run-dcm-workflow

#6077 Remove mention of retired feature.
  packages/devtools_app/lib/src/screens/memory/panes/chart/chart_control_pane.dart
Labels: release-notes-not-required, run-dcm-workflow

#6085 [VM Tools] Add support for inspecting inbound references and internal VM types
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/inbound_references_tree.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_inspector_view_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_viewport.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_class_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_object_model.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_unknown_object_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_common_widgets.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_class_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_code_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_developer_common_widgets_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_field_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_function_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_ic_data_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_library_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_object_pool_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_script_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_simple_list_display_test.dart
  packages/devtools_app/test/vm_developer/vm_developer_test_utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#6090 [VM Tools] Fix open port inspector and UI inconsistencies
  packages/devtools_app/lib/src/screens/vm_developer/isolate_statistics/isolate_statistics_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_statistics/vm_statistics_view.dart
Labels: release-notes-not-required, run-dcm-workflow

#6099 Fix text selection issues in the codeview and console
  packages/devtools_app/lib/src/shared/console/console.dart
  packages/devtools_app/lib/src/shared/console/widgets/expandable_variable.dart
  packages/devtools_app/lib/src/shared/tree.dart
Labels: release-notes-not-required, run-dcm-workflow

#6096 Add skeleton for enabling the Performance screen for web apps
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/test/performance/performance_screen_test.dart
  packages/devtools_app/test/shared/visible_screens_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6098 Add `--no-build-app` flag to the `build_e2e.dart` script.
  tool/build_e2e.dart
Labels: release-notes-not-required, run-dcm-workflow

#6094 Add a server endpoint for serving devtools extensions
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/extensions/embedded/controller.dart
  packages/devtools_app/lib/src/extensions/extension_model.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_web.dart
  packages/devtools_app/test/extensions/extension_screen_test.dart
  packages/devtools_shared/lib/devtools_extensions.dart
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/lib/src/server/server_api.dart
Labels: release-notes-not-required, run-dcm-workflow

#6097 Load extensions from DevTools server instead of using stubs.
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/test/extensions/extension_model_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6100 Prevent console text from being cut-off
  packages/devtools_app/lib/src/shared/console/widgets/console_pane.dart
  packages/devtools_app/lib/src/shared/console/widgets/evaluate.dart
Labels: release-notes-not-required, run-dcm-workflow

#6070 Migrate `Variables` to use DAP
  packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart
  packages/devtools_app/lib/src/screens/debugger/variables.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/class_hierarchy_explorer.dart
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
  packages/devtools_app/lib/src/shared/connected_app.dart
  packages/devtools_app/lib/src/shared/console/widgets/display_provider.dart
  packages/devtools_app/lib/src/shared/diagnostics/dap_object_node.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/lib/src/shared/tree.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/debugger/debugger_screen_dap_variables_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6106 Add documentation comments for `DapDisplayProvider` and `DisplayProvider`
  packages/devtools_app/lib/src/shared/console/widgets/display_provider.dart
Labels: release-notes-not-required, run-dcm-workflow

#6107 Performance panel instructions for web apps
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/test/performance/performance_screen_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6118 Clean up build release sript
  tool/build_release.sh
Labels: autosubmit

#6117 Clean up some common widgets
  packages/devtools_app/lib/src/framework/about_dialog.dart
  packages/devtools_app/lib/src/framework/report_feedback_button.dart
  packages/devtools_app/lib/src/framework/settings_dialog.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/import_export.dart
  packages/devtools_app/lib/src/shared/ui/label.dart
Labels: release-notes-not-required, run-dcm-workflow

#6111 Add extensionActivationState endpoint to the devtools server
  packages/devtools_app/lib/src/shared/config_specific/server/_server_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_web.dart
  packages/devtools_extensions/.metadata
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/extensions/extension_activation.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/lib/src/server/usage.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/extensions/extension_activation_test.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6125 A couple fixes to the extensions server apis
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/extensions/extension_enablement.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/test/extensions/extension_enablement_test.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6126 Add warning message about breakpoints for Chrome version 115
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/shared/environment_parameters/environment_parameters_base.dart
  packages/devtools_app/lib/src/shared/environment_parameters/environment_parameters_external.dart
Labels: release-notes-not-required, run-dcm-workflow

#6127 Add `defaultBorderRadius` and `defaultRadius` helpers
  packages/devtools_app/lib/src/screens/debugger/controls.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_breadcrumbs.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/legend.dart
  packages/devtools_app/lib/src/screens/provider/instance_viewer/instance_viewer.dart
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
  packages/devtools_app/lib/src/shared/analytics/prompt.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/dialogs.dart
  packages/devtools_app/lib/src/shared/side_panel.dart
  packages/devtools_app/lib/src/shared/theme.dart
  packages/devtools_app/lib/src/shared/ui/hover.dart
Labels: release-notes-not-required, run-dcm-workflow

#6128 Cleanup stale test name
  packages/devtools_app/test/shared/environment_parameters/environment_parameters_external_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6130 Releasing from 2.26.0-dev.16 to 2.26.0
  packages/devtools_app/.gitignore
  packages/devtools_app/devtools_app.iml
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/devtools_extensions.iml
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/.gitignore
  packages/devtools_shared/devtools_shared.iml
  packages/devtools_shared/pubspec.yaml
  packages/devtools_test/.gitignore
  packages/devtools_test/devtools_test.iml
  packages/devtools_test/pubspec.yaml
  tool/release_helper.sh
  tool/update_version.dart
Labels: release-notes-not-required, run-dcm-workflow
