Repository flutter/devtools, pull requests merged in 2023-08, with the labels that each got.

#6129 Replace `DualValueListenableBuilder` with `MultiValueListenableBuilder`
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/framework/status_line.dart
  packages/devtools_app/lib/src/screens/debugger/breakpoints.dart
  packages/devtools_app/lib/src/screens/debugger/call_stack.dart
  packages/devtools_app/lib/src/screens/debugger/codeview.dart
  packages/devtools_app/lib/src/screens/debugger/controls.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/class_details/path.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_list.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_view.dart
  packages/devtools_app/lib/src/screens/memory/panes/leaks/primitives/analysis_status.dart
  packages/devtools_app/lib/src/screens/memory/panes/tracing/class_table.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/enhance_tracing/enhance_tracing.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frames_chart.dart
  packages/devtools_app/lib/src/screens/performance/panes/raster_stats/raster_stats.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_view.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/editable_list.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#6132 Remove `devtools_shared` dependency on `package:io`
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/test/extensions/extension_manager_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6136 Prep for patch release
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_shared/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6138 Add the extension settings dialog
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/extensions/extension_settings.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_web.dart
  packages/devtools_app/test/extensions/extension_screen_test.dart
  packages/devtools_app/test/extensions/extension_settings_test.dart
  packages/devtools_app/test/test_infra/goldens/extensions/settings_state_modified.png
  packages/devtools_app/test/test_infra/goldens/extensions/settings_state_none.png
  packages/devtools_app/test/test_infra/test_data/extensions.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_test/lib/src/mocks/generated.dart
Labels: release-notes-not-required, run-dcm-workflow

#6140 Add ability to enable and disable an extension from the extension screen
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/extension_screen_controls.dart
  packages/devtools_app/lib/src/extensions/extension_settings.dart
  packages/devtools_app/lib/src/shared/theme.dart
  packages/devtools_app/test/extensions/extension_screen_test.dart
  packages/devtools_app/test/extensions/extension_settings_test.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_test/lib/src/mocks/generated_mocks_factories.dart
Labels: release-notes-not-required, run-dcm-workflow

#6164 Update stager filenames in launch configuration / commands
  packages/.vscode/launch.json
  packages/devtools_app/.vscode/launch.json
  packages/devtools_app/test/test_infra/scenes/README.md
  packages/devtools_app/test/test_infra/scenes/cpu_profiler/default.dart
  packages/devtools_app/test/test_infra/scenes/hello.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
  packages/devtools_app/test/test_infra/scenes/memory/diff_snapshot.dart
  packages/devtools_app/test/test_infra/scenes/performance/default.dart
Labels: release-notes-not-required, run-dcm-workflow

#6174 Fix tab bar alignment for latest flutter
  packages/devtools_app/lib/src/shared/theme.dart
Labels: release-notes-not-required, run-dcm-workflow

#6175 Support vm service connection for DevTools extensions
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
  packages/devtools_app/lib/src/shared/server_api_client.dart
  packages/devtools_extensions/lib/src/api/api.dart
  packages/devtools_extensions/lib/src/template/connected_app_manager.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/lib/devtools_shared.dart
  packages/devtools_shared/lib/service.dart
  packages/devtools_shared/lib/src/service/service.dart
  packages/devtools_shared/lib/src/sse/_fake_sse.dart
  packages/devtools_shared/lib/src/sse/sse_shim.dart
  packages/devtools_shared/pubspec.yaml
  tool/build_release.sh
  tool/pub_upgrade.sh
Labels: release-notes-not-required, run-dcm-workflow

#6169 Link boilerplate for equality in coding agreements.
  packages/README.md
Labels: autosubmit

#6139 Use `package:extension_discovery` to detect DevTools extensions
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6202 Fix goldens for 3.14.0-4.0.pre broken goldens
  packages/devtools_app/test/performance/frame_analysis/goldens/performance/frame_time_visualizer.png
  packages/devtools_app/test/performance/frame_analysis/goldens/performance/frame_time_visualizer_with_shader_compilation.png
  packages/devtools_app/test/performance/raster_stats/goldens/raster_stats_changed_selection.png
  packages/devtools_app/test/performance/raster_stats/goldens/raster_stats_with_data.png
  packages/devtools_app/test/test_infra/goldens/codeview_scrollbars.png
  packages/devtools_app/test/test_infra/goldens/cpu_profiler/bottom_up_guidelines.png
  packages/devtools_app/test/test_infra/goldens/cpu_profiler/bottom_up_no_guidelines.png
  packages/devtools_app/test/test_infra/goldens/cpu_profiler/call_tree_guidelines.png
  packages/devtools_app/test/test_infra/goldens/cpu_profiler/call_tree_no_guidelines.png
  packages/devtools_app/test/test_infra/goldens/cpu_profiler/method_table_no_selection.png
  packages/devtools_app/test/test_infra/goldens/cpu_profiler/method_table_with_selection.png
  packages/devtools_app/test/test_infra/goldens/cpu_profiler/method_table_with_selection_2.png
  packages/devtools_app/test/test_infra/goldens/extensions/settings_state_modified.png
  packages/devtools_app/test/test_infra/goldens/extensions/settings_state_none.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/collasped_list.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/collasped_map.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/collasped_object.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/edit.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/edit_esc.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/expanded_list.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/expanded_map.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/expanded_object.png
  packages/devtools_app/test/test_infra/goldens/instance_viewer/show_internal_properties.png
  packages/devtools_app/test/test_infra/goldens/integration_animated_physical_model_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_errors_1_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_errors_2_error_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_richtext_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_scaffold_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center_details_tree.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty1.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty2.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_custom.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_except.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_only.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_showAll.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_selected_class.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_custom_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_custom_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_except_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_except_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_only_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_only_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_scene_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_scene_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_showAll_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_showAll_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_three_snapshots1.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_three_snapshots2.png
  packages/devtools_app/test/test_infra/goldens/provider_screen/list_error_banner.png
  packages/devtools_app/test/test_infra/goldens/settings_dialog_default.png
  packages/devtools_app/test/test_infra/goldens/settings_dialog_modified.png
  packages/devtools_app/test/test_infra/goldens/timeline_flame_chart_with_selected_frame.png
  packages/devtools_app/test/test_infra/goldens/treemap_apk.png
  packages/devtools_app/test/test_infra/goldens/treemap_sizes.png
  packages/devtools_app/test/test_infra/goldens/treemap_v8.png
Labels: autosubmit

#6204 Fetch dependencies for all DevTools packages in `tool/bots.sh`
  tool/bots.sh
Labels: run-dcm-workflow

#5538 Each log entry should be on its own line
  packages/devtools_app/lib/src/shared/log_storage.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/test/primitives/utils_test.dart
  packages/devtools_app/test/shared/log_storage_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6185 Ignore DCM error for type assertion
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
Labels: release-notes-not-required, run-dcm-workflow

#6207 Fixing source_location issue on new candidate
  packages/devtools_app/lib/src/shared/diagnostics/primitives/source_location.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6203 Adding helper for quickly fixing goldens
  .github/workflows/build.yaml
  tool/fix_goldens.sh
Labels: autosubmit

#6216 Extensions cleanup and TODOs
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/test/provider/provider_screen_integration_test.dart
  packages/devtools_app/test/provider/provider_screen_test.dart
  packages/devtools_extensions/lib/src/template/connected_app_manager.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_test/lib/src/utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#6104 Add some simple side bar functionality with a mock editor environment
  packages/.vscode/launch.json
  packages/devtools_app/lib/src/shared/config_specific/post_message/post_message.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/post_message_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/post_message_web.dart
  packages/devtools_app/lib/src/standalone_ui/api/dart_tooling_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/dart_tooling_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/standalone_screen.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code_mock_editor.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
Labels: release-notes-not-required, run-dcm-workflow

#6217 Polish the DevTools extension template and embedded view
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/extension_screen_controls.dart
  packages/devtools_app/lib/src/framework/release_notes/release_notes.dart
  packages/devtools_extensions/example/foo_devtools_extension/lib/main.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
Labels: release-notes-not-required, run-dcm-workflow

#6228 Stop passing a nullable value to Future<nn-type>.value or Completer<nn-type>.completer
  packages/devtools_app/lib/src/shared/scripts/script_manager.dart
  packages/devtools_test/lib/src/mocks/fake_service_manager.dart
  packages/devtools_test/lib/src/mocks/fake_vm_service_wrapper.dart
Labels: release-notes-not-required, run-dcm-workflow

#6230 Add an `example` directory to `devtools_app_shared`
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
  packages/devtools_app_shared/README.md
  packages/devtools_app_shared/example/service_example.dart
  packages/devtools_app_shared/example/ui/common_example.dart
  packages/devtools_app_shared/example/ui/dialog_example.dart
  packages/devtools_app_shared/example/ui/split_example.dart
  packages/devtools_app_shared/example/utils/auto_dispose_example.dart
  packages/devtools_app_shared/example/utils/globals_example.dart
  packages/devtools_app_shared/example/utils/list_example.dart
  packages/devtools_app_shared/example/utils/utils_example.dart
  packages/devtools_app_shared/lib/src/ui/dialogs.dart
Labels: release-notes-not-required, run-dcm-workflow

#6238 Include new packages into upgrade process.
  tool/generate_code.sh
  tool/refresh.sh
  tool/upgrade.sh
Labels: autosubmit

#6245 Move `OutlineDecoration` to devtools_app_shared
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/screens/debugger/common.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/class_details/class_details.dart
  packages/devtools_app/lib/src/screens/network/network_request_inspector.dart
  packages/devtools_app/lib/src/screens/profiler/panes/method_table/method_table.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_object_pool_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_unknown_object_display.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/ui/tab.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
Labels: release-notes-not-required, run-dcm-workflow

#6246 Move FormattedJson to devtools_app_shared
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/legacy/event_details.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app_shared/example/ui/split_example.dart
  packages/devtools_app_shared/example/utils/auto_dispose_example.dart
  packages/devtools_app_shared/lib/src/service/eval_on_dart_library.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
Labels: release-notes-not-required, run-dcm-workflow

#6252 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: autosubmit

#6250 Add `DevToolsExtensionHostInterface` and clean up some service management for extensions
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app_shared/lib/src/service/connected_app.dart
  packages/devtools_extensions/lib/src/api/api.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_shared/lib/src/service/service.dart
Labels: release-notes-not-required, run-dcm-workflow

#6253 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: autosubmit

#6251 Add a simulated DevTools environment for developing extensions
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
  packages/devtools_app_shared/lib/src/utils/globals.dart
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/api/api.dart
  packages/devtools_extensions/lib/src/api/model.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_connect_ui.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_controller.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6255 Add initial README.md for `package:devtools_extensions`
  packages/devtools_extensions/README.md
  packages/devtools_extensions/_readme_images/example_devtools_extension.png
  packages/devtools_extensions/_readme_images/simulated_devtools_environment.png
Labels: autosubmit

#6259 Ship a `build_and_copy` command with the `devtools_extensions` package
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/bin/_build_and_copy.dart
  packages/devtools_extensions/bin/devtools_extensions.dart
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6262 Clean up `theme.dart` in `devtools_app_shared`
  packages/devtools_app/lib/src/framework/initializer.dart
  packages/devtools_app/lib/src/screens/debugger/codeview.dart
  packages/devtools_app/lib/src/screens/debugger/program_explorer.dart
  packages/devtools_app/lib/src/screens/debugger/syntax_highlighter.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/legend.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/legacy/timeline_flame_chart.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_code_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_instance_display.dart
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
  packages/devtools_app/lib/src/shared/charts/chart.dart
  packages/devtools_app/lib/src/shared/charts/flame_chart.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/console/widgets/display_provider.dart
  packages/devtools_app/lib/src/shared/table/table.dart
  packages/devtools_app/lib/src/shared/ui/colors.dart
  packages/devtools_app/lib/src/shared/ui/hover.dart
  packages/devtools_app/lib/src/shared/ui/icons.dart
  packages/devtools_app/lib/src/shared/ui/search.dart
  packages/devtools_app/test/shared/syntax_highlighter_test.dart
  packages/devtools_app/test/test_infra/goldens/timeline_flame_chart_with_selected_frame.png
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
Labels: release-notes-not-required, run-dcm-workflow

#6269 Prepare `devtools_extensions`, `devtools_app_shared` releases and fix bug
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_connect_ui.dart
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6270 Temporary disable failing integration test.
  packages/devtools_app/integration_test/test/live_connection/eval_and_browse_test_disabled.dart
Labels: release-notes-not-required, run-dcm-workflow

#6274 Hide the DevTools provider screen when the provider DevTools extension is available
  packages/devtools_app/lib/src/app.dart
Labels: release-notes-not-required, run-dcm-workflow

#6275 Add hot reload and hot restart buttons to the simulated devtools environment
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_controller.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6276 Add `showNotification` and `showBannerMessage` to extension API
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/shared/banner_messages.dart
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/example/foo_devtools_extension/lib/main.dart
  packages/devtools_extensions/lib/src/api/api.dart
  packages/devtools_extensions/lib/src/api/model.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/test/api_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6254 Limit Network text view to 2^16 characters to prevent it from crashing
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: run-dcm-workflow

#6283 Releasing from 2.27.0-dev.17 to 2.27.0
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6285 Update README.md.
  packages/README.md
Labels: autosubmit

#6260 Add ability to copy filtered logs in Logging page
  packages/devtools_app/lib/src/screens/logging/logging_screen.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/images/logger_copy.png
  packages/devtools_app/test/logging/logging_screen_test.dart
Labels: autosubmit, run-dcm-workflow

#6290 disable flaky flutter web integration test
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
Labels: release-notes-not-required, run-dcm-workflow

#6288 Fixes for google3 roll
  packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/lib/src/shared/utils.dart
  packages/devtools_app_shared/README.md
  packages/devtools_app_shared/lib/src/service/isolate_manager.dart
  packages/devtools_app_shared/lib/src/service/service_extension_manager.dart
  packages/devtools_app_shared/lib/src/service/service_manager.dart
  packages/devtools_app_shared/lib/src/ui/ui_utils.dart
  packages/devtools_app_shared/lib/src/utils/globals.dart
  packages/devtools_extensions/lib/src/api/api.dart
Labels: release-notes-not-required, run-dcm-workflow

#6291 Fixing flakey debug panel test
  packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
Labels: release-notes-not-required, run-dcm-workflow

#6281 Clean up Logging page top bar
  packages/devtools_app/lib/src/screens/logging/logging_screen.dart
  packages/devtools_app/lib/src/screens/logging/shared/constants.dart
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/logging/logging_screen_test.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
Labels: autosubmit, run-dcm-workflow

#6295 Fix App.started timeout in integration tests
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/test/test_infra/flutter_test_driver.dart
Labels: release-notes-not-required, run-dcm-workflow

#6298 Add exception handling to build_and_copy command
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/bin/_build_and_copy.dart
Labels: release-notes-not-required, run-dcm-workflow

#6297 Decrease memory footprint of heap snapshot.
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/model.dart
  packages/devtools_app/lib/src/shared/memory/adapted_heap_object.dart
  packages/devtools_app/lib/src/shared/memory/class_name.dart
  packages/devtools_app/macos/Runner.xcodeproj/project.pbxproj
  packages/devtools_app/test/memory/diff/controller/heap_diff_test.dart
  packages/devtools_app/test/memory/memory_footprint_test.dart
  packages/devtools_app/test/memory/primitives/class_name_test.dart
  packages/devtools_app/test/memory/shared/heap/class_filter_test.dart
  packages/devtools_app/test/memory/shared/heap/heap_analyzer_test.dart
  packages/devtools_app/test/memory/shared/heap/heap_test.dart
  packages/devtools_app/test/memory/shared/heap/model_test.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow
