Repository flutter/devtools, pull requests merged in 2023-11, with the labels that each got.

#6632 Improve flutter backwards compatibility for `devtools_app_shared`
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/service_extensions.dart
Labels: release-notes-not-required, run-dcm-workflow

#6629 Move sharedStdIn.terminate to only run from top level
  tool/bin/devtools_tool.dart
  tool/lib/devtools_command_runner.dart
Labels: release-notes-not-required, run-dcm-workflow

#6634 Convert the build_release.sh script to a dart script
  packages/devtools_app/test_benchmarks/web_bundle_size_test.dart
  tool/build_e2e.dart
  tool/build_release.sh
  tool/lib/commands/build_release.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/model.dart
  tool/lib/utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#6636 Convert the `update_perfetto.sh` script to a dart script
  packages/devtools_app/pubspec.yaml
  tool/build_e2e.dart
  tool/build_release.sh
  tool/lib/commands/build_release.dart
  tool/lib/commands/update_perfetto.dart
  tool/lib/commands/update_version.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/utils.dart
  tool/update_perfetto.sh
  tool/update_perfetto_assets.dart
Labels: release-notes-not-required, run-dcm-workflow

#6638 Replace `build_e2e.dart` with `devtools_tool serve` command
  tool/RELEASE_INSTRUCTIONS.md
  tool/build_e2e.dart
  tool/lib/commands/release_helper.dart
  tool/lib/commands/serve.dart
  tool/lib/devtools_command_runner.dart
Labels: release-notes-not-required, run-dcm-workflow

#6643 Fix build-release issue on Windows
  tool/lib/commands/build_release.dart
  tool/lib/commands/serve.dart
Labels: release-notes-not-required

#6639 Address some devtools extensions feedback related to Windows
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/bin/_build_and_copy.dart
  packages/devtools_extensions/bin/devtools_extensions.dart
  packages/devtools_extensions/example/foo/.vscode/launch.json
  packages/devtools_extensions/extension_config_spec.md
Labels: release-notes-not-required, run-dcm-workflow

#6508 Bump to vm_service 13.0.0 and reduce `VmServiceWrapper`.
  packages/devtools_app/integration_test/test/live_connection/service_connection_test.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/network/network_controller.dart
  packages/devtools_app/lib/src/screens/network/network_service.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
  packages/devtools_app/lib/src/shared/console/console_service.dart
  packages/devtools_app/lib/src/shared/error_badge_manager.dart
  packages/devtools_app/lib/src/shared/framework_controller.dart
  packages/devtools_app/lib/src/shared/http/http_request_data.dart
  packages/devtools_app/lib/src/shared/http/http_service.dart
  packages/devtools_app/lib/src/shared/server_api_client.dart
  packages/devtools_app/lib/src/shared/utils.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/provider/provider_screen_integration_test.dart
  packages/devtools_app/test/provider/provider_screen_test.dart
  packages/devtools_app/test/test_infra/flutter_test_driver.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/README.md
  packages/devtools_app_shared/example/service_example.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/service/service.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
  packages/devtools_test/lib/src/mocks/fake_vm_service_wrapper.dart
  packages/devtools_test/lib/src/mocks/generated_mocks_factories.dart
  packages/devtools_test/pubspec.yaml
  tool/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6647 Add service extension example to devtools_extensions
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/bin/devtools_extensions.dart
  packages/devtools_extensions/example/app_that_uses_foo/lib/main.dart
  packages/devtools_extensions/example/foo/packages/foo/lib/foo.dart
  packages/devtools_extensions/example/foo/packages/foo/lib/src/foo_base.dart
  packages/devtools_extensions/example/foo/packages/foo/lib/src/foo_controller.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/.vscode/launch.json
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/devtools_event_example.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/devtools_extension_api_example.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/foo_devtools_extension.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/service_extension_example.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/pubspec.yaml
  packages/devtools_extensions/lib/src/api/model.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
Labels: release-notes-not-required

#6651 Fix DevTools extension analytics
  packages/devtools_app/lib/src/extensions/embedded/view.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/extension_screen_controls.dart
  packages/devtools_app/lib/src/extensions/extension_settings.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_extension_constants.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/extensions/extension_analytics_test.dart
  packages/devtools_app/test/test_infra/test_data/extensions.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/extensions/extension_model_test.dart
  packages/devtools_test/pubspec.yaml
  tool/pubspec.yaml
Labels: release-notes-not-required

#6656 Fix incorrect description of the `devtools_tool update-flutter-sdk` command
  tool/lib/commands/update_flutter_sdk.dart
Labels: release-notes-not-required

#6660 Clarify error messaging if 'isPubliclyHosted' key is missing
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/test/extensions/extension_model_test.dart
Labels: release-notes-not-required

#6659 Fix a couple bugs with the `serve` and `build_release` commands
  tool/lib/commands/build_release.dart
  tool/lib/commands/serve.dart
Labels: release-notes-not-required

#6646 Exit with an error if trying to run update-perfetto on Windows
  tool/lib/commands/update_perfetto.dart
Labels: release-notes-not-required

#6665 Add expression evaluation example to devtools_extensions
  packages/devtools_app_shared/lib/src/ui/common.dart
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/_readme_images/simulated_devtools_environment.png
  packages/devtools_extensions/example/app_that_uses_foo/devtools_options.yaml
  packages/devtools_extensions/example/app_that_uses_foo/lib/main.dart
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/flutter_service_worker.js
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/index.html
  packages/devtools_extensions/example/foo/packages/foo/extension/devtools/build/main.dart.js
  packages/devtools_extensions/example/foo/packages/foo/lib/foo.dart
  packages/devtools_extensions/example/foo/packages/foo/lib/src/foo_base.dart
  packages/devtools_extensions/example/foo/packages/foo/lib/src/foo_controller.dart
  packages/devtools_extensions/example/foo/packages/foo/lib/src/foo_widget.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/devtools_event_example.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/devtools_extension_api_example.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/expression_evaluation_example.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/foo_devtools_extension.dart
  packages/devtools_extensions/example/foo/packages/foo_devtools_extension/lib/src/service_extension_example.dart
  packages/devtools_extensions/integration_test/test/simulated_environment_test.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
Labels: release-notes-not-required

#6668 Fix an issue locating the Flutter SDK on Windows when not invoked via 'dart' inside a Flutter SDK
  tool/lib/model.dart
Labels: autosubmit, release-notes-not-required

#6669 Use located Flutter instead of PATH flutter for Command.flutter() + support FLUTTER_ROOT override
  tool/lib/commands/analyze.dart
  tool/lib/commands/pub_get.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/model.dart
  tool/lib/utils.dart
Labels: release-notes-not-required

#6666 Validate extension names and warn in devtools_app for server-side extension errors
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_web.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_web.dart
  packages/devtools_app/lib/src/shared/primitives/storage.dart
  packages/devtools_app/test/extensions/extension_analytics_test.dart
  packages/devtools_app/test/extensions/extension_screen_test.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
  packages/devtools_app/test/test_infra/test_data/extensions.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/test/extensions/extension_model_test.dart
Labels: release-notes-not-required

#6678 Prepare for roll to G3.
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#6687 Add a test target to the app_that_uses_foo/ example
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/example/app_that_uses_foo/test/app_that_uses_foo_test.dart
Labels: release-notes-not-required

#6676 Fix analysis warnings on master
  .github/workflows/build.yaml
  tool/RELEASE_INSTRUCTIONS.md
  tool/bots.sh
Labels: release-notes-not-required

#6673 Bump min sdk versions in DevTools packages.
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/service_extensions.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#6670 Allow --machine/--allow-embedding to be passed to devtools_tool serve
  tool/lib/commands/serve.dart
Labels: release-notes-not-required

#6691 Revert "Prepare for roll to G3."
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#6694 Fix analysis warnings for new flutter
  .github/workflows/build.yaml
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_test/lib/src/mocks/fake_vm_service_wrapper.dart
  tool/bots.sh
Labels: release-notes-not-required

#6695 Add `build-mode` and `pub-get` argument to the `serve` and `build` CLI tools
  CONTRIBUTING.md
  tool/RELEASE_INSTRUCTIONS.md
  tool/lib/commands/build.dart
  tool/lib/commands/build_release.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/shared.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/commands/update_perfetto.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/utils.dart
Labels: release-notes-not-required

#6544 Update Deep link validation UI
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/fake_data.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/lib/src/shared/table/table.dart
  packages/devtools_app/lib/src/shared/ui/colors.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
Labels: release-notes-not-required

#6702 Fix bug in `addBuildModeOption`
  tool/lib/commands/shared.dart
Labels: release-notes-not-required

#6705 Some readme cleanups.
  packages/devtools_app/integration_test/README.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/bin/_build_and_copy.dart
Labels: release-notes-not-required

#6685 Fix release helper git command
  tool/lib/commands/release_helper.dart
  tool/lib/commands/update_dart_sdk_deps.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/commands/update_perfetto.dart
  tool/lib/utils.dart
Labels: autosubmit, release-notes-not-required

#6707 Fix some errors in contributing instructions
  CONTRIBUTING.md
  tool/lib/commands/serve.dart
Labels: release-notes-not-required

#6711 Set deepLinkValidation feature flag to false until the feature is ready
  packages/devtools_app/lib/src/shared/feature_flags.dart
Labels: release-notes-not-required

#6704 Update deep link validation tool UI
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#6712 Migrate DevTools server to use `package:http`
  packages/devtools_app/lib/src/shared/config_specific/server/_server_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_web.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required

#6713 Refactor server APIs by logical groups
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/framework/release_notes/release_notes.dart
  packages/devtools_app/lib/src/framework/settings_dialog.dart
  packages/devtools_app/lib/src/screens/app_size/app_size_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/select_project_view.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_controller_web.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_web.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/server/_server_web.dart
  packages/devtools_app/lib/src/shared/config_specific/server/server.dart
  packages/devtools_app/lib/src/shared/server/_analytics_api.dart
  packages/devtools_app/lib/src/shared/server/_app_size_api.dart
  packages/devtools_app/lib/src/shared/server/_deep_links_api.dart
  packages/devtools_app/lib/src/shared/server/_extensions_api.dart
  packages/devtools_app/lib/src/shared/server/_release_notes_api.dart
  packages/devtools_app/lib/src/shared/server/_survey_api.dart
  packages/devtools_app/lib/src/shared/server/server.dart
  packages/devtools_app/lib/src/shared/server/server_api_client.dart
  packages/devtools_app/lib/src/shared/survey.dart
  packages/devtools_app/test/shared/server_api_client_test.dart
Labels: release-notes-not-required

#6626 Work towards migrating `devtools_app` to `package:web`
  packages/devtools_app/integration_test/test/live_connection/devtools_extensions_test.dart
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_web.dart
  packages/devtools_app/lib/src/shared/analytics/analytics_common.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_web.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/drag_and_drop.dart
  packages/devtools_app/lib/src/shared/config_specific/file/_file_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/file/file.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_web.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/framework_initialize.dart
  packages/devtools_app/lib/src/shared/config_specific/host_platform/_host_platform_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/host_platform/_host_platform_web.dart
  packages/devtools_app/lib/src/shared/config_specific/host_platform/host_platform.dart
  packages/devtools_app/lib/src/shared/config_specific/host_platform/host_platform_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_web.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/import_export.dart
  packages/devtools_app/lib/src/shared/config_specific/launch_url/_launch_url_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/launch_url/_launch_url_web.dart
  packages/devtools_app/lib/src/shared/config_specific/launch_url/launch_url.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_allowed_error_default.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_allowed_error_web.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_logger_io.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_logger_web.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/allowed_error.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/logger.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/logger_html.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/_notifications_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/_notifications_web.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/notifications.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/notifications_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/notifications_web.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/_post_message_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/_post_message_web.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/post_message.dart
  packages/devtools_app/lib/src/shared/console/eval/inspector_tree.dart
  packages/devtools_app/test/shared/visible_screens_test.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/connected_app.dart
  packages/devtools_app_shared/lib/src/ui/theme/_ide_theme_web.dart
  packages/devtools_app_shared/lib/src/utils/url/_url_web.dart
  packages/devtools_app_shared/lib/src/utils/web_utils.dart
  packages/devtools_app_shared/lib/web_utils.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_controller.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/lib/src/utils.dart
  packages/devtools_extensions/lib/utils.dart
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/lib/src/sse/_fake_sse.dart
Labels: release-notes-not-required

#6715 Accept project root paths in debug sessions for sidebar
  packages/devtools_app/lib/src/standalone_ui/api/impl/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/vs_code_api.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
Labels: autosubmit, release-notes-not-required

#6724 Don't render not-found page during initial setup
  packages/devtools_app/lib/src/app.dart
Labels: release-notes-not-required

#6722 [deep link]Add empty filler rows in data table
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/shared/table/table.dart
Labels: release-notes-not-required

#6731 [deep link] add deep_links_services
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_services.dart
Labels: release-notes-not-required

#6737 Update dart doc for some `devtools_extensions` members
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
Labels: release-notes-not-required

#6730 Set version constraints for pkg:web >=0.3.0 <0.5.0
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_web.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required

#6739 Revert "Set version constraints for pkg:web >=0.3.0 <0.5.0 (#6730)"
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_web.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required

#6741 Reland "Set version constraints for pkg:web >=0.3.0 <0.5.0 (#6730)"
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_web.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required

#6740 Add better error messaging when accessing devtools extension globals too soon
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/test/web/devtools_extension_test.dart
  tool/bots.sh
Labels: release-notes-not-required

#6744 Add cast to JSObject for instanceOfString call
  packages/devtools_app_shared/lib/src/utils/web_utils.dart
Labels: release-notes-not-required

#6738 Move `ResolvedUriManager` from `devtools_app` to `devtools_app_shared`
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/screens/debugger/codeview.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/test/debugger/debugger_codeview_test.dart
  packages/devtools_app/test/shared/resolved_uri_manager_test.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/service.dart
  packages/devtools_app_shared/lib/src/service/resolved_uri_manager.dart
  packages/devtools_app_shared/lib/src/service/service_manager.dart
  packages/devtools_test/lib/src/mocks/fake_service_manager.dart
Labels: release-notes-not-required

#6736 Add support for "Open DevTools in Browser" in Sidebar menu
  packages/devtools_app/lib/src/shared/analytics/constants/_vs_code_sidebar_constants.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
Labels: autosubmit, flutter sidebar

#6754 Enhance DevTools survey logic
  packages/devtools_app/lib/src/shared/analytics/_analytics_stub.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/survey.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/shared/survey_test.dart
  packages/devtools_shared/lib/src/utils/semantic_version.dart
  packages/devtools_shared/test/semantic_version_test.dart
Labels: release-notes-not-required

#6762 [devtools_app] update dependency on pkg:file_selector
  packages/devtools_app/pubspec.yaml
Labels: autosubmit, release-notes-not-required

#6746 [deep link] Add more unit tests
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
Labels: release-notes-not-required

#6769 Do not show source links in CPU profile when offline
  packages/devtools_app/lib/src/shared/profiler_utils.dart
  packages/devtools_app/test/cpu_profiler/method_table/method_table_test.dart
Labels: release-notes-not-required

#6770 Fix renderflex overflow errors on Performance and CPU Profiler screens
  packages/devtools_app/lib/src/screens/performance/panes/controls/performance_controls.dart
  packages/devtools_app/lib/src/screens/profiler/panes/controls/profiler_screen_controls.dart
Labels: release-notes-not-required

#6750 Pin package:web 0.4.0
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
  packages/devtools_app/lib/src/shared/config_specific/analysis_options.yaml
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_web.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/_notifications_web.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/_post_message_web.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required

#6780 Always call launchUrlVSCode, error or not
  packages/devtools_app/lib/src/shared/config_specific/launch_url/launch_url.dart
Labels: release-notes-not-required

#6782 Increase the pump duration for app connection in integration test
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required

#6783 Fix some minor Windows issues
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/extensions/extension_enablement_test.dart
  packages/devtools_shared/test/extensions/extension_manager_test.dart
Labels: autosubmit, release-notes-not-required

#6776 Always use tool/flutter-sdk for devtools_tool + remote FLUTTER_ROOT
  .github/workflows/build.yaml
  .github/workflows/flutter-prep.yaml
  tool/bin/devtools_tool
  tool/bin/devtools_tool.bat
  tool/ci/setup.sh
  tool/lib/commands/analyze.dart
  tool/lib/commands/build.dart
  tool/lib/commands/pub_get.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/shared.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/model.dart
  tool/lib/utils.dart
Labels: autosubmit, release-notes-not-required

#6814 [devtools_app] Bump dependencies
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test_driver/integration_test.dart
Labels: release-notes-not-required

#6815 Drop unneeded library directives
  packages/analysis_options.yaml
  packages/devtools_app/lib/src/screens/inspector/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_tree_controller.dart
  packages/devtools_app/lib/src/screens/provider/instance_viewer/eval.dart
  packages/devtools_app/lib/src/service/service_extensions.dart
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_stub.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/gtags.dart
  packages/devtools_app/lib/src/shared/console/eval/inspector_tree.dart
  packages/devtools_app/lib/src/shared/http/_http_cookies.dart
  packages/devtools_app/lib/src/shared/http/_http_date.dart
  packages/devtools_app/lib/src/shared/http/_http_exception.dart
  packages/devtools_app/lib/src/shared/http/http.dart
  packages/devtools_app/lib/src/shared/ui/icons.dart
  packages/devtools_app/test/legacy_integration_tests/debugger.dart
  packages/devtools_app/test/test_infra/matchers/matchers.dart
  packages/devtools_extensions/lib/api.dart
  packages/devtools_extensions/lib/devtools_extensions.dart
  packages/devtools_extensions/lib/utils.dart
  third_party/packages/widget_icons/lib/widget_icons.dart
Labels: autosubmit, release-notes-not-required

#6820 Revert "Always use tool/flutter-sdk for devtools_tool + remote FLUTTE…
  .github/workflows/build.yaml
  .github/workflows/flutter-prep.yaml
  tool/bin/devtools_tool
  tool/bin/devtools_tool.bat
  tool/ci/setup.sh
  tool/lib/commands/analyze.dart
  tool/lib/commands/build.dart
  tool/lib/commands/pub_get.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/shared.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/model.dart
  tool/lib/utils.dart
Labels: release-notes-not-required

#6824 Re-land SDK detection changes with support for running from PATH
  .github/workflows/build.yaml
  .github/workflows/flutter-prep.yaml
  tool/bin/devtools_tool
  tool/bin/devtools_tool.bat
  tool/ci/setup.sh
  tool/flutter_customer_tests/setup.sh
  tool/lib/commands/analyze.dart
  tool/lib/commands/build.dart
  tool/lib/commands/pub_get.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/shared.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/model.dart
  tool/lib/utils.dart
Labels: release-notes-not-required

#6844 Add missing 'screen' analytics event for the VS code sidebar
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
Labels: release-notes-not-required

#6854 Fix Icon issue blocking g3 roll
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#6827 Add button for toggling background colour during raster preview
  packages/devtools_app/lib/src/screens/performance/panes/raster_stats/raster_stats.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: autosubmit

#6857 Fix project directory inference for inspector panel
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/inspector/inspector_service_test.dart
Labels: autosubmit
