Repository flutter/devtools, pull requests merged in 2023-12, with the labels that each got.

#6885 Fix TODOs and lints in memory app test fixture
  packages/devtools_app/test/test_infra/fixtures/memory_app/lib/main.dart
Labels: release-notes-not-required

#6732 [deep link] Update loading UI
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/select_project_view.dart
Labels: release-notes-not-required

#6900 Add a helper script for converting json to a dart file
  tool/json_to_map.dart
Labels: release-notes-not-required

#6898 Use the proper mounted guard in a State class
  packages/devtools_app/lib/src/screens/deep_link_validation/select_project_view.dart
Labels: release-notes-not-required

#6907 Remove unused test fixtures
  packages/devtools_app/test/test_infra/fixtures/provider_app/.gitignore
  packages/devtools_app/test/test_infra/fixtures/provider_app/.metadata
  packages/devtools_app/test/test_infra/fixtures/provider_app/lib/main.dart
  packages/devtools_app/test/test_infra/fixtures/provider_app/lib/mixin.dart
  packages/devtools_app/test/test_infra/fixtures/provider_app/lib/tester.dart
  packages/devtools_app/test/test_infra/fixtures/provider_app/pubspec.yaml
  packages/devtools_app/test/test_infra/fixtures/riverpod_app/.gitignore
  packages/devtools_app/test/test_infra/fixtures/riverpod_app/.metadata
  packages/devtools_app/test/test_infra/fixtures/riverpod_app/README.md
  packages/devtools_app/test/test_infra/fixtures/riverpod_app/lib/main.dart
  packages/devtools_app/test/test_infra/fixtures/riverpod_app/lib/tester.dart
  packages/devtools_app/test/test_infra/fixtures/riverpod_app/pubspec.yaml
Labels: release-notes-not-required

#6881 Add a basic performance benchmark test for DevTools.
  .github/workflows/build.yaml
  packages/devtools_app/benchmark/README.md
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
  packages/devtools_app/benchmark/run_benchmarks.dart
  packages/devtools_app/benchmark/test_infra/client.dart
  packages/devtools_app/benchmark/test_infra/common.dart
  packages/devtools_app/benchmark/test_infra/devtools_automator.dart
  packages/devtools_app/benchmark/test_infra/devtools_recorder.dart
  packages/devtools_app/benchmark/test_infra/project_root_directory.dart
  packages/devtools_app/benchmark/web_bundle_size_test.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test_benchmarks/README.md
  tool/ci/benchmark_performance.sh
  tool/ci/benchmark_size.sh
Labels: release-notes-not-required

#6912 Bump to web_benchmarks 1.0.0
  packages/devtools_app/benchmark/README.md
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
  packages/devtools_app/benchmark/run_benchmarks.dart
  packages/devtools_app/benchmark/scripts/run_benchmarks.dart
  packages/devtools_app/pubspec.yaml
  tool/ci/benchmark_performance.sh
Labels: release-notes-not-required

#6917 Add scrollbar to log details
  packages/devtools_app/lib/src/screens/logging/_log_details.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: autosubmit

#6918 Add the ability to compare benchmark runs
  packages/devtools_app/benchmark/README.md
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
  packages/devtools_app/benchmark/scripts/compare_benchmarks.dart
  packages/devtools_app/benchmark/scripts/run_benchmarks.dart
  packages/devtools_app/benchmark/scripts/utils.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required

#6920 Add the ability to average benchmark runs
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
  packages/devtools_app/benchmark/scripts/run_benchmarks.dart
  packages/devtools_app/benchmark/scripts/utils.dart
Labels: release-notes-not-required

#6916 Use Object as the parameter type in 'operator ==' overrides
  packages/devtools_app/lib/src/screens/debugger/debugger_model.dart
  packages/devtools_app/lib/src/screens/network/network_model.dart
  packages/devtools_app/lib/src/shared/charts/flame_chart.dart
  packages/devtools_app/lib/src/shared/diagnostics/primitives/source_location.dart
  packages/devtools_app/lib/src/shared/http/http_request_data.dart
  packages/devtools_app/lib/src/shared/primitives/trace_event.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/test/primitives/utils_test.dart
  packages/devtools_app/test/test_infra/goldens/syntax_highlighting/keywords.dart.golden
  packages/devtools_app/test/test_infra/test_data/syntax_highlighting/keywords.dart
  packages/devtools_app_shared/lib/src/service/flutter_version.dart
  packages/devtools_app_shared/lib/src/service/service_manager.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
Labels: release-notes-not-required

#6933 Use type promotion in vm_developer_common_widgets
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_common_widgets.dart
Labels: release-notes-not-required

#6927 Add some ignores for nullable vlues into non-nullable Futures.
  packages/devtools_app/lib/src/shared/config_specific/logger/_allowed_error_default.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_allowed_error_web.dart
Labels: release-notes-not-required

#6938 Avoid raw types so as to avoid dynamic invocations
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/shared/diagnostics/variable_factory.dart
  packages/devtools_app/lib/src/shared/http/_http_date.dart
  packages/devtools_app/test/memory/diff/widgets/diff_pane_test.dart
Labels: release-notes-not-required

#6941 Rearrange null-safe code to avoid null-aware type issues
  packages/devtools_test/lib/src/mocks/fake_vm_service_wrapper.dart
Labels: release-notes-not-required

#6931 Reduce use of dynamic by avoiding Map.fromIterable, List.from, Map.from
  packages/devtools_app/lib/src/screens/inspector/inspector_data_models.dart
  packages/devtools_app/test/cpu_profiler/cpu_profile_model_test.dart
  packages/devtools_app/test/performance/performance_model_test.dart
Labels: release-notes-not-required

#6943 [deep link] Update api key
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_services.dart
Labels: release-notes-not-required

#6945 chart_test: memoryJson has HeapSamples
  packages/devtools_app/test/memory/chart/chart_test.dart
Labels: release-notes-not-required

#6947 Type the TableStates in table_test
  packages/devtools_app/test/shared/table_test.dart
Labels: release-notes-not-required

#6950 Add a flag to run benchmark tests with skwasm
  packages/devtools_app/benchmark/README.md
  packages/devtools_app/benchmark/scripts/run_benchmarks.dart
Labels: release-notes-not-required

#6922 Bump to web_benchmarks version 1.1.0
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
  packages/devtools_app/benchmark/scripts/compare_benchmarks.dart
  packages/devtools_app/benchmark/scripts/run_benchmarks.dart
  packages/devtools_app/benchmark/scripts/utils.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required

#6937 Use a switch over object patterns instead of runtime type
  packages/devtools_test/lib/src/mocks/fake_service_extension_manager.dart
Labels: release-notes-not-required

#6940 Add type arguments on class declaration clauses
  packages/devtools_app/lib/src/shared/table/table.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/utils/compare.dart
  packages/devtools_shared/lib/src/utils/semantic_version.dart
  packages/devtools_shared/pubspec.yaml
Labels: release-notes-not-required

#6934 Declare some local variables to avoid dynamic dispatch and null assertions
  packages/devtools_app/lib/src/service/vm_service_logger.dart
Labels: release-notes-not-required

#6961 [DevTools extensions] Only use `Uri.file` for windows platforms
  .github/workflows/flutter-prep.yaml
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/pubspec.yaml
Labels: release-notes-not-required

#6967 Fix the `update-sdk-deps` command to only add the DEPS file
  tool/lib/commands/update_dart_sdk_deps.dart
Labels: release-notes-not-required

#6968 [DevTools extensions] Use `Uri.parse` for windows platforms too
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
Labels: release-notes-not-required

#6908 Add a global --flutter-from-path argument that overrides SDK selection
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/model.dart
  tool/lib/utils.dart
Labels: autosubmit, release-notes-not-required

#6973 Rename ToCsvButton to DownloadButton to enable different types of download/save/export buttons.
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/profile_view.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
Labels: release-notes-not-required

#6976 Update DevTools survey metadata location
  packages/devtools_app/lib/src/shared/survey.dart
Labels: release-notes-not-required

#6984 Fix incoming postMessages for package:web
  packages/devtools_app/lib/src/shared/config_specific/post_message/_post_message_web.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: autosubmit

#6979 Convert FrameInfo and ImageSizesForFrame into extension types
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
Labels: release-notes-not-required

#6983 Remove unused parameter in `initVmService`
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/lib/src/framework/initializer.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/lib/src/shared/routing.dart
  packages/devtools_app/test/primitives/utils_test.dart
Labels: release-notes-not-required

#6985 Resume the latest flutter candidate logic
  .github/workflows/flutter-prep.yaml
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
  packages/devtools_app/lib/src/shared/console/widgets/evaluate.dart
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
Labels: release-notes-not-required

#6980 Add CpuProfileDataJson extension type for handling this data
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart
Labels: release-notes-not-required

#6978 Add extension type for old memory data JSON
  packages/devtools_shared/lib/src/memory/memory_json.dart
Labels: release-notes-not-required

#6977 Add extension type for profile report range JSON
  packages/devtools_app/lib/src/screens/vm_developer/vm_service_private_extensions.dart
Labels: release-notes-not-required

#6989 Read active survey data from extension type
  packages/devtools_shared/lib/src/server/usage.dart
Labels: release-notes-not-required

#6990 Add extension type to read performance data JSON
  packages/devtools_app/lib/src/screens/performance/performance_model.dart
Labels: release-notes-not-required

#6999 Skip flakey test for flutter customer tests
  packages/devtools_app/test/shared/eval_integration_test.dart
  packages/devtools_test/lib/src/helpers/utils.dart
  tool/flutter_customer_tests/README.md
  tool/flutter_customer_tests/test.sh
Labels: release-notes-not-required

#7001 Improve doc comment and remove dynamic variable in AppSizeController
  packages/devtools_app/lib/src/screens/app_size/app_size_controller.dart
Labels: release-notes-not-required

#7000 Specify type arguments on raw types
  packages/devtools_app/benchmark/test_infra/automators/devtools_automator.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/service/service_extensions.dart
  packages/devtools_app_shared/lib/src/service/eval_on_dart_library.dart
  packages/devtools_app_shared/lib/src/service/service_extensions.dart
  packages/devtools_app_shared/lib/src/service/service_utils.dart
  packages/devtools_app_shared/test/utils/auto_dispose_mixin_test.dart
  packages/devtools_app_shared/test/utils/list_test.dart
Labels: release-notes-not-required

#7009 Base connection to Dart Tooling Daemon
  packages/devtools_app/lib/initialization.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/service/dtd_manager.dart
  packages/devtools_app/lib/src/shared/globals.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: autosubmit
