Repository flutter/devtools, pull requests merged in 2023-10, with the labels that each got.

#6505 Prepare DevTools tests for running in the Flutter customer test registry
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/cpu_profiler/cpu_profile_model_test.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/example/app_that_uses_foo/pubspec.yaml
  packages/devtools_extensions/example/foo/packages/foo/pubspec.yaml
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_extensions/test/api_test.dart
  packages/devtools_test/lib/src/wrappers.dart
  packages/devtools_test/pubspec.yaml
  packages/pubspec.yaml
  tool/flutter_customer_tests/analyze.sh
  tool/flutter_customer_tests/test.sh
  tool/flutter_tests.sh
  tool/lib/model.dart
Labels: release-notes-not-required, run-dcm-workflow

#6514 Link to devtools-extension-authors discord channel in readme
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6522 Bump package:file
  packages/devtools_app/pubspec.yaml
Labels: autosubmit

#6526 Switch to conditional import that works with wasm
  packages/devtools_app/lib/src/extensions/embedded/controller.dart
  packages/devtools_app/lib/src/extensions/embedded/view.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/perfetto.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/perfetto_controller.dart
  packages/devtools_app/lib/src/shared/analytics/analytics.dart
  packages/devtools_app/lib/src/shared/analytics/analytics_controller.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/drag_and_drop.dart
  packages/devtools_app/lib/src/shared/config_specific/file/file.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/framework_initialize.dart
  packages/devtools_app/lib/src/shared/config_specific/host_platform/host_platform.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/import_export.dart
  packages/devtools_app/lib/src/shared/config_specific/launch_url/launch_url.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/allowed_error.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/logger.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/notifications.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/post_message.dart
  packages/devtools_app/lib/src/shared/config_specific/server/server.dart
  packages/devtools_app/test/test_infra/matchers/matchers.dart
  packages/devtools_app_shared/lib/src/ui/theme/ide_theme.dart
  packages/devtools_app_shared/lib/src/utils/url/url.dart
  packages/devtools_shared/lib/src/sse/sse_shim.dart
Labels: release-notes-not-required, run-dcm-workflow

#6534 CpuProfiler tree guidelines now always enabled
  packages/devtools_app/lib/src/screens/profiler/cpu_profiler.dart
  packages/devtools_app/lib/src/screens/profiler/panes/bottom_up.dart
  packages/devtools_app/lib/src/screens/profiler/panes/call_tree.dart
  packages/devtools_app/lib/src/screens/profiler/panes/controls/cpu_profiler_controls.dart
  packages/devtools_app/lib/src/shared/preferences.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/cpu_profiler/cpu_profiler_test.dart
  packages/devtools_app/test/shared/preferences_controller_test.dart
Labels: run-dcm-workflow

#6542 Disable broken integration test `eval_and_browse_test.dart`
  packages/devtools_app/integration_test/run_tests.dart
Labels: release-notes-not-required, run-dcm-workflow

#6525 Fix status bar text colour
  packages/devtools_app/lib/src/framework/status_line.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: run-dcm-workflow

#6489 Improve error running devtools_tool from a different folder
  tool/lib/commands/analyze.dart
  tool/lib/commands/list.dart
  tool/lib/commands/pub_get.dart
  tool/lib/commands/repo_check.dart
  tool/lib/commands/rollback.dart
  tool/lib/model.dart
  tool/lib/utils.dart
Labels: tool, release-notes-not-required, run-dcm-workflow

#6547 Fix bug where extension states were not getting cleared on app disconnect
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/service_extension_manager.dart
  packages/devtools_app_shared/lib/src/utils/auto_dispose.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_app_shared/test/utils/auto_dispose_mixin_test.dart
Labels: run-dcm-workflow

#6515 Add "Track platform channels" setting to the enhance tracing menu
  packages/devtools_app/lib/src/screens/performance/panes/controls/enhance_tracing/enhance_tracing_controller.dart
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
  packages/devtools_app/lib/src/service/service_extensions.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_performance_constants.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/images/track_platform_channels.png
  packages/devtools_app/test/performance/frame_analysis/frame_hints_test.dart
  packages/devtools_app/test/performance/performance_screen_test.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/service_extensions.dart
Labels: run-dcm-workflow

#6530 Add timeline event on snapshot.
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_protocol.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/chart_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_android_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_charts.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_events_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_vm_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/secondary_controls.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/model.dart
  packages/devtools_app/test/memory/memory_screen_test.dart
  packages/devtools_app/test/memory/memory_service_test.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6554 Link to DevTools YouTube video from footer
  packages/devtools_app/lib/src/framework/status_line.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/screen.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/images/watch_tutorial_link.png
Labels: run-dcm-workflow

#6556 Remove gaContext.
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/classes_table_diff.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/classes_table_single.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/instances.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/instances.dart
  packages/devtools_app/lib/src/screens/memory/shared/primitives/instance_context_menu.dart
Labels: release-notes-not-required, run-dcm-workflow

#6545 Fix for broken eval_and_browse
  packages/devtools_app/integration_test/run_tests.dart
  packages/devtools_app/integration_test/test/live_connection/eval_and_browse_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6567 Show Performance and CPU Profiler screens without app connection
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/framework/status_line.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/performance_controls.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/screens/profiler/panes/controls/profiler_screen_controls.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_cpu_profiler_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_performance_constants.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/import_export.dart
  packages/devtools_app/lib/src/shared/file_import.dart
  packages/devtools_app/lib/src/shared/screen.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/cpu_profiler/profiler_screen_test.dart
  packages/devtools_app/test/performance/controls/performance_controls_test.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/ui/common.dart
  packages/devtools_app_shared/pubspec.yaml
Labels: run-dcm-workflow

#6536 Wires up deeplink validation tool backend
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/fake_data.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/select_project_view.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/directory_picker.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
  packages/devtools_shared/lib/src/deeplink/app_link_settings.dart
  packages/devtools_shared/lib/src/deeplink/deeplink_manager.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_test/lib/src/utils.dart
  packages/devtools_test/lib/src/wrappers.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6568 Use `RoundedButtonGroup` for debugger buttons
  packages/devtools_app/lib/src/screens/debugger/controls.dart
  packages/devtools_app/test/debugger/debugger_screen_paused_test.dart
  packages/devtools_app/test/debugger/debugger_screen_test.dart
  packages/devtools_app/test/test_infra/goldens/codeview_scrollbars.png
  packages/devtools_app/test/test_infra/utils/debugger_utils.dart
Labels: release-notes-not-required, run-dcm-workflow

#6579 Migrate generate_code.sh to devtools_tool for Windows compatibility
  packages/devtools_test/lib/src/mocks/generated.dart
  tool/bots.sh
  tool/generate_code.sh
  tool/lib/commands/generate_code.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/utils.dart
  tool/refresh.sh
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6582 Include main package subdirectories in the `devtools_tool pub-get` command
  tool/lib/commands/pub_get.dart
Labels: release-notes-not-required, run-dcm-workflow

#6583 Replace upgrade.sh, refresh.sh, pull_and_refresh.sh scripts with `sync` and `generate-code --upgrade` commands
  CONTRIBUTING.md
  tool/lib/commands/fix_goldens.dart
  tool/lib/commands/generate_code.dart
  tool/lib/commands/sync.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/utils.dart
  tool/pull_and_refresh.sh
  tool/refresh.sh
  tool/upgrade.sh
Labels: release-notes-not-required, run-dcm-workflow

#6584 Adds basic instrument for deep links validation
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/select_project_view.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_deep_links_constants.dart
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6581 Use theme preference from IDE when embedded instead of preference
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app_shared/lib/src/ui/theme/_ide_theme_web.dart
  packages/devtools_app_shared/lib/src/ui/theme/ide_theme.dart
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
Labels: run-dcm-workflow

#6593 Skip flaky test
  packages/devtools_app/integration_test/run_tests.dart
Labels: release-notes-not-required, run-dcm-workflow

#6591 Remove integration with leak_tracker.
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_tabs.dart
  packages/devtools_app/lib/src/screens/memory/panes/leaks/controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/leaks/diagnostics/formatter.dart
  packages/devtools_app/lib/src/screens/memory/panes/leaks/diagnostics/leak_analyzer.dart
  packages/devtools_app/lib/src/screens/memory/panes/leaks/diagnostics/model.dart
  packages/devtools_app/lib/src/screens/memory/panes/leaks/leaks_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/leaks/primitives/README.md
  packages/devtools_app/lib/src/screens/memory/panes/leaks/primitives/analysis_status.dart
  packages/devtools_app/lib/src/screens/memory/panes/leaks/primitives/simple_items.dart
  packages/devtools_app/lib/src/screens/memory/panes/leaks/widgets/simple_widgets.dart
  packages/devtools_app/pubspec.yaml
Labels: autosubmit, release-notes-not-required, run-dcm-workflow

#6588 Fix some "devtools_tool sync" issues on Windows
  tool/lib/commands/analyze.dart
  tool/lib/commands/generate_code.dart
  tool/lib/commands/pub_get.dart
  tool/lib/commands/release_helper.dart
  tool/lib/commands/sync.dart
  tool/lib/commands/update_dart_sdk_deps.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/model.dart
  tool/lib/utils.dart
  tool/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6605 Bump package:intl version to fix build
  case_study/memory_leaks/memory_leak_app/pubspec.yaml
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/app_size/app_size_screen_test.dart
Labels: release-notes-not-required, run-dcm-workflow

#6604 Rewrite update_flutter_sdk.sh as a Dart script
  .github/workflows/flutter-candidate-update.yaml
  CONTRIBUTING.md
  tool/RELEASE_INSTRUCTIONS.md
  tool/build_release.sh
  tool/lib/commands/release_helper.dart
  tool/lib/commands/repo_check.dart
  tool/lib/commands/update_dart_sdk_deps.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/model.dart
  tool/lib/utils.dart
  tool/update_flutter_sdk.sh
Labels: release-notes-not-required, run-dcm-workflow

#6611 Fix some Windows issues in update-flutter-sdk
  tool/lib/commands/update_flutter_sdk.dart
Labels: release-notes-not-required, run-dcm-workflow

#6608 Remove io import from devtools_app that was only used for tests
  packages/devtools_app/lib/src/shared/memory/adapted_heap_data.dart
  packages/devtools_app/test/test_infra/test_data/memory/heap/heap_data.dart
Labels: release-notes-not-required, run-dcm-workflow

#6607 devtools_app: migrate _analytics_web.dart to pkg:web
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow

#6562 Add a benchmark test for the DevTools web bundle size
  .github/workflows/build.yaml
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test_benchmarks/README.md
  packages/devtools_app/test_benchmarks/web_bundle_size_test.dart
  tool/bots.sh
Labels: release-notes-not-required, run-dcm-workflow

#6616 Disable the Raster Stats tool for Impeller
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_hints.dart
  packages/devtools_app/lib/src/screens/performance/panes/raster_stats/raster_stats.dart
  packages/devtools_app/lib/src/screens/performance/panes/raster_stats/raster_stats_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_utils.dart
  packages/devtools_app/lib/src/screens/performance/tabbed_performance_view.dart
  packages/devtools_app/lib/src/service/service_registrations.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_performance_constants.dart
  packages/devtools_app/lib/src/shared/banner_messages.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/images/open_file_performance_screen.png
  packages/devtools_app/test/performance/raster_stats/raster_stats_controller_test.dart
  packages/devtools_app/test/performance/raster_stats/raster_stats_test.dart
  packages/devtools_test/lib/src/mocks/fake_service_manager.dart
Labels: run-dcm-workflow

#6617 Make SemanticsNode.isMergedIntoParent Readonly
  packages/devtools_app/lib/src/shared/primitives/custom_pointer_scroll_view.dart
Labels: release-notes-not-required, run-dcm-workflow

#6598 New VSCode fallback behaviour for copyToClipboard
  packages/devtools_app/lib/src/framework/settings_dialog.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/config_specific/copy_to_clipboard/_copy_to_clipboard_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/copy_to_clipboard/_copy_to_clipboard_web.dart
  packages/devtools_app/lib/src/shared/config_specific/copy_to_clipboard/copy_to_clipboard.dart
  packages/devtools_app/lib/src/shared/dialogs.dart
  packages/devtools_app/lib/src/shared/editable_list.dart
  packages/devtools_app/lib/src/shared/utils.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: autosubmit, run-dcm-workflow

#6625 Prepare for 2.29.0 release
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required, run-dcm-workflow
