Repository flutter/devtools, pull requests merged in 2023-04, with the labels that each got.

#5652 Ignore to be deprecated field
  packages/devtools_app/lib/src/shared/routing.dart
Labels: autosubmit

#5681 Fixes all remaining DCM warnings in `devtools_app`
  packages/devtools_app/lib/src/screens/inspector/inspector_tree_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_events_pane.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_common_widgets.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/charts/flame_chart.dart
  packages/devtools_app/lib/src/shared/diagnostics/primitives/source_location.dart
  packages/devtools_app/lib/src/shared/dialogs.dart
  packages/devtools_app/lib/src/shared/http/_http_cookies.dart
  packages/devtools_app/lib/src/shared/http/_http_date.dart
  packages/devtools_app/lib/src/shared/http/http_request_data.dart
  packages/devtools_app/lib/src/shared/primitives/listenable.dart
  packages/devtools_app/lib/src/shared/primitives/trace_event.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/lib/src/shared/table/table.dart
  packages/devtools_app/lib/src/shared/ui/search.dart
  packages/devtools_app/lib/src/shared/version.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/legacy_integration_tests/integration.dart
  packages/devtools_app/test/performance/flutter_frames/flutter_frames_controller_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/object_inspector_view_test.dart
Labels: autosubmit, release-notes-not-required

#5682 Fix all remaining DCM warnings in `devtools_test`
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
  packages/devtools_test/lib/src/mocks/mocks.dart
  packages/devtools_test/lib/src/wrappers.dart
  packages/devtools_test/pubspec.yaml
Labels: autosubmit, release-notes-not-required

#5683 Fix all remaining DCM warnings in `devtools_shared`
  packages/devtools_shared/lib/src/memory/memory_json.dart
  packages/devtools_shared/lib/src/server/file_system.dart
  packages/devtools_shared/lib/src/server/usage.dart
  packages/devtools_shared/lib/src/test/chrome.dart
  packages/devtools_shared/lib/src/test/cli_test_driver.dart
  packages/devtools_shared/lib/src/utils/compare.dart
  packages/devtools_shared/lib/src/utils/semantic_version.dart
  packages/devtools_shared/pubspec.yaml
Labels: release-notes-not-required

#5691 Clean up pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-notes-not-required

#5690 Clean up some inconsistent styling on the app size screen
  packages/devtools_app/lib/src/screens/app_size/app_size_screen.dart
Labels: release-notes-not-required

#5694 Add `release-notes-not-required` to daily dev bump PRs
  .github/workflows/daily-dev-bump.yaml
Labels: autosubmit

#5716 Refactored inspector-related classes to use more general inspector types
  packages/devtools_app/lib/src/screens/inspector/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_screen.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_tree_controller.dart
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/lib/src/shared/preferences.dart
  packages/devtools_app/test/inspector/inspector_service_test.dart
  packages/devtools_app/test/shared/preferences_controller_test.dart
  packages/devtools_test/lib/src/mocks/mocks.dart
Labels: release-notes-not-required

#5731 Fix DCM errors at head
  packages/devtools_app/lib/src/service/service_extension_manager.dart
  packages/devtools_app/test/shared/service_manager_test.dart
  packages/devtools_test/lib/src/mocks/fake_service_extension_manager.dart
Labels: release-notes-not-required

#5732 Fix blurriness on focused line in code view
  packages/devtools_app/lib/src/screens/debugger/codeview.dart
Labels: release-notes-not-required
