Repository flutter/devtools, pull requests merged in 2024-06, with the labels that each got.

#7870 Fix doc formatting and remove `dynamic` usages in shared memory classes
  packages/devtools_shared/lib/src/memory/adb_memory_info.dart
  packages/devtools_shared/lib/src/memory/class_heap_detail_stats.dart
  packages/devtools_shared/lib/src/memory/event_sample.dart
  packages/devtools_shared/lib/src/memory/heap_sample.dart
  packages/devtools_shared/lib/src/memory/heap_space.dart
  packages/devtools_shared/lib/src/memory/memory_json.dart
Labels: release-notes-not-required

#7872 Take advantage of new core library iterable methods
  packages/devtools_app/lib/src/screens/memory/shared/primitives/memory_timeline.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/tracing/model.dart
  packages/devtools_app/lib/src/shared/console/eval/auto_complete.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/lib/src/shared/routing.dart
  packages/devtools_app_shared/lib/src/service/isolate_manager.dart
  packages/devtools_shared/lib/src/test/cli_test_driver.dart
Labels: release-notes-not-required

#7883 Fix VS Code sidebar mock app + generated mocks + remove unused method
  packages/devtools_app/lib/src/standalone_ui/api/impl/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/vs_code_api.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code.dart
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#7869 Fork the inspector tests
  packages/devtools_app/lib/src/shared/console/widgets/description.dart
  packages/devtools_app/test/inspector_v2/diagnostics_test.dart
  packages/devtools_app/test/inspector_v2/inspector_error_navigator_test.dart
  packages/devtools_app/test/inspector_v2/inspector_integration_test.dart
  packages/devtools_app/test/inspector_v2/inspector_screen_test.dart
  packages/devtools_app/test/inspector_v2/inspector_tree_test.dart
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/arrow_test.dart
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/flex_test.dart
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/goldens/arrow_bidirectional_horizontal.png
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/goldens/arrow_bidirectional_vertical.png
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/goldens/arrow_unidirectional_down.png
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/goldens/arrow_unidirectional_left.png
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/goldens/arrow_unidirectional_right.png
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/goldens/arrow_unidirectional_up.png
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/goldens/story_of_column_layout.png
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/goldens/story_of_row_layout.png
  packages/devtools_app/test/inspector_v2/layout_explorer/inspector_data_models_test.dart
  packages/devtools_app/test/inspector_v2/layout_explorer/layout_explorer_serialization_delegate.dart
  packages/devtools_app/test/inspector_v2/layout_explorer/layout_explorer_test_utils.dart
  packages/devtools_app/test/inspector_v2/utils/inspector_tree.dart
  packages/devtools_app/test/shared/diagnostics/inspector_service_test.dart
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_animated_physical_model_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_errors_1_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_errors_2_error_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_richtext_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_scaffold_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_select_center.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_select_center_details_tree.png
  packages/devtools_test/lib/src/helpers/wrappers.dart
  packages/devtools_test/lib/src/mocks/mocks.dart
Labels: release-notes-not-required

#7885 Fork `shared/console/eval/inspector_tree`
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_breadcrumbs.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_screen.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_tree_controller.dart
  packages/devtools_app/lib/src/shared/console/eval/inspector_tree_v2.dart
  packages/devtools_app/test/inspector_v2/inspector_screen_test.dart
  packages/devtools_app/test/inspector_v2/inspector_tree_test.dart
  packages/devtools_app/test/inspector_v2/layout_explorer/flex/flex_test.dart
  packages/devtools_app/test/inspector_v2/utils/inspector_tree.dart
  packages/devtools_test/lib/src/mocks/mocks.dart
Labels: release-notes-not-required

#7880 [deep link] [ios] Add a dropdown to choose ios target (default is `runner`)
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
Labels: release-notes-not-required

#7882 [deep link][ios] load links for ios and change path to nullable
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
  packages/devtools_shared/lib/src/deeplink/universal_link_settings.dart
Labels: release-notes-not-required

#7888 Add `--no-strip-wasm` flag support to build and serve commands.
  tool/lib/commands/build.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/shared.dart
Labels: release-notes-not-required

#7891 [deep link]Add UI for cross checking
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7892 [deep link] Distinguish IosDomainError and AndroidDomainError.
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_services.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
Labels: release-notes-not-required

#7896 Fix a regression with accessing the Flutter store file.
  packages/devtools_app/lib/src/shared/server/_analytics_api.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/devtools_server.dart
  packages/devtools_shared/lib/src/server/devtools_store.dart
  packages/devtools_shared/lib/src/server/file_system.dart
  packages/devtools_shared/lib/src/server/flutter_store.dart
  packages/devtools_shared/lib/src/server/server_api.dart
Labels: release-notes-not-required

#7897 Add `avoid-importing-entrypoint-exports` DCM lint.
  packages/analysis_options.yaml
  packages/devtools_app/lib/src/framework/about_dialog.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/framework/release_notes/release_notes.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/import_export.dart
  packages/devtools_app/lib/src/shared/diagnostics/references.dart
  packages/devtools_app/lib/src/shared/survey.dart
  packages/devtools_app/lib/src/shared/utils.dart
  packages/devtools_extensions/lib/src/utils.dart
Labels: release-notes-not-required

#7890 [deep link] Add a ios AASA check tile
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7900 Improve the Performance page for narrow screens.
  packages/devtools_app/lib/src/screens/performance/panes/controls/performance_controls.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frames_chart.dart
Labels: release-notes-not-required

#7908 Remove unused code from DevTools.
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_model.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_view.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profiler.dart
  packages/devtools_app/lib/src/screens/profiler/panes/controls/cpu_profiler_controls.dart
  packages/devtools_app/lib/src/screens/vm_developer/isolate_statistics/isolate_statistics_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_inspector_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/process_memory/process_memory_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_statistics/vm_statistics_view.dart
  packages/devtools_app/lib/src/service/service_extensions.dart
  packages/devtools_app/lib/src/service/vm_flags.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_cpu_profiler_constants.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/primitives/enum_utils.dart
  packages/devtools_app/lib/src/shared/primitives/geometry.dart
  packages/devtools_app/lib/src/shared/primitives/message_bus.dart
  packages/devtools_app/lib/src/shared/primitives/simple_items.dart
  packages/devtools_app/lib/src/shared/server/server.dart
  packages/devtools_app/lib/src/shared/ui/utils.dart
  packages/devtools_app/test/cpu_profiler/cpu_profiler_test.dart
  packages/devtools_app/test/debugger/debugger_model_test.dart
  packages/devtools_app/test/shared/geometry_test.dart
  packages/devtools_app/test/shared/vm_flag_widgets_test.dart
  packages/devtools_app/test/shared/widget_rebuild_counts_test.dart
  packages/devtools_app/test/test_infra/flutter_test_environment.dart
  packages/devtools_app/test/test_infra/matchers/matchers.dart
  packages/devtools_app/test/test_infra/test_data/extensions.dart
Labels: release-notes-not-required

#7909 Upgrade DCM version on the bots and fix lints.
  .github/workflows/build.yaml
  packages/devtools_app/lib/src/framework/notifications_view.dart
  packages/devtools_app/lib/src/framework/status_line.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/select_project_view.dart
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_controller_v2.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/legend.dart
  packages/devtools_app/lib/src/screens/performance/performance_model.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_common_widgets.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_service_private_extensions.dart
  packages/devtools_app_shared/lib/src/ui/dialogs.dart
  packages/devtools_shared/test/server/general_api_test.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required

#7907 Add missing dispose method in sidebar api and remove unused code.
  packages/devtools_app/lib/src/standalone_ui/api/dart_tooling_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/dart_tooling_api.dart
  packages/devtools_app/lib/src/standalone_ui/standalone_screen.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code.dart
Labels: release-notes-not-required

#7906 Remove unused code in the memory page, and add TODOs for bugs
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/data/charts.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/data/primitives.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/instances.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_list.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/instances.dart
  packages/devtools_app/lib/src/screens/memory/shared/primitives/memory_utils.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_memory_constants.dart
  packages/devtools_app/lib/src/shared/memory/classes.dart
  packages/devtools_app/lib/src/shared/memory/retaining_path.dart
  packages/devtools_app/lib/src/shared/routing.dart
Labels: release-notes-not-required

#7904 Remove unused code and fix a type check bug in Deep Links page
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/lib/src/shared/ui/colors.dart
Labels: release-notes-not-required

#7910 Cleanup to use a utility method.
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_web.dart
Labels: release-notes-not-required

#7913 Add back golden test to `inspector_service_test`
  packages/devtools_app/test/shared/diagnostics/inspector_service_test.dart
  packages/devtools_app/test/test_infra/goldens/inspector_service_details_tree.txt
  packages/devtools_app/test/test_infra/matchers/matchers.dart
Labels: release-notes-not-required

#7914 Clean up survey prompt styling
  packages/devtools_app/lib/src/framework/notifications_view.dart
  packages/devtools_app/lib/src/screens/debugger/codeview_controller.dart
  packages/devtools_app/lib/src/screens/debugger/controls.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_debugger_constants.dart
  packages/devtools_app/lib/src/shared/notifications.dart
  packages/devtools_app/lib/src/shared/survey.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
Labels: release-notes-not-required

#7920 Update the `debugSurveyMetadata` helper
  packages/devtools_app/lib/src/shared/development_helpers.dart
Labels: release-notes-not-required

#7921 Clean up event name strings throughout DevTools
  packages/devtools_app/lib/src/screens/logging/_kind_column.dart
  packages/devtools_app/lib/src/screens/logging/_message_column.dart
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_controller_v2.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/memory_tracker.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/data/charts.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart
  packages/devtools_app/lib/src/shared/console/console_service.dart
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/lib/src/shared/error_badge_manager.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/service.dart
  packages/devtools_app_shared/lib/src/service/constants.dart
  packages/devtools_app_shared/lib/src/service/service_extension_manager.dart
  packages/devtools_shared/test/server/general_api_test.dart
Labels: release-notes-not-required

#7923 Expose service manager helpers in `devtools_app_shared`
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/preferences/_inspector_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_inspector_v2_preferences.dart
  packages/devtools_app/test/shared/diagnostics/inspector_service_test.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/service_manager.dart
  packages/devtools_test/lib/src/mocks/fake_service_manager.dart
Labels: release-notes-not-required

#7924 [devtools_tool] Platform agnostic package root determination
  tool/lib/model.dart
Labels: release-notes-not-required

#7918 Refactor VS Code sidebar to make more generic and align with new DTD APIs
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/service/editor/api_classes.dart
  packages/devtools_app/lib/src/service/editor/editor_client.dart
  packages/devtools_app/lib/src/service/editor/readme.md
  packages/devtools_app/lib/src/standalone_ui/api/dart_tooling_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/dart_tooling_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/standalone_screen.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devices.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/test/standalone_ui/vs_code/debug_sessions_test.dart
  packages/devtools_app/test/standalone_ui/vs_code/devtools_test.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/editor_service/editor_server.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/editor_service/fake_editor.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/editor_service/post_message_fake_editor.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/mock_editor_widget.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
  packages/devtools_shared/lib/src/utils/serialization.dart
  packages/devtools_test/lib/src/mocks/generated.dart
Labels: release-notes-not-required

#7820 Base Logging V2 behaviour
  packages/devtools_app/.vscode/settings.json
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_controller_v2.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_model.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_screen_v2.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_row.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_v2.dart
  packages/devtools_app/lib/src/shared/globals.dart
  packages/devtools_app/lib/src/shared/ui/utils.dart
  packages/devtools_app/lib/src/shared/utils.dart
  packages/devtools_app/test/logging/logging_screen_v2/logging_controller_v2_test.dart
  packages/devtools_app/test/logging/logging_screen_v2/logging_screen_v2_test.dart
  packages/devtools_app/test/shared/utils_test.dart
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
  packages/devtools_test/lib/src/helpers/wrappers.dart
  packages/devtools_test/lib/src/mocks/generated_mocks_factories.dart
Labels: release-notes-not-required

#7938 push the benchmark size.
  packages/devtools_app/benchmark/web_bundle_size_test.dart
Labels: release-notes-not-required

#7932 Add settings dialog to Logging V2
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_v2.dart
Labels: release-notes-not-required

#7875 Migrate devtools wiki & update old flutter wiki links
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  STYLE.md
  TRIAGE.md
  docs/README.md
  packages/analysis_options.yaml
  packages/devtools_app/lib/src/framework/about_dialog.dart
  packages/devtools_app/test/legacy_integration_tests/integration.dart
  packages/devtools_extensions/README.md
  packages/devtools_shared/lib/src/test/chrome_driver.dart
  tool/RELEASE_INSTRUCTIONS.md
Labels: autosubmit, release-notes-not-required

#7943 Add API fields to allow passing requiresDebugSession to openDevTools
  packages/devtools_app/lib/src/service/editor/editor_client.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/dart_tooling_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/vs_code_api.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/editor_service/editor_server.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/editor_service/fake_editor.dart
Labels: release-notes-not-required

#7912 [Inspector V2] Unify summary tree and widget details tree
  packages/devtools_app/integration_test/test/live_connection/eval_and_inspect_test.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_tree_controller.dart
  packages/devtools_app/lib/src/shared/console/widgets/description.dart
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/test/inspector_v2/inspector_integration_test.dart
  packages/devtools_app/test/shared/diagnostics/inspector_service_test.dart
  packages/devtools_app/test/test_infra/goldens/inspector_service_node_no_summary.txt
  packages/devtools_app/test/test_infra/goldens/inspector_service_node_summary.txt
  packages/devtools_app/test/test_infra/goldens/inspector_service_tree_no_summary.txt
  packages/devtools_app/test/test_infra/goldens/inspector_service_tree_summary.txt
  packages/devtools_app/test/test_infra/goldens/integration_animated_physical_model_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_richtext_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_scaffold_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center_details_tree.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_errors_1_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_errors_2_error_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_initial_load.png
Labels: release-notes-not-required

#7949 Add "prefersDebugSession" + rename capabilities flag
  packages/devtools_app/lib/src/service/editor/editor_client.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/dart_tooling_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/vs_code_api.dart
  packages/devtools_app/lib/src/standalone_ui/api/vs_code_api.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/editor_service/editor_server.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/editor_service/fake_editor.dart
Labels: release-notes-not-required

#7945 [deep link] Update loading string
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/select_project_view.dart
Labels: release-notes-not-required

#7957 Skip another eval_integration_test case that is flaking in the Flutter customer tests
  packages/devtools_app/test/shared/eval_integration_test.dart
Labels: release-notes-not-required

#7953 Update flutter.dev links to more permanent destinations
  CONTRIBUTING.md
  DOCUMENTATION.md
  README.md
  STYLE.md
  case_study/code_size/optimized/code_size_images/android/.gitignore
  case_study/code_size/optimized/code_size_package/android/.gitignore
  case_study/code_size/unoptimized/code_size_images/android/.gitignore
  case_study/code_size/unoptimized/code_size_package/android/.gitignore
  case_study/memory_leaks/images_1/android/.gitignore
  case_study/memory_leaks/leaking_counter_1/android/.gitignore
  case_study/memory_leaks/leaking_counter_1/android/app/build.gradle
  packages/devtools_app/README.md
  packages/devtools_app/integration_test/README.md
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/diff_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/ALLOCATION_PROFILE.md
  packages/devtools_app/lib/src/screens/memory/panes/tracing/ALLOCATION_TRACING.md
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_hints.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/screens/performance/performance_utils.dart
  packages/devtools_app/lib/src/service/service_extensions.dart
  packages/devtools_app/lib/src/shared/banner_messages.dart
  packages/devtools_app/lib/src/shared/console/widgets/help_dialog.dart
  packages/devtools_app/lib/src/shared/primitives/simple_items.dart
  packages/devtools_app_shared/README.md
  packages/devtools_extensions/README.md
  packages/devtools_test/README.md
Labels: release-notes-not-required

#7959 Move logic to de-duplicate extensions into a helper file for shared use
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/extensions/extension_service_helpers.dart
  packages/devtools_app/test/extensions/extension_service_helpers_test.dart
  packages/devtools_app/test/extensions/extension_service_test.dart
  packages/devtools_app/test/shared/diagnostics/inspector_service_test.dart
Labels: release-notes-not-required

#7964 Fix survey metadata URL in documentation.
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/survey.dart
Labels: release-notes-not-required

#7871 Remove usages of BoundField#decl
  packages/devtools_app/lib/src/screens/provider/instance_viewer/instance_providers.dart
  packages/devtools_app/lib/src/screens/provider/provider_nodes.dart
  packages/devtools_app/lib/src/shared/console/eval/auto_complete.dart
  packages/devtools_app/lib/src/shared/diagnostics/references.dart
  packages/devtools_app/lib/src/shared/diagnostics/variable_factory.dart
Labels: release-notes-not-required

#7956 update to package:web 0.5.1
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_web.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required

#7951 Implement the log retention setting
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_model.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_row.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_v2.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/settings_dialog.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_logging_constants.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_web.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/_notifications_web.dart
  packages/devtools_app/lib/src/shared/preferences/_logging_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/preferences.dart
  packages/devtools_app/lib/src/shared/utils.dart
  packages/devtools_app/test/logging/logging_screen_v2/logging_controller_v2_test.dart
  packages/devtools_app/test/logging/logging_screen_v2/logging_model_test.dart
  packages/devtools_app/test/logging/logging_screen_v2/logging_screen_v2_test.dart
Labels: autosubmit, release-notes-not-required

#7973 Show extensions that require a connection even when there is not a connected app in embedded mode
  packages/devtools_app/integration_test/test/live_connection/devtools_extensions_test.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/extensions/embedded/view.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/_notifications_web.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/test/extensions/extension_screen_test.dart
  packages/devtools_app/test/extensions/extension_service_test.dart
  packages/devtools_app/test/shared/screens_test.dart
  packages/devtools_app_shared/lib/src/utils/web_utils.dart
Labels: release-notes-not-required

#7868 [deeplinks] add more instruments for validating project
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/select_project_view.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_deep_links_constants.dart
Labels: release-notes-not-required

#7976 Refactor DevTools sidebar code.
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/devtools_view.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/extensions_view.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/shared.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/sidebar_extensions_controller.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/test/standalone_ui/vs_code/devtools_test.dart
Labels: release-notes-not-required

#7979 Move some common widgets and utilities to `devtools_app_shared`
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/root_selector.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/interval_dropdown.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/classes_table_diff.dart
  packages/devtools_app/lib/src/screens/profiler/panes/controls/cpu_profiler_controls.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_inspector_view.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/file_import.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/lib/src/shared/ui/drop_down_button.dart
  packages/devtools_app/lib/src/shared/ui/search.dart
  packages/devtools_app/test/memory/tracing/tracing_view_test.dart
  packages/devtools_app/test/shared/primitives/utils_test.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/ui/buttons.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
  packages/devtools_app_shared/lib/src/ui/text_field.dart
  packages/devtools_app_shared/lib/src/utils/utils.dart
  packages/devtools_app_shared/lib/ui.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_app_shared/test/utils/utils_test.dart
Labels: release-notes-not-required

#7984 [deep link] Add logic to validate ios domain errors in controller
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_services.dart
Labels: release-notes-not-required

#7978 Optimize how the inspector V2 tree is built and updated
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_tree_controller.dart
  packages/devtools_app/lib/src/shared/console/eval/inspector_tree_v2.dart
  packages/devtools_app/test/inspector_v2/inspector_tree_test.dart
Labels: release-notes-not-required

#7993 Check whether the version in flutter-candidate.txt is a tag or a commit hash
  tool/lib/commands/update_flutter_sdk.dart
Labels: autosubmit, release-notes-not-required

#7997 Fix incorrect type in release notes server api.
  packages/devtools_app/test/shared/disconnect_observer_test.dart
  packages/devtools_shared/lib/src/server/server_api.dart
Labels: release-notes-not-required

#7998 Prepare for release 2.37.0
  flutter-candidate.txt
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required

#8003 Revert "Prepare for release 2.37.0 (#7998)"
  flutter-candidate.txt
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required

#8007 Prepare for release 2.37.0
  flutter-candidate.txt
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
Labels: autosubmit
