Repository flutter/devtools, pull requests merged in 2024-01, with the labels that each got.

#7015 Prepare for release Using Flutter SDK from /Users/polinach/_/devtools/tool/flutter-sdk 2.31.0
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#7016 Add dev version.
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#7013 Update RELEASE_INSTRUCTIONS.md
  tool/RELEASE_INSTRUCTIONS.md
Labels: autosubmit

#7033 Use a minimum fixed size for variable width columns instead of measuring text
  packages/devtools_app/lib/src/screens/profiler/panes/cpu_profile_columns.dart
  packages/devtools_app/lib/src/screens/profiler/panes/method_table/method_table.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/lib/src/shared/profiler_utils.dart
  packages/devtools_app/lib/src/shared/table/column_widths.dart
  packages/devtools_app/lib/src/shared/table/table.dart
  packages/devtools_app/lib/src/shared/table/table_controller.dart
  packages/devtools_app/lib/src/shared/table/table_data.dart
  packages/devtools_app/test/primitives/utils_test.dart
  packages/devtools_app/test/shared/table_test.dart
Labels: release-notes-not-required

#7032 Add a Process Memory view to VM Tools
  packages/devtools_app/lib/src/screens/vm_developer/process_memory/process_memory_tree_columns.dart
  packages/devtools_app/lib/src/screens/vm_developer/process_memory/process_memory_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/process_memory/process_memory_view_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_tools_screen.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/charts/treemap.dart
  packages/devtools_app/lib/src/shared/table/table_data.dart
Labels: release-notes-not-required

#7037 Update to avoid deprecated library in `package:web` v0.4.1
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_web.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_web.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_web.dart
  packages/devtools_app/lib/src/shared/config_specific/host_platform/_host_platform_web.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_web.dart
  packages/devtools_app/lib/src/shared/config_specific/launch_url/_launch_url_web.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_allowed_error_web.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_logger_web.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/_notifications_web.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/_post_message_web.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/lib/src/ui/theme/_ide_theme_web.dart
  packages/devtools_app_shared/lib/src/utils/url/_url_web.dart
  packages/devtools_app_shared/lib/src/utils/web_utils.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/utils.dart
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required

#7041 Clean up devtools_tool dependencies
  tool/json_to_map.dart
  tool/pubspec.yaml
Labels: release-notes-not-required

#7043 Remove superseded repo tool in root directory
  bin/repo_tool
Labels: release-notes-not-required

#7048 Fix typos.
  packages/devtools_app/lib/src/screens/memory/panes/tracing/tracing_tree.dart
  packages/devtools_app/lib/src/shared/table/table.dart
  packages/devtools_app/lib/src/shared/table/table_controller.dart
Labels: release-notes-not-required

#7044 Minor cleanup and updates to case_study directory
  case_study/code_size/optimized/code_size_images/README.md
  case_study/code_size/optimized/code_size_images/lib/main.dart
  case_study/code_size/optimized/code_size_images/pubspec.yaml
  case_study/code_size/optimized/code_size_package/README.md
  case_study/code_size/optimized/code_size_package/lib/main.dart
  case_study/code_size/optimized/code_size_package/pubspec.yaml
  case_study/code_size/unoptimized/code_size_images/README.md
  case_study/code_size/unoptimized/code_size_images/lib/main.dart
  case_study/code_size/unoptimized/code_size_images/pubspec.yaml
  case_study/code_size/unoptimized/code_size_package/README.md
  case_study/code_size/unoptimized/code_size_package/lib/main.dart
  case_study/code_size/unoptimized/code_size_package/pubspec.yaml
  case_study/memory_leaks/images_1/README.md
  case_study/memory_leaks/images_1/analysis_options.yaml
  case_study/memory_leaks/images_1/lib/main.dart
  case_study/memory_leaks/images_1/pubspec.yaml
  case_study/memory_leaks/images_1/web/README.md
  case_study/memory_leaks/leaking_counter_1/analysis_options.yaml
  case_study/memory_leaks/leaking_counter_1/pubspec.yaml
  case_study/memory_leaks/memory_leak_app/README.md
  case_study/memory_leaks/memory_leak_app/lib/about.dart
  case_study/memory_leaks/memory_leak_app/lib/logging.dart
  case_study/memory_leaks/memory_leak_app/lib/main.dart
  case_study/memory_leaks/memory_leak_app/lib/restful_servers.dart
  case_study/memory_leaks/memory_leak_app/lib/tabs/http_data.dart
  case_study/memory_leaks/memory_leak_app/lib/tabs/logger.dart
  case_study/memory_leaks/memory_leak_app/lib/tabs/settings.dart
  case_study/memory_leaks/memory_leak_app/pubspec.yaml
  case_study/platform_channel/README.md
  case_study/platform_channel/lib/channel_demo.dart
  case_study/platform_channel/pubspec.yaml
Labels: release-notes-not-required

#7052 Added a description and link to documentation in the `devtools_options.yaml` file.
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/extensions/extension_enablement.dart
  packages/devtools_shared/test/extensions/extension_enablement_test.dart
Labels: release-notes-not-required

#7056 Refactor `table.dart` using part files to make it more manageable.
  packages/devtools_app/lib/src/shared/table/_flat_table.dart
  packages/devtools_app/lib/src/shared/table/_table_column.dart
  packages/devtools_app/lib/src/shared/table/_table_row.dart
  packages/devtools_app/lib/src/shared/table/_tree_table.dart
  packages/devtools_app/lib/src/shared/table/table.dart
Labels: release-notes-not-required

#6709 Show extension screens in the VS code sidebar DevTools dropdown
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/globals.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/dart_tooling_api.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
  packages/devtools_app/macos/Runner.xcodeproj/project.pbxproj
  packages/devtools_app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/standalone_ui/vs_code/debug_sessions_test.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code_mock_editor.dart
  packages/devtools_app/test/test_infra/test_data/dart_tooling_api/mock_api.dart
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
  packages/devtools_test/lib/src/mocks/generated.dart
  packages/devtools_test/lib/src/mocks/generated_mocks_factories.dart
Labels: vs-code, flutter sidebar

#7067 Add back Open In Browser button to VS code sidebar devtools menu
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
Labels: release-notes-not-required

#7069 UI polish
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/editable_list.dart
  packages/devtools_app/test/test_infra/goldens/treemap_apk.png
  packages/devtools_app/test/test_infra/goldens/treemap_sizes.png
  packages/devtools_app/test/test_infra/goldens/treemap_v8.png
Labels: release-notes-not-required

#7085 Create `CliCommand.dart` that uses the Dart executable from flutter
  tool/lib/commands/analyze.dart
  tool/lib/commands/release_helper.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/sync.dart
  tool/lib/model.dart
  tool/lib/utils.dart
Labels: release-notes-not-required

#7091 Simplify CpuSamplesPrivateView.codes
  packages/devtools_app/lib/src/screens/vm_developer/vm_service_private_extensions.dart
Labels: release-notes-not-required

#7087 Add a return type to all function types, avoiding implicit dynamic
  packages/devtools_app/lib/src/framework/app_bar.dart
  packages/devtools_app/lib/src/screens/app_size/app_size_screen.dart
  packages/devtools_app/lib/src/screens/debugger/program_explorer.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_breadcrumbs.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_screen.dart
  packages/devtools_app/lib/src/screens/memory/panes/tracing/tracing_tree.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/class_filter.dart
  packages/devtools_app/lib/src/screens/memory/shared/widgets/class_filter.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/legacy/timeline_flame_chart.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_common_widgets.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/editable_list.dart
  packages/devtools_app/lib/src/shared/file_import.dart
  packages/devtools_app/lib/src/shared/preferences.dart
  packages/devtools_app/lib/src/shared/primitives/extent_delegate_list.dart
  packages/devtools_app/lib/src/shared/table/_table_column.dart
  packages/devtools_app/lib/src/shared/table/_table_row.dart
  packages/devtools_app/lib/src/shared/ui/search.dart
  packages/devtools_app/test/shared/syntax_highlighter_test.dart
  packages/devtools_app/test/test_infra/utils/test_utils.dart
Labels: release-notes-not-required

#7089 Add parameter type to Future.catchError onError parameter
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/test/legacy_integration_tests/integration.dart
  packages/devtools_app/test/shared/eval_integration_test.dart
  packages/devtools_shared/lib/src/service/service.dart
  packages/devtools_shared/lib/src/test/cli_test_driver.dart
Labels: release-notes-not-required

#7090 Add types to parameters with no inference
  packages/devtools_app/lib/src/screens/debugger/syntax_highlighter.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_android_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/instances.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/instances.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/profile_view.dart
  packages/devtools_app/lib/src/shared/charts/chart.dart
  packages/devtools_app/lib/src/shared/charts/chart_controller.dart
  packages/devtools_app/lib/src/shared/charts/treemap.dart
  packages/devtools_app/lib/src/shared/diagnostics/dap_object_node.dart
  packages/devtools_app/lib/src/shared/notifications.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
Labels: release-notes-not-required

#7088 Add explicit type arguments where they are not inferred
  packages/devtools_app/lib/src/screens/debugger/codeview.dart
  packages/devtools_app/lib/src/screens/debugger/file_search.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/heap.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/model.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/spanning_tree.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_hints.dart
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/lib/src/shared/memory/adapted_heap_data.dart
  packages/devtools_app/lib/src/shared/ui/hover.dart
  packages/devtools_app/lib/src/standalone_ui/api/impl/dart_tooling_api.dart
  packages/devtools_app/test/debugger/debugger_controller_test.dart
  packages/devtools_app/test/legacy_integration_tests/integration.dart
  packages/devtools_app/test/network/network_model_test.dart
  packages/devtools_app/test/performance/performance_model_test.dart
  packages/devtools_app/test/performance/timeline_events/legacy/legacy_event_processor_test.dart
  packages/devtools_app/test/performance/timeline_events/perfetto/perfetto_event_processor_test.dart
  packages/devtools_app/test/primitives/utils_test.dart
  packages/devtools_app/test/test_infra/fixtures/memory_app/lib/main.dart
  packages/devtools_app/test/test_infra/flutter_test_environment.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code_mock_editor.dart
  packages/devtools_app_shared/test/utils/auto_dispose_mixin_test.dart
  packages/devtools_shared/lib/src/service/service.dart
  packages/devtools_test/lib/src/mocks/fake_vm_service_wrapper.dart
Labels: release-notes-not-required

#7093 Remove splitting by spaces from process/command helpers
  tool/lib/commands/analyze.dart
  tool/lib/commands/build.dart
  tool/lib/commands/fix_goldens.dart
  tool/lib/commands/generate_code.dart
  tool/lib/commands/pub_get.dart
  tool/lib/commands/release_helper.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/sync.dart
  tool/lib/commands/update_dart_sdk_deps.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/commands/update_perfetto.dart
  tool/lib/utils.dart
Labels: release-notes-not-required

#7101 Refactor AxisScale to not use dynamic or late
  packages/devtools_app/lib/src/shared/charts/chart_trace.dart
  packages/devtools_app/test/memory/chart/chart_test.dart
Labels: release-notes-not-required

#7103 Remove unused type parameters from MultiValueListenableBuilder
  packages/devtools_app/lib/src/shared/common_widgets.dart
Labels: release-notes-not-required

#7102 Remove one-off dynamic invocations
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/lib/src/screens/app_size/code_size_attribution.dart
  packages/devtools_app/lib/src/screens/logging/_message_column.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/chart_pane.dart
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_service.dart
  packages/devtools_app/lib/src/screens/vm_developer/isolate_statistics/isolate_statistics_view_controller.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/server/_dtd_api.dart
  packages/devtools_app/lib/src/shared/server/_extensions_api.dart
  packages/devtools_app/lib/src/shared/server/_release_notes_api.dart
  packages/devtools_app/lib/src/shared/server/_survey_api.dart
  packages/devtools_app/lib/src/shared/server/server.dart
  packages/devtools_app/test/test_infra/utils/test_utils.dart
  packages/devtools_shared/lib/src/server/file_system.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required

#7100 Skip a flaky test in debugger_evaluation_test
  packages/devtools_app/test/debugger/debugger_evaluation_test.dart
Labels: test flake, release-notes-not-required

#7119 Remove dynamic invocations in vm_service_private_extensions
  packages/devtools_app/lib/src/screens/vm_developer/vm_service_private_extensions.dart
  packages/devtools_app/test/shared/eval_integration_test.dart
Labels: release-notes-not-required

#7113 Remove unnecessary imports of 'package:collection' `IterableExtension`
  packages/devtools_app/lib/src/screens/performance/panes/rebuild_stats/rebuild_stats_model.dart
  packages/devtools_app/lib/src/shared/server/_extensions_api.dart
  packages/devtools_app/lib/src/shared/server/server.dart
  packages/devtools_shared/lib/src/test/integration_test_runner.dart
Labels: release-notes-not-required

#7129 Migrate `tag_version.sh` to a `devtools_tool` command
  tool/RELEASE_INSTRUCTIONS.md
  tool/lib/commands/tag_version.dart
  tool/lib/devtools_command_runner.dart
  tool/pubspec.yaml
  tool/tag_version.sh
Labels: release-notes-not-required

#7116 Fix extensions not showing in sidebar on Windows
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/server/_extensions_api.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
  packages/devtools_app/test/standalone_ui/vs_code/debug_sessions_test.dart
  packages/devtools_shared/lib/src/devtools_api.dart
Labels: release-notes-not-required

#7138 Add `showDevToolsDialog` helper method to `devtools_app_shared`
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/ui/dialogs.dart
Labels: release-notes-not-required

#7134 Re-enable `debugger_evaluation_test`
  packages/devtools_app/test/debugger/debugger_evaluation_test.dart
Labels: release-notes-not-required

#7140 Prepare for release 2.32.0
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required
