Repository flutter/devtools, pull requests merged in 2024-04, with the labels that each got.

#7502 Move chart related code to chart controller.
  STYLE.md
  packages/devtools_app/integration_test/test/live_connection/memory_screen_helpers.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/connected_screen_body.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_tracker.dart
  packages/devtools_app/lib/src/screens/memory/panes/README.md
  packages/devtools_app/lib/src/screens/memory/panes/chart/chart_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/data/charts.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/data/primitives.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/interval_dropdown.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/legend.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/memory_android_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/memory_events_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/memory_vm_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/controller/control_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/primary_controls.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/secondary_controls.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/settings_dialog.dart
  packages/devtools_app/lib/src/shared/charts/chart_controller.dart
  packages/devtools_app/test/memory/chart/chart_test.dart
  packages/devtools_app/test/memory/control/settings_dialog_test.dart
  packages/devtools_app/test/memory/framework/memory_screen_test.dart
  packages/devtools_app/test/memory/framework/memory_service_test.dart
Labels: autosubmit, release-notes-not-required

#7510 Rename offline mode API items.
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/example/conditional_screen.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/framework/initializer.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frames_chart.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frames_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/raster_stats/raster_stats.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_view.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/screens/performance/tabbed_performance_view.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profiler_controller.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen_controller.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/banner_messages.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/import_export.dart
  packages/devtools_app/lib/src/shared/globals.dart
  packages/devtools_app/lib/src/shared/offline_data.dart
  packages/devtools_app/lib/src/shared/offline_screen.dart
  packages/devtools_app/lib/src/shared/profiler_utils.dart
  packages/devtools_app/lib/src/shared/screen.dart
  packages/devtools_app/test/cpu_profiler/cpu_profiler_controller_test.dart
  packages/devtools_app/test/cpu_profiler/cpu_profiler_test.dart
  packages/devtools_app/test/cpu_profiler/method_table/method_table_test.dart
  packages/devtools_app/test/cpu_profiler/profiler_screen_controller_test.dart
  packages/devtools_app/test/memory/framework/memory_screen_test.dart
  packages/devtools_app/test/performance/controls/performance_controls_test.dart
  packages/devtools_app/test/performance/flutter_frames/flutter_frames_chart_test.dart
  packages/devtools_app/test/performance/frame_analysis/frame_analysis_test.dart
  packages/devtools_app/test/performance/frame_analysis/frame_hints_test.dart
  packages/devtools_app/test/performance/performance_controller_test.dart
  packages/devtools_app/test/performance/performance_screen_test.dart
  packages/devtools_app/test/performance/raster_stats/raster_stats_test.dart
  packages/devtools_app/test/performance/tabbed_performance_view_test.dart
  packages/devtools_app/test/performance/timeline_events/timeline_event_processor_test.dart
  packages/devtools_app/test/performance/timeline_events/timeline_events_controller_test.dart
  packages/devtools_app/test/shared/import_export_test.dart
  packages/devtools_app/test/shared/initializer_test.dart
  packages/devtools_app/test/shared/scaffold_debugger_test.dart
  packages/devtools_app/test/shared/scaffold_debugging_controls_test.dart
  packages/devtools_app/test/shared/scaffold_no_app_test.dart
  packages/devtools_app/test/shared/scaffold_profile_test.dart
  packages/devtools_app/test/shared/scaffold_test.dart
  packages/devtools_app/test/shared/visible_screens_test.dart
  packages/devtools_app/test/test_infra/flutter_test_environment.dart
  packages/devtools_app/test/test_infra/scenes/cpu_profiler/default.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
  packages/devtools_app/test/test_infra/scenes/memory/diff_snapshot.dart
  packages/devtools_app/test/test_infra/scenes/performance/default.dart
Labels: release-notes-not-required

#7512 Move initReviewHistoryOnDisconnectListener to framework.
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen_controller.dart
Labels: release-notes-not-required

#7513 Remove unused `DevToolsScreen.controller` parameter.
  packages/devtools_app/lib/src/app.dart
Labels: release-notes-not-required

#7515 Improve documentation for framework.
  packages/devtools_app/lib/src/shared/offline_data.dart
  packages/devtools_app/lib/src/shared/screen.dart
Labels: autosubmit, release-notes-not-required

#7517 Add documentation.
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/shared/screen.dart
Labels: autosubmit, release-notes-not-required

#7518 Refactor memory screen.
  packages/devtools_app/lib/src/screens/memory/.gitignore
  packages/devtools_app/lib/src/screens/memory/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/framework/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/framework/connected/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/framework/connected/connected_screen_body.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/android_chart_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/event_chart_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/memory_tracker.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/vm_chart_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/data/charts.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/interval_dropdown.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/legend.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/memory_android_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/memory_events_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/memory_vm_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/panes/control/controller/control_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/secondary_controls.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_list.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/panes/tracing/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/shared/DEPENDENCIES.md
  packages/devtools_app/lib/src/shared/charts/chart_controller.dart
  packages/devtools_app/lib/src/shared/memory/DEPENDENCIES.md
  packages/devtools_app/test/memory/framework/memory_screen_test.dart
  packages/devtools_app/test/memory/framework/memory_service_test.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
Labels: release-notes-not-required

#7522 Add a `debugDtdUri` development helper and clean up memory debug flag
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/memory/retaining_path.dart
  packages/devtools_app/lib/src/shared/server/_dtd_api.dart
  packages/devtools_app/test/shared/development_helpers_test.dart
Labels: release-notes-not-required

#7507 [deep link] Auto-select a deep link when user tap the recheck/ fix domain/fix path buttons.
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7526 Enable experiment as constant.
  packages/.vscode/launch.json
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/example/conditional_screen.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/lib/src/shared/offline_data.dart
  packages/devtools_app/lib/src/shared/screen.dart
Labels: release-notes-not-required

#7527 Merge feature controllers into memory controller.
  packages/devtools_app/lib/src/screens/memory/framework/connected/connected_screen_body.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_tabs.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_pane_controller.dart
  packages/devtools_app/test/memory/diff/widgets/diff_pane_test.dart
  packages/devtools_app/test/memory/framework/memory_controller_test.dart
  packages/devtools_app/test/memory/framework/memory_screen_test.dart
  packages/devtools_app/test/memory/framework/memory_service_test.dart
  packages/devtools_app/test/memory/profile/allocation_profile_table_view_test.dart
  packages/devtools_app/test/memory/tracing/tracing_view_test.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
Labels: release-notes-not-required

#7532 Add the ability to run `devtools_tool serve` with a local Dart SDK build
  tool/lib/commands/serve.dart
  tool/lib/utils.dart
Labels: release-notes-not-required

#7534 Move code out of `connected`.
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/screens/memory/framework/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/framework/connected/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/framework/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/memory_screen.dart
  packages/devtools_app/lib/src/screens/memory/framework/memory_tabs.dart
  packages/devtools_app/lib/src/screens/memory/framework/screen_body.dart
  packages/devtools_app/test/memory/diff/widgets/diff_pane_test.dart
  packages/devtools_app/test/memory/framework/memory_controller_test.dart
  packages/devtools_app/test/memory/framework/memory_service_test.dart
  packages/devtools_app/test/memory/profile/allocation_profile_table_view_test.dart
  packages/devtools_app/test/memory/tracing/tracing_view_test.dart
Labels: autosubmit, release-notes-not-required

#7488 Migrate to using unified_analytics from DTD
  packages/devtools_app/benchmark/test_infra/automators/devtools_automator.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_controller_stub.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_controller_web.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_stub.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/analytics_controller.dart
  packages/devtools_app/lib/src/shared/dtd_manager_extensions.dart
  packages/devtools_app/lib/src/shared/server/_analytics_api.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/shared/analytics_prompt_test.dart
  packages/devtools_app/test/shared/scaffold_debugger_test.dart
  packages/devtools_app/test/shared/scaffold_debugging_controls_test.dart
  packages/devtools_app/test/shared/scaffold_no_app_test.dart
  packages/devtools_app/test/shared/scaffold_profile_test.dart
  packages/devtools_app/test/shared/scaffold_test.dart
  packages/devtools_app_shared/lib/src/service/dtd_manager.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/server/deeplink_api_test.dart
  packages/devtools_shared/test/server/dtd_api_test.dart
  packages/devtools_shared/test/server/general_api_test.dart
Labels: release-notes-not-required

#7539 Clean up styling for analytics prompt
  packages/devtools_app/lib/src/shared/analytics/analytics_controller.dart
  packages/devtools_app/lib/src/shared/analytics/gtags.dart
  packages/devtools_app/lib/src/shared/analytics/prompt.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/test/shared/analytics_prompt_test.dart
  packages/devtools_app/test/shared/development_helpers_test.dart
Labels: release-notes-not-required

#7545 Reorganize tracing code.
  packages/devtools_app/lib/src/screens/memory/panes/tracing/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/panes/tracing/class_table.dart
  packages/devtools_app/lib/src/screens/memory/panes/tracing/tracing_data.dart
  packages/devtools_app/lib/src/screens/memory/panes/tracing/tracing_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/tracing/tracing_tree.dart
Labels: autosubmit, release-notes-not-required

#7540 Add getter for devtools mode.
  packages/devtools_app/lib/src/screens/memory/framework/memory_controller.dart
  packages/devtools_app/lib/src/shared/primitives/simple_items.dart
  packages/devtools_app/lib/src/shared/screen.dart
  packages/devtools_app/lib/src/shared/utils.dart
  packages/devtools_app/test/memory/framework/memory_screen_test.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
Labels: autosubmit, release-notes-not-required

#7548 Serve DevTools extensions from pub cache instead of copying assets.
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/devtools_extensions.dart
  packages/devtools_shared/lib/devtools_extensions_io.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/lib/src/server/handlers/_general.dart
  packages/devtools_shared/test/extensions/extension_manager_test.dart
  packages/devtools_shared/test/server/deeplink_api_test.dart
  packages/devtools_shared/test/server/dtd_api_test.dart
  packages/devtools_shared/test/server/general_api_test.dart
Labels: release-notes-not-required

#7558 Fix issue with io dependencies
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/devtools_extensions.dart
  packages/devtools_shared/lib/devtools_extensions_io.dart
  packages/devtools_shared/lib/src/extensions/constants.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/utils/retry_test.dart
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#7560 Clean up `devtools_test` versioning
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
  tool/lib/commands/update_version.dart
Labels: release-notes-not-required

#7565 Refactor extensions manager code
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
Labels: release-notes-not-required

#7561 Cleanup not needed stream processing.
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_pane_controller.dart
  packages/devtools_app/test/memory/framework/memory_service_test.dart
Labels: release-notes-not-required

#7564 Return available extensions if any were successfully served
  packages/devtools_shared/lib/src/server/handlers/_devtools_extensions.dart
  packages/devtools_shared/test/helpers.dart
  packages/devtools_shared/test/server/devtools_extensions_api_test.dart
  packages/devtools_shared/test/utils/file_utils_test.dart
Labels: release-notes-not-required

#7568 Add testing for `apiExtensionEnabledState`
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/extensions/extension_enablement.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/server/devtools_extensions_api_test.dart
Labels: release-notes-not-required

#7572 Reorganize chart pane controller code and prepare structure for offline mode.
  packages/devtools_app/lib/src/screens/memory/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/framework/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/framework/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/offline_data/offline_data.dart
  packages/devtools_app/lib/src/screens/memory/framework/screen_body.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/memory_tracker.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/data/primitives.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/controller/control_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/primary_controls.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/secondary_controls.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/diff_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/profile_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/class_filter.dart
  packages/devtools_app/lib/src/screens/memory/shared/primitives/memory_timeline.dart
  packages/devtools_app/lib/src/shared/charts/chart_controller.dart
  packages/devtools_app/test/memory/control/settings_dialog_test.dart
  packages/devtools_app/test/memory/diff/widgets/diff_pane_test.dart
  packages/devtools_app/test/memory/framework/memory_controller_test.dart
  packages/devtools_app/test/memory/framework/memory_screen_test.dart
  packages/devtools_app/test/memory/framework/memory_service_test.dart
  packages/devtools_app/test/memory/profile/allocation_profile_table_view_test.dart
  packages/devtools_app/test/memory/tracing/tracing_view_test.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
  packages/devtools_app/test/test_infra/scenes/memory/diff_snapshot.dart
  packages/devtools_app/test/test_infra/scenes/scene_test_extensions.dart
Labels: autosubmit, release-notes-not-required

#7583 Add utility extension methods on `Completer`: `safeComplete` and `safeCompleteError`
  packages/devtools_app/integration_test/test/live_connection/service_connection_test.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
  packages/devtools_app/test/legacy_integration_tests/integration.dart
  packages/devtools_app_shared/lib/src/service/isolate_state.dart
  packages/devtools_app_shared/lib/src/service/service_extension_manager.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/devtools_shared.dart
  packages/devtools_shared/lib/src/service/service.dart
  packages/devtools_shared/lib/src/utils/utils.dart
  packages/devtools_shared/test/utils/utils_test.dart
Labels: release-notes-not-required

#7584 Rename serialization methods in DevTools to meet recommended standard.
  packages/devtools_app/lib/src/example/conditional_screen.dart
  packages/devtools_app/lib/src/screens/debugger/span_parser.dart
  packages/devtools_app/lib/src/screens/memory/framework/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/offline_data/offline_data.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/diff_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/profile_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/class_filter.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/enhance_tracing/enhance_tracing_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frame_model.dart
  packages/devtools_app/lib/src/screens/performance/panes/raster_stats/raster_stats_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/raster_stats/raster_stats_model.dart
  packages/devtools_app/lib/src/screens/performance/panes/rebuild_stats/rebuild_stats_model.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_model.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_service_private_extensions.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/offline_data.dart
  packages/devtools_app/lib/src/shared/survey.dart
  packages/devtools_app/test/cpu_profiler/cpu_profile_model_test.dart
  packages/devtools_app/test/cpu_profiler/cpu_profile_transformer_test.dart
  packages/devtools_app/test/cpu_profiler/cpu_profiler_controller_test.dart
  packages/devtools_app/test/cpu_profiler/cpu_profiler_test.dart
  packages/devtools_app/test/cpu_profiler/method_table/method_table_controller_test.dart
  packages/devtools_app/test/cpu_profiler/method_table/method_table_test.dart
  packages/devtools_app/test/performance/flutter_frames/flutter_frames_chart_test.dart
  packages/devtools_app/test/performance/performance_model_test.dart
  packages/devtools_app/test/performance/raster_stats/raster_stats_controller_test.dart
  packages/devtools_app/test/performance/raster_stats/raster_stats_model_test.dart
  packages/devtools_app/test/performance/timeline_events/timeline_events_controller_test.dart
  packages/devtools_app/test/shared/flame_chart_test.dart
  packages/devtools_app/test/shared/survey_test.dart
  packages/devtools_app/test/shared/widget_rebuild_counts_test.dart
  packages/devtools_app/test/test_infra/test_data/performance/sample_performance_data.dart
  packages/devtools_shared/lib/src/test/integration_test_runner.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required

#7588 Fix class filter.
  packages/devtools_app/lib/src/screens/memory/shared/heap/class_filter.dart
  packages/devtools_app/test/memory/shared/heap/class_filter_test.dart
Labels: release-notes-not-required

#7587 Don't minify stack traces when building in debug mode
  tool/lib/commands/build.dart
Labels: release-notes-not-required

#7590 Reorganize code.
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_connection.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_pane_controller.dart
Labels: release-notes-not-required

#7597 Upgrade vm_service
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: autosubmit

#7589 Skip serialization in case of in-process data passing.
  packages/devtools_app/lib/src/screens/memory/framework/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/control/widgets/secondary_controls.dart
Labels: autosubmit, release-notes-not-required

#7600 Fix issue with `dart_foo` extension configuration
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo/extension/devtools/.pubignore
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo/extension/devtools/config.yaml
Labels: release-notes-not-required

#7570 DevToolsExtensionConfig doc updates and breaking changes.
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/server/_extensions_api.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/test_infra/test_data/extensions.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/bin/_validate.dart
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/lib/src/server/handlers/_devtools_extensions.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/extensions/extension_model_test.dart
  packages/devtools_shared/test/server/devtools_extensions_api_test.dart
Labels: release-notes-not-required

#7175 Delete `rootPackages` and all the code that depends on it
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/test/inspector/inspector_service_test.dart
Labels: release-notes-not-required

#7602 Modify DevToolsExtensionConfig model to handle static extensions
  packages/devtools_app/integration_test/test/live_connection/devtools_extensions_test.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/server/_dtd_api.dart
  packages/devtools_app/lib/src/shared/server/_extensions_api.dart
  packages/devtools_app/test/test_infra/test_data/extensions.dart
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo/extension/devtools/config.yaml
  packages/devtools_extensions/extension_config_spec.md
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/extensions/constants.dart
  packages/devtools_shared/lib/src/extensions/extension_enablement.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/test/extensions/extension_enablement_test.dart
  packages/devtools_shared/test/extensions/extension_model_test.dart
Labels: release-notes-not-required

#7603 Remove todos.
  packages/devtools_app/lib/src/screens/memory/framework/offline_data/offline_data.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/class_filter.dart
Labels: release-notes-not-required

#7609 Refactor chart data.
  packages/devtools_app/lib/src/screens/memory/framework/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/DEPENDENCIES.md
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_data.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/interval_dropdown.dart
  packages/devtools_app/lib/src/screens/memory/shared/primitives/memory_timeline.dart
  packages/devtools_app/test/shared/json_to_service_cache_test.dart
  packages/devtools_app/test/test_infra/scenes/memory/default.dart
Labels: autosubmit, release-notes-not-required

#7633 Upgrade vm_service.
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: autosubmit

#7627 Move GCStats.
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/model.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/profile_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_service_private_extensions.dart
  packages/devtools_app/lib/src/shared/memory/gc_stats.dart
  packages/devtools_app/test/memory/profile/allocation_profile_table_view_test.dart
Labels: release-notes-not-required

#7625 Create `StubDevToolsExtensions` class for use in debug and in tests
  packages/devtools_app/benchmark/web_bundle_size_test.dart
  packages/devtools_app/integration_test/test/live_connection/devtools_extensions_test.dart
  packages/devtools_app/lib/src/extensions/extension_settings.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/globals.dart
  packages/devtools_app/test/extensions/extension_analytics_test.dart
  packages/devtools_app/test/extensions/extension_screen_test.dart
  packages/devtools_app/test/extensions/extension_settings_test.dart
  packages/devtools_app/test/standalone_ui/vs_code/debug_sessions_test.dart
  packages/devtools_app/test/test_infra/goldens/extensions/settings_state_modified.png
  packages/devtools_app/test/test_infra/goldens/extensions/settings_state_none.png
  packages/devtools_app/test/test_infra/test_data/extensions.dart
Labels: release-notes-not-required

#7651 Refactor offline data processing to be more readable.
  packages/devtools_app/lib/src/example/conditional_screen.dart
  packages/devtools_app/lib/src/screens/memory/framework/memory_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen_controller.dart
  packages/devtools_app/lib/src/shared/offline_data.dart
Labels: autosubmit, release-notes-not-required

#7648 Clean up framework initialization and dispose
  packages/devtools_app/lib/initialization.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/framework_initialize.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/dtd_manager.dart
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
Labels: release-notes-not-required

#7655 Refactor memory charts.
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/android_chart_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/charts/android_chart_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/charts/event_chart_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/charts/vm_chart_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/event_chart_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/vm_chart_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/legend.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/memory_android_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/memory_chart.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/memory_events_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/memory_vm_chart.dart
  packages/devtools_app/lib/src/screens/memory/shared/primitives/memory_timeline.dart
  packages/devtools_app/macos/Runner/AppDelegate.swift
  packages/devtools_app/test/memory/framework/memory_screen_test.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_app/lib/overflow_errors.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_error_app/lib/main.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_error_app/lib/missing_material_error.dart
  packages/devtools_app/test/test_infra/goldens/integration_animated_physical_model_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_errors_1_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_errors_2_error_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_richtext_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_scaffold_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center_details_tree.png
Labels: release-notes-not-required

#7660 Move the `DTDConnectionInfo` typedef to a different library
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/devtools_shared.dart
  packages/devtools_shared/lib/src/common.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/pubspec.yaml
Labels: release-notes-not-required

#7670 Prepare for release 2.35.0
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required

#7675 Fixes to the release-helper script and add better support for development
  tool/lib/commands/release_helper.dart
Labels: release-notes-not-required

#7676 Send `timing`, `screen`, `impression`, and `exception` events through unified_analytics
  packages/devtools_app/lib/src/shared/analytics/_analytics_stub.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
Labels: release-notes-not-required
