Repository flutter/devtools, pull requests merged in 2024-03, with the labels that each got.

#7308 Refactor some `devtools_shared` code
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/test/primitives/utils_test.dart
  packages/devtools_app/test/test_infra/goldens/instance_viewer/edit.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty1.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty2.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_selected_class.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_three_snapshots1.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_three_snapshots2.png
  packages/devtools_app_shared/lib/src/ui/flex_split_column.dart
  packages/devtools_app_shared/lib/src/ui/split.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/devtools_shared.dart
  packages/devtools_shared/lib/src/server/handlers/_deeplink.dart
  packages/devtools_shared/lib/src/server/handlers/_devtools_extensions.dart
  packages/devtools_shared/lib/src/server/handlers/_dtd.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/lib/src/utils/file_utils.dart
  packages/devtools_shared/test/fakes.dart
  packages/devtools_shared/test/server/deeplink_api_test.dart
  packages/devtools_shared/test/server/dtd_api_test.dart
  packages/devtools_shared/test/server/server_api_test.dart
  packages/devtools_shared/test/utils/file_utils_test.dart
Labels: release-notes-not-required

#7294 Revert "Revert "Rename a server api method and cleanup a TODO""
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/lib/src/shared/server/server.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/server/handlers/_deeplink.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#7322 Add a 'fatal-infos' argument to the `devtools_tool analyze` command
  tool/flutter_customer_tests/analyze.sh
  tool/lib/commands/analyze.dart
  tool/lib/commands/build.dart
  tool/lib/commands/fix_goldens.dart
  tool/lib/commands/generate_code.dart
  tool/lib/commands/pub_get.dart
  tool/lib/commands/release_helper.dart
  tool/lib/commands/rollback.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/update_dart_sdk_deps.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/commands/update_perfetto.dart
  tool/lib/commands/update_version.dart
Labels: release-notes-not-required

#7324 Don't negate fatal infos flag
  tool/lib/commands/analyze.dart
Labels: release-notes-not-required

#7328 Rename `devtools_app_shared`'s `Split` to `SplitPane`
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/screens/app_size/app_size_screen.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_screen.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/diff_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/class_details/class_details.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_view.dart
  packages/devtools_app/lib/src/screens/memory/panes/tracing/tracing_view.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/lib/src/screens/performance/panes/raster_stats/raster_stats.dart
  packages/devtools_app/lib/src/screens/profiler/panes/method_table/method_table.dart
  packages/devtools_app/lib/src/screens/provider/provider_screen.dart
  packages/devtools_app/lib/src/screens/vm_developer/isolate_statistics/isolate_statistics_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_inspector_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_code_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_instance_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_object_pool_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_common_widgets.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/app_size/app_size_screen_test.dart
  packages/devtools_app/test/network/network_profiler_test.dart
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center.png
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code_mock_editor.dart
  packages/devtools_app/test/vm_developer/object_inspector/object_inspector_view_test.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/example/ui/split_example.dart
  packages/devtools_app_shared/lib/src/ui/flex_split_column.dart
  packages/devtools_app_shared/lib/src/ui/split_pane.dart
  packages/devtools_app_shared/lib/ui.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_app_shared/test/ui/flex_split_column_test.dart
  packages/devtools_app_shared/test/ui/split_pane_test.dart
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/integration_test/test/simulated_environment_test.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required

#7347 [deep link] Support adding Local fingerprint
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_services.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7291 Add a DevTools server API to notify when a vm service connection changes
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/shared/framework_controller.dart
  packages/devtools_app/lib/src/shared/server/server.dart
  packages/devtools_app/lib/src/shared/utils.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/service_manager.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/connection_ui/_vm_service_connect.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/server/handlers/_dtd.dart
  packages/devtools_shared/lib/src/server/handlers/_general.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/helpers.dart
  packages/devtools_shared/test/server/dtd_api_test.dart
  packages/devtools_shared/test/server/general_api_test.dart
  packages/devtools_test/lib/src/mocks/fake_service_manager.dart
  tool/ci/package_tests.sh
Labels: release-notes-not-required

#7109 [deep link]Add intent filter checks to the android app links
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/lib/src/deeplink/app_link_settings.dart
Labels: release-notes-not-required

#7335 Compile release build of DevTools with default dart2js optimizations
  tool/build_release.sh
  tool/lib/commands/build.dart
Labels: release-notes-not-required

#7357 Documentation and cleanup for offline mode
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/example/conditional_screen.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen_controller.dart
  packages/devtools_app/lib/src/shared/offline_mode.dart
Labels: release-notes-not-required

#7354 Fix checkbox alignment
  packages/devtools_app/lib/src/shared/common_widgets.dart
Labels: release-notes-not-required

#7358 Reuse logic to show disconnected screen body
  packages/devtools_app/lib/src/example/conditional_screen.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/lib/src/framework/scaffold.dart
  packages/devtools_app/lib/src/screens/app_size/app_size_screen.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_screen.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen.dart
  packages/devtools_app/lib/src/screens/memory/framework/memory_screen.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen.dart
  packages/devtools_app/lib/src/screens/provider/provider_screen.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_tools_screen.dart
  packages/devtools_app/lib/src/shared/primitives/trees.dart
  packages/devtools_app/lib/src/shared/screen.dart
  packages/devtools_app/test/shared/scaffold_debugger_test.dart
  packages/devtools_app/test/shared/scaffold_debugging_controls_test.dart
  packages/devtools_app/test/shared/scaffold_no_app_test.dart
  packages/devtools_app/test/shared/scaffold_profile_test.dart
  packages/devtools_app/test/shared/scaffold_test.dart
Labels: release-notes-not-required

#6942 Fix a skipped test in inspector_service_test (was a false positive)
  packages/devtools_app/test/inspector/inspector_service_test.dart
  packages/devtools_app/test/test_infra/goldens/inspector_service_details_tree.txt
  packages/devtools_app/test/test_infra/goldens/inspector_service_text_details_tree_v2.txt
  packages/devtools_app/test/test_infra/goldens/inspector_service_text_details_tree_v3.txt
  packages/devtools_app/test/test_infra/goldens/inspector_service_text_details_tree_v4.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_controller_details_tree_scaffold.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_controller_details_tree_scaffold_expanded.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_controller_details_tree_scaffold_with_styles.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_controller_details_tree_scrolled_to_center.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_controller_initial_tree_with_styles.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_controller_selection_with_styles.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_controller_text_details_tree.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_controller_text_details_tree_richtext_selected.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_controller_text_details_tree_with_styles.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_service_details_tree.txt
  packages/devtools_app/test/test_infra/goldens_stable/inspector_service_text_details_tree.txt
  packages/devtools_app/test/test_infra/goldens_stable/logging_controller_material_error.txt
  packages/devtools_app/test/test_infra/goldens_stable/logging_controller_navigation.txt
  packages/devtools_app/test/test_infra/goldens_stable/logging_controller_overflow_error.txt
  packages/devtools_app/test/test_infra/matchers/matchers.dart
Labels: release-notes-not-required

#7362 Reorganize code.
  packages/devtools_app/lib/src/screens/memory/panes/diff/data/classes_diff.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/classes_table_diff.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/instances.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/heap.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/model.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/sampler.dart
  packages/devtools_app/lib/src/shared/memory/classes.dart
  packages/devtools_app/lib/src/shared/memory/retainers.dart
  packages/devtools_app/test/memory/diff/controller/heap_diff_test.dart
  packages/devtools_app/test/memory/shared/heap/heap_analyzer_golden_test.dart
  packages/devtools_app/test/memory/shared/heap/heap_analyzer_test.dart
  packages/devtools_app/test/memory/shared/heap/heap_test.dart
Labels: release-notes-not-required

#7368 Refactor preferences.dart
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/initialization.dart
  packages/devtools_app/lib/src/shared/globals.dart
  packages/devtools_app/lib/src/shared/preferences/_extension_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_inspector_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_memory_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_performance_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/preferences.dart
Labels: release-notes-not-required

#7374 Allow for null responses from `ServerConnectionStorage.getValue`
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_web.dart
  packages/devtools_app/lib/src/shared/server/server_api_client.dart
Labels: release-notes-not-required

#7379 [deep link] Add a code snippet to path check
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7380 [Deep link] update fingerprint UI
  packages/devtools_app/benchmark/web_bundle_size_test.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_services.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7350 [Deep link] Use serviceConnection.rootPackageDirectoryForMainIsolate to get the project path
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/select_project_view.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
Labels: release-notes-not-required

#7390 [deep link] For domain errors, split _AssetLinksJsonFileIssues and _HostingIssues
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7386 [deep link] Fix a runtime json type error in deep link tab
  packages/devtools_app/lib/src/shared/server/_deep_links_api.dart
Labels: release-notes-not-required

#7394 [deep link] Updating Domain check UI
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: autosubmit, release-notes-not-required

#7297 Change Release Note template url so it's url is ready for the flutter…
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/helpers/release_notes_template.md
Labels: release-notes-not-required

#7367 Fix JsonViewer auto closing, and add SelectionArea to info tabs
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: autosubmit

#7404 Fixing typos
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/shared/offline_mode.dart
Labels: release-notes-not-required

#7406 Refactor and cleanup byte utilities
  packages/devtools_app/lib/src/screens/app_size/app_size_table.dart
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/memory_charts.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/class_details/paths.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/classes_table_single.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_list.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/profile_view.dart
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
  packages/devtools_app/lib/src/screens/vm_developer/isolate_statistics/isolate_statistics_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_common_widgets.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_statistics/vm_statistics_view.dart
  packages/devtools_app/lib/src/shared/charts/treemap.dart
  packages/devtools_app/lib/src/shared/primitives/byte_utils.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/lib/src/shared/table/table_data.dart
  packages/devtools_app/test/memory/profile/allocation_profile_table_view_test.dart
  packages/devtools_app/test/primitives/byte_utils_test.dart
  packages/devtools_app/test/primitives/utils_test.dart
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_except_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_scene_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_showAll_diff.png
  packages/devtools_app/test/test_infra/goldens/treemap_sizes.png
  packages/devtools_app/test/vm_developer/object_inspector/vm_class_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_developer_common_widgets_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_library_display_test.dart
  packages/devtools_app/test/vm_developer/object_inspector/vm_script_display_test.dart
Labels: release-notes-not-required

#7407 [deep link] Update path check UI according to figma changes, and extract some duplicated code.
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_services.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7411 Adding missing fingerprint typo fix
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
Labels: release-notes-not-required

#7412 Dependency bumps for devtools_app_shared and devtools_shared
  packages/devtools_app/lib/src/framework/app_bar.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code_mock_editor.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required

#7403 Store perfetto trace binaries in ring buffer to prevent OOMs
  packages/.vscode/launch.json
  packages/devtools_app/integration_test/test/live_connection/performance_screen_event_recording_test.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/perfetto_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/tracing/model.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_event_processor.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/shared/primitives/byte_utils.dart
  packages/devtools_app/lib/src/shared/routing.dart
  packages/devtools_app/test/performance/timeline_events/perfetto/tracing_model_test.dart
  packages/devtools_app/test/performance/timeline_events/timeline_event_processor_test.dart
  packages/devtools_app/test/performance/timeline_events/timeline_events_controller_test.dart
  packages/devtools_app/test/primitives/byte_utils_test.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/vs_code_mock_editor.dart
Labels: release-notes-not-required

#7417 Update simulated devtools extension environment help dialogs
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/connection_ui/_dtd_connect.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/connection_ui/_vm_service_connect.dart
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required

#7409 [deep link] Update `initiallyExpanded` for some tiles
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7408 [deep link] Fix an issue that selected linkdata is not highlighted in domain view and path view
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
Labels: release-notes-not-required

#7433 [deep link] Add an app check that manifest file should have deeplinkingFlagEnabled
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7442 [deep link] update expansion tiles
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7440 Stop failing when disconnected.
  packages/devtools_app/lib/src/screens/memory/panes/tracing/tracing_pane_controller.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: autosubmit

#7443 [deep link] some strings, colors, style updates
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/select_project_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/lib/src/shared/ui/colors.dart
Labels: release-notes-not-required

#7432 [deep link] Fix the issue that table is not updated when user change sorting option.
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/shared/table/_flat_table.dart
  packages/devtools_app/lib/src/shared/table/table_data.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
Labels: release-notes-not-required

#7441 [deep link] Update `recheck` button
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7449 Remove feature flag from export snapshot.
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_list.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/more_debugging_options.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_analysis.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/performance/tabbed_performance_view.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/test_infra/scenes/performance/default.dart
Labels: autosubmit

#7455 Update flutter-candidate.txt
  flutter-candidate.txt
Labels: autosubmit

#7452 [deep link] Fix double borders, height, fonts
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
Labels: release-notes-not-required

#7458 Update flutter-candidate.txt
  flutter-candidate.txt
Labels: autosubmit

#7454 [deep links] update strings and fix typos
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/select_project_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
Labels: release-notes-not-required

#7457 Export on mac.
  packages/devtools_app/lib/src/shared/config_specific/file/_file_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/file/_file_web.dart
  packages/devtools_app/lib/src/shared/config_specific/file/file.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_desktop.dart
Labels: autosubmit, release-notes-not-required

#7431 Use DTD project roots instead of workspace roots for Deep links tool
  packages/devtools_app/lib/src/screens/deep_link_validation/select_project_view.dart
  packages/devtools_app/lib/src/shared/directory_picker.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
  packages/devtools_app/test/primitives/utils_test.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/service/dtd_manager.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/pubspec.yaml
Labels: release-notes-not-required

#7459 Set flush to true.
  packages/devtools_app/lib/src/shared/config_specific/file/_file_desktop.dart
  packages/devtools_app/test_driver/integration_test.dart
Labels: release-notes-not-required

#7460 Organize files in deep link folder
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/root_selector.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/select_project_view.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
Labels: release-notes-not-required

#7462 Reuse class filter between diff and profile tabs.
  packages/devtools_app/lib/src/screens/memory/framework/connected/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/diff_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/profile/profile_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/shared/heap/class_filter.dart
  packages/devtools_app/macos/Runner.xcodeproj/project.pbxproj
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/memory/diff/controller/memory_footprint_test.dart
  packages/devtools_app/test/memory/framework/memory_controller_test.dart
  packages/devtools_app/test/memory/framework/memory_screen_test.dart
  packages/devtools_app/test/memory/framework/memory_service_test.dart
  packages/devtools_app/test/memory/memory_footprint_test.dart
Labels: autosubmit

#7466 Fix script path detection.
  tool/lib/utils.dart
Labels: autosubmit, release-notes-not-required

#7461 Fix bug with selecting flutter frames
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_event_processor.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
Labels: release-notes-not-required

#7463 Add a loading overlay when Perfetto UI is proecessing trace
  packages/devtools_app/lib/src/screens/performance/panes/controls/performance_controls.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_analysis.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_hints.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_view.dart
  packages/devtools_app/lib/src/screens/performance/tabbed_performance_view.dart
  packages/devtools_app/lib/src/shared/future_work_tracker.dart
  packages/devtools_app/test/performance/frame_analysis/frame_analysis_test.dart
  packages/devtools_app/test/performance/frame_analysis/frame_hints_test.dart
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
Labels: release-notes-not-required

#7474 Fix file system tech debt
  packages/devtools_app/lib/src/shared/config_specific/file/_file_web.dart
  packages/devtools_app/lib/src/shared/config_specific/file/file.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/_file_desktop.dart
Labels: release-notes-not-required

#7468 Prepare for release.
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#7478 Only display 'Performance Settings' for Flutter applications
  packages/devtools_app/lib/src/screens/performance/panes/controls/performance_controls.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/performance_settings.dart
  packages/devtools_app/test/performance/controls/performance_controls_test.dart
Labels: release-notes-not-required

#7475 Add GA timing for processing timeline events
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_performance_constants.dart
Labels: release-notes-not-required

#7485 Compile devtools with `release` mode (no dart2js optimization set)
  tool/build_release.sh
  tool/lib/commands/build.dart
Labels: release-notes-not-required

#7490 Revert version to 2.34.1
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_test/pubspec.yaml
Labels: release-notes-not-required

#7493 Show reachable size in list.
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/item_controller.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/helpers/release_notes_template.md
Labels: autosubmit

#7497 [deep link] Update googlePlayFingerprintsAvailability key
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_services.dart
Labels: release-notes-not-required

#7495 Update release notes readme and send analytics for theme
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/preferences/preferences.dart
  packages/devtools_app/release_notes/README.md
Labels: release-notes-not-required

#7498 Release notes documentation.
  CONTRIBUTING.md
  packages/devtools_app/release_notes/README.md
  packages/devtools_app/release_notes/helpers/release_notes_template.md
Labels: autosubmit
