Repository flutter/devtools, pull requests merged in 2024-12, with the labels that each got.

#8580 Update to latest flutter.
  flutter-candidate.txt
  packages/devtools_app/test/inspector_v2/inspector_integration_test.dart
  packages/devtools_app/test/test_infra/goldens/memory/load_offline_data_profile_tab.png
Labels: release-notes-not-required

#8578 Temporarily disable `Code` based profiling when VM Developer Mode is enabled
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
Labels: release-notes-not-required

#8586 Skip flaky eval integration tests for test registry
  packages/devtools_app/test/shared/eval_integration_test.dart
Labels: release-notes-not-required

#8573 Stager scene for Property Editor
  .vscode/launch.json
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_property_editor_sidebar_constants.dart
  packages/devtools_app/lib/src/standalone_ui/standalone_screen.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/property_editor_panel.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/editor_sidebar.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/mock_editor_widget.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/property_editor_sidebar.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/shared/common_ui.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/shared/utils.dart
Labels: release-notes-not-required

#8592 Remove `package:codicon` dependency
  packages/devtools_app/icons/material_symbols/LICENSE
  packages/devtools_app/icons/material_symbols/resume.png
  packages/devtools_app/icons/material_symbols/step_into.png
  packages/devtools_app/icons/material_symbols/step_out.png
  packages/devtools_app/icons/material_symbols/step_over.png
  packages/devtools_app/lib/src/screens/debugger/controls.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/screens/logging/metadata.dart
  packages/devtools_app/lib/src/shared/ui/common_widgets.dart
  packages/devtools_app/lib/src/shared/ui/filter.dart
  packages/devtools_app/lib/src/shared/ui/icons.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/shared.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/screens/debugger/debugger_screen_paused_test.dart
  packages/devtools_app/test/screens/debugger/debugger_screen_test.dart
  packages/devtools_app/test/test_infra/goldens/codeview_scrollbars.png
  packages/devtools_app/test/test_infra/goldens/integration_animated_physical_model_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_richtext_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_scaffold_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_select_center_details_tree.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_implementation_widgets_hidden.png
  packages/devtools_app/test/test_infra/goldens/memory/load_offline_data_profile_tab.png
  packages/devtools_app/test/test_infra/goldens/memory/load_offline_data_trace_tab.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty1.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty2.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_custom.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_except.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_only.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_filter_dialog_showAll.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_selected_class.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_custom_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_custom_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_except_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_except_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_only_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_only_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_scene_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_scene_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_showAll_diff.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_snapshot_showAll_single.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_three_snapshots1.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_three_snapshots2.png
  packages/devtools_app/test/test_infra/goldens/shared/disconnect_observer_disconnected.png
  packages/devtools_app/test/test_infra/utils/debugger_utils.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/ui/buttons.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
  packages/devtools_app_shared/lib/src/ui/icons.dart
  packages/devtools_app_shared/lib/ui.dart
  packages/devtools_test/lib/src/helpers/actions.dart
Labels: release-notes-not-required

#8574 Verify that benchmark tests meet expected performance thresholds
  .github/workflows/build.yaml
  packages/devtools_app/benchmark/README.md
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
Labels: release-notes-not-required

#8597 Check in devtools_options.yaml at the repo level
  devtools_options.yaml
  packages/devtools_app/devtools_options.yaml
Labels: autosubmit

#8599 remove the dep on package:ansicolor
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/screens/debugger/debugger_console_test.dart
  packages/devtools_app/test/screens/logging/logging_screen_data_test.dart
  packages/devtools_app/test/shared/ansi_up_test.dart
  packages/devtools_app/test/test_infra/fixtures/color_console_output_app.dart
  packages/devtools_app/test/test_infra/utils/ansi.dart
Labels: release-notes-not-required

#8601 remove and inline the use of package:ansi_up
  packages/devtools_app/lib/src/screens/logging/_message_column.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_instance_display.dart
  packages/devtools_app/lib/src/shared/console/console.dart
  packages/devtools_app/lib/src/shared/console/widgets/display_provider.dart
  packages/devtools_app/lib/src/shared/primitives/ansi_utils.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/shared/ansi_output_test.dart
Labels: release-notes-not-required

#8595 Delete `codicon` package from `third_party`
  packages/devtools_app/.gitignore
  third_party/packages/codicon/CHANGELOG.md
  third_party/packages/codicon/LICENSE
  third_party/packages/codicon/README.md
  third_party/packages/codicon/analysis_options.yaml
  third_party/packages/codicon/lib/codicon.dart
  third_party/packages/codicon/lib/font/codicon.ttf
  third_party/packages/codicon/pubspec.yaml
Labels: release-notes-not-required

#8607 Remove the `shared_preferences` dependency from `devtools_app`
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/macos/Flutter/GeneratedPluginRegistrant.swift
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/framework/home_screen_test.dart
Labels: release-notes-not-required

#8605 Delete `ansi_up` from `third_party`
  third_party/packages/ansi_up/CHANGELOG.md
  third_party/packages/ansi_up/LICENSE
  third_party/packages/ansi_up/README.md
  third_party/packages/ansi_up/analysis_options.yaml
  third_party/packages/ansi_up/lib/ansi_up.dart
  third_party/packages/ansi_up/pubspec.yaml
Labels: release-notes-not-required

#8608 Remove dependency on `package:clock`
  packages/devtools_app/lib/src/shared/managers/survey.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/shared/managers/survey_test.dart
Labels: release-notes-not-required

#8600 Register the Property Editor as a standalone screen
  packages/devtools_app/lib/src/standalone_ui/standalone_screen.dart
Labels: autosubmit, release-notes-not-required

#8613 Migrate to flutter_lints v5
  packages/devtools_app/lib/src/screens/debugger/program_explorer.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/tracing/model.dart
  packages/devtools_app/lib/src/shared/charts/treemap.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_web.dart
  packages/devtools_app/lib/src/shared/diagnostics/diagnostics_node.dart
  packages/devtools_app/lib/src/shared/offline/offline_data.dart
  packages/devtools_app/lib/src/shared/primitives/enum_utils.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/example/utils/list_example.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/lib/src/memory/memory_json.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_test/pubspec.yaml
  pubspec.yaml
  tool/lib/license_utils.dart
  tool/lib/utils.dart
  tool/pubspec.yaml
Labels: release-notes-not-required

#8615 Replace `Uri.copyWith` extension method with built-in `replace` method
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/shared/framework/routing.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
Labels: release-notes-not-required

#8614 Replace `EnumUtils` with extension methods from SDK
  packages/devtools_app/lib/src/screens/inspector/inspector_data_models.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_data_models.dart
  packages/devtools_app/lib/src/shared/diagnostics/diagnostics_node.dart
  packages/devtools_app/lib/src/shared/primitives/enum_utils.dart
  packages/devtools_app/test/shared/primitives/enum_utils_test.dart
Labels: release-notes-not-required

#8617 Fix analytics for hot reload and hot restart actions.
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
Labels: release-notes-not-required

#8590 [Inspector V2] Add initial test case to handle live-reloads after code edits
  packages/devtools_app/test/screens/inspector_v2/inspector_integration_test.dart
  packages/devtools_app/test/test_infra/flutter_test_environment.dart
Labels: release-notes-not-required

#8598 Connect the Property Editor to DTD
  packages/devtools_app/lib/src/service/editor/api_classes.dart
  packages/devtools_app/lib/src/service/editor/editor_client.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_panel.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/lib/src/standalone_ui/standalone_screen.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/property_editor_sidebar.dart
Labels: release-notes-not-required

#8620 Remove unnecessary logging type prefix
  packages/devtools_app/lib/src/framework/release_notes.dart
Labels: release-notes-not-required

#8622 Auto-refresh the widget tree on navigation events
  packages/devtools_app/lib/src/screens/inspector_shared/inspector_settings_dialog.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_controller.dart
Labels: release-notes-not-required

#8621 Support connecting debug mode DevTools app to DevTools server
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_web.dart
  packages/devtools_app/lib/src/shared/preferences/preferences.dart
  packages/devtools_app/lib/src/shared/server/server.dart
  packages/devtools_app/lib/src/shared/server/server_api_client.dart
  packages/devtools_app/web/flutter_bootstrap.js
  tool/lib/commands/serve.dart
  tool/lib/utils.dart
Labels: release-notes-not-required

#8630 Add a `dt run` command with better stdout handling
  CONTRIBUTING.md
  packages/devtools_app/lib/src/shared/preferences/preferences.dart
  packages/devtools_app/lib/src/shared/server/server.dart
  tool/lib/commands/build.dart
  tool/lib/commands/run.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/shared.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/utils.dart
Labels: autosubmit, release-notes-not-required

#8631 Fix property editor tests
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
Labels: release-notes-not-required

#8636 Upgrade Flutter version
  flutter-candidate.txt
  packages/devtools_app/benchmark/web_bundle_size_test.dart
Labels: release-notes-not-required

#8632 Can send edit requests from the Property Editor
  packages/devtools_app/lib/src/service/editor/api_classes.dart
  packages/devtools_app/lib/src/service/editor/editor_client.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
Labels: release-notes-not-required

#8640 Remove uses of deprecated `--web-renderer` option
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/bin/_build_and_copy.dart
  packages/devtools_extensions/pubspec.yaml
  tool/lib/commands/build.dart
Labels: release-notes-not-required

#8641 Remove unused analytics code.
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
Labels: release-notes-not-required

#8638 Serve command still works with `--machine` flag
  tool/lib/commands/serve.dart
Labels: release-notes-not-required

#8645 [Inspector V2] Change selected node heuristic after navigation event triggering a tree refresh
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_controller.dart
Labels: release-notes-not-required

#8647 [Inspector V2] Hide implementation widgets by default
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_controller.dart
  packages/devtools_app/test/screens/inspector_v2/inspector_integration_test.dart
  packages/devtools_app/test/test_infra/goldens/codeview_scrollbars.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_errors_1_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_errors_2_error_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_hideable_widget_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_hideable_widget_selected_from_search.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_implementation_widgets_collapsed.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_implementation_widgets_expanded.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_implementation_widgets_hidden.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_select_center.png
  packages/devtools_app/test/test_infra/goldens/memory/load_offline_data_profile_tab.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty1.png
  packages/devtools_app/test/test_infra/goldens/memory_diff_empty2.png
Labels: release-notes-not-required
