Repository flutter/devtools, pull requests merged in 2024-10, with the labels that each got.

#8383 Fix timeline processing for thread name change.
  flutter-candidate.txt
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
Labels: release-notes-not-required

#8379 Scroll to selected node after switching inspector screens
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_tree_controller.dart
Labels: release-notes-not-required

#8309 [deep link] Add sub checks for ios domain error - format error
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_services.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/test/deep_link_vlidation/deep_links_screen_test.dart
  packages/devtools_app/test/test_infra/test_data/deep_link/fake_responses.dart
Labels: release-notes-not-required

#8377 `DevtoolsToggleButton` and `ServiceExtensionButton` have same text color
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_errors_1_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_errors_2_error_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_hideable_widget_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_hideable_widget_selected_from_search.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_implementation_widgets_collapsed.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_implementation_widgets_expanded.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_select_center.png
  packages/devtools_app/test/test_infra/goldens/memory/load_offline_data_profile_tab.png
  packages/devtools_app_shared/lib/src/ui/buttons.dart
Labels: release-notes-not-required

#8392 Remove whitespace from build script
  tool/build_release.sh
Labels: autosubmit, release-notes-not-required

#8387 Accept themeChanged events via postMessage as well as DTD
  packages/devtools_app/lib/src/framework/theme_manager.dart
Labels: ide: vs-code, release-notes-not-required

#8391 Increase number of retries for eval test
  packages/devtools_app/integration_test/test/live_connection/eval_utils.dart
Labels: release-notes-not-required

#8177 Add android app id and ios bundle id in GA metrics
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_deep_links_constants.dart
  packages/devtools_app/lib/src/shared/analytics/metrics.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required

#8396 Make collapsible buttons in inspector controls responsive to screen size
  packages/devtools_app/lib/src/screens/inspector_shared/inspector_controls.dart
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
  packages/devtools_app/lib/src/service/service_extensions.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
Labels: release-notes-not-required

#8397 Fix delta percentage calculation for benchmark script.
  packages/devtools_app/benchmark/scripts/run_benchmarks.dart
  packages/devtools_app/benchmark/scripts/utils.dart
Labels: release-notes-not-required

#8398 Prepare for release 2.40.0
  flutter-candidate.txt
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
  tool/lib/commands/shared.dart
Labels: release-notes-not-required

#8399 Move analytics factories to constructors
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
Labels: release-notes-not-required

#8402 Fix assert firing on the Desktop build
  packages/devtools_app/lib/src/shared/preferences/preferences.dart
  packages/devtools_test/.gitignore
Labels: release-notes-not-required

#8403 Replace `devtools_tool` exe with shorthand `dt`
  .github/workflows/build.yaml
  .github/workflows/daily-dev-bump.yaml
  BETA_TESTING.md
  CONTRIBUTING.md
  TESTING.md
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/release_notes/README.md
  packages/devtools_test/lib/src/mocks/generated.dart
  tool/RELEASE_INSTRUCTIONS.md
  tool/bin/devtools_tool
  tool/bin/devtools_tool.bat
  tool/bin/dt
  tool/bin/dt.bat
  tool/bin/dt.dart
  tool/build_release.sh
  tool/ci/bots.sh
  tool/ci/setup.sh
  tool/flutter_customer_tests/analyze.sh
  tool/flutter_customer_tests/setup.sh
  tool/lib/commands/build.dart
  tool/lib/commands/release_helper.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/shared.dart
  tool/lib/commands/update_dart_sdk_deps.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/model.dart
  tool/lib/utils.dart
  tool/pubspec.yaml
Labels: release-notes-not-required

#8404 [Inspector V2] Persist tab when a new widget is selected
  packages/devtools_app/lib/src/screens/inspector_v2/widget_properties/properties_view.dart
Labels: release-notes-not-required

#8406 Clean up the Logging V2 metadata and controls display
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_row.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_v2.dart
Labels: release-notes-not-required

#8409 Delete unnecessary wrapper classes and further densify log display for logging v2
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/log_data.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_controller_v2.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_model.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_screen_v2.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_row.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_v2.dart
  packages/devtools_app/test/logging/logging_screen_v2/logging_model_test.dart
Labels: release-notes-not-required

#8418 Refactor logging code
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_row.dart
  packages/devtools_app/lib/src/screens/logging/metadata.dart
  packages/devtools_app/lib/src/screens/logging/shared/constants.dart
  packages/devtools_app/test/logging/logging_screen_v2/logging_table_row_test.dart
Labels: release-notes-not-required

#8320 Unskip the wasm benchmark
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
  packages/devtools_app/benchmark/scripts/dart2wasm_performance_diff.dart
  packages/devtools_app/benchmark/scripts/run_benchmarks.dart
  packages/devtools_app/benchmark/test_infra/automators/devtools_automator.dart
  packages/devtools_app/benchmark/test_infra/client/client_js.dart
  packages/devtools_app/benchmark/test_infra/client/client_shared.dart
  packages/devtools_app/benchmark/test_infra/client/client_wasm.dart
  packages/devtools_app/benchmark/test_infra/common.dart
  packages/devtools_app/benchmark/test_infra/devtools_recorder.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required

#8425 Refactor logging controls
  packages/devtools_app/lib/src/screens/logging/logging_controls.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen.dart
Labels: release-notes-not-required

#8428 Support filtering by log level in the text filter
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/logging/metadata.dart
Labels: release-notes-not-required

#8432 Create a generalized `SettingFilter` class to support filtering by any type of data
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_model.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profiler_controller.dart
  packages/devtools_app/lib/src/shared/ui/filter.dart
  packages/devtools_app/test/cpu_profiler/cpu_profiler_controller_test.dart
  packages/devtools_app/test/cpu_profiler/cpu_profiler_test.dart
  packages/devtools_app/test/logging/logging_controller_test.dart
  packages/devtools_app/test/logging/logging_screen_v2/logging_controller_v2_test.dart
  packages/devtools_app/test/logging/logging_screen_v2/logging_model_test.dart
  packages/devtools_app/test/shared/filter_test.dart
  packages/devtools_test/lib/src/mocks/generated_mocks_factories.dart
Labels: release-notes-not-required

#8435 Determine the logging split view axis by the aspect ratio
  packages/devtools_app/lib/src/screens/logging/logging_screen.dart
  packages/devtools_app/test/logging/logging_screen_test.dart
Labels: release-notes-not-required

#8438 Move the DevTools debug mode banner to the bottom right
  packages/devtools_app/lib/src/app.dart
Labels: release-notes-not-required

#8446 Store the logging details format in user preferences
  packages/devtools_app/lib/src/screens/logging/_log_details.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_logging_constants.dart
  packages/devtools_app/lib/src/shared/preferences/_logging_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/preferences.dart
  packages/devtools_app/test/shared/preferences_controller_test.dart
Labels: release-notes-not-required

#8457 Change the default log level to include everything by default
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
Labels: release-notes-not-required

#8462 Use new Dart wildcard variables
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_screen_body.dart
  packages/devtools_app/lib/src/screens/inspector_shared/inspector_controls.dart
  packages/devtools_app/lib/src/screens/inspector_shared/inspector_settings_dialog.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_screen_body.dart
  packages/devtools_app/lib/src/screens/inspector_v2/widget_details.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_row.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/widgets/chart_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/diff_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/class_details/class_details.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/class_details/path.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_control_pane.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_list.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/widgets/snapshot_view.dart
  packages/devtools_app/lib/src/screens/memory/panes/tracing/class_table.dart
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/screens/vm_developer/process_memory/process_memory_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_statistics/vm_statistics_view.dart
  packages/devtools_app/lib/src/shared/common_widgets.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/_post_message_stub.dart
  packages/devtools_app/lib/src/shared/console/console.dart
  packages/devtools_app/lib/src/shared/editable_list.dart
  packages/devtools_app/lib/src/shared/table/_table_row.dart
  packages/devtools_app/lib/src/shared/ui/filter.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/inspector/inspector_tree_test.dart
  packages/devtools_app/test/inspector/utils/inspector_tree.dart
  packages/devtools_app/test/inspector_v2/inspector_tree_test.dart
  packages/devtools_app/test/inspector_v2/utils/inspector_tree.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
  packages/devtools_app_shared/lib/src/ui/theme/ide_theme.dart
Labels: release-notes-not-required

#8463 Include query filter instructions for the standalone filter field
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/logging/logging_controls.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_model.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen_v2/logging_table_v2.dart
  packages/devtools_app/lib/src/screens/network/network_controller.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profiler.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profiler_controller.dart
  packages/devtools_app/lib/src/screens/profiler/panes/controls/cpu_profiler_controls.dart
  packages/devtools_app/lib/src/shared/ui/filter.dart
  packages/devtools_app/test/shared/filter_test.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/ui/text_field.dart
  packages/devtools_test/lib/src/mocks/generated_mocks_factories.dart
Labels: release-notes-not-required

#8464 Fix bug with local mock generation
  tool/lib/commands/generate_code.dart
Labels: release-notes-not-required

#8472 Fix bounds check error with dart2wasm -O4
  packages/devtools_app/lib/src/shared/ui/filter.dart
Labels: release-notes-not-required

#8474 Fix wasm casting error
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/logging/metadata.dart
Labels: release-notes-not-required

#8479 [Inspector V2] Implementation details remain hidden on tree refresh
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_controller.dart
  packages/devtools_app/test/inspector_v2/inspector_integration_test.dart
Labels: release-notes-not-required

#8480 [Inspector V2] Request the reduced widget tree from Flutter
  flutter-candidate.txt
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_tree_controller.dart
  packages/devtools_app/lib/src/shared/diagnostics/diagnostics_node.dart
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/macos/Runner.xcodeproj/project.pbxproj
  packages/devtools_app/test/inspector_v2/inspector_integration_test.dart
Labels: release-notes-not-required

#8488 Disable two lint rules which are being removed.
  packages/analysis_options.yaml
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
Labels: release-notes-not-required

#8499 Remove unused query filter field from filter dialog
  packages/devtools_app/lib/src/shared/ui/filter.dart
Labels: release-notes-not-required
