Repository flutter/devtools, pull requests merged in 2025-02, with the labels that each got.

#8839 optimize cpu_profile_transformer to not create intermediate lists
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_transformer.dart
Labels: release-notes-not-required

#8843 Fix licence tool include/excludes for Windows
  tool/lib/license_utils.dart
Labels: release-notes-not-required

#8847 [CQ] migrate to using `fileNameFromUri`
  packages/devtools_app/lib/src/screens/debugger/breakpoints.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_model.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/screens/debugger/file_search.dart
  packages/devtools_app/lib/src/screens/performance/panes/rebuild_stats/rebuild_stats.dart
  packages/devtools_app/lib/src/shared/console/widgets/description.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
Labels: release-notes-not-required

#8852 [PE] fix typo in `RoundedButtonGroup` class doc
  packages/devtools_app_shared/lib/src/ui/buttons.dart
Labels: release-notes-not-required

#8856 Make the tooltip for 'Load all CPU samples' more verbose
  packages/devtools_app/lib/src/screens/profiler/panes/controls/profiler_screen_controls.dart
Labels: release-notes-not-required

#8844 Normalize analytics paths for Windows
  packages/devtools_app/lib/src/shared/analytics/analytics_common.dart
  packages/devtools_app/test/shared/analytics/analytics_test.dart
Labels: autosubmit, release-notes-not-required

#8868 Make DevToolsTable.rowItemExtent non-nullable
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/shared/table/table.dart
Labels: release-notes-not-required

#8867 Add a unique key to the notifications widget so they don't get reparented
  packages/devtools_app/lib/src/framework/notifications_view.dart
Labels: release-notes-not-required

#8846 Fix some extensions + file util tests on Windows
  packages/devtools_shared/test/helpers/extension_test_manager.dart
  packages/devtools_shared/test/helpers/extension_test_manager_test.dart
  packages/devtools_shared/test/server/devtools_extensions_api_test.dart
  packages/devtools_shared/test/utils/file_utils_test.dart
Labels: release-notes-not-required

#8863 Fix broken comment references in devtools_app_shared
  packages/devtools_app_shared/example/ui/dialog_example.dart
  packages/devtools_app_shared/example/ui/split_example.dart
  packages/devtools_app_shared/lib/src/service/resolved_uri_manager.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
  packages/devtools_app_shared/lib/src/ui/flex_split_column.dart
  packages/devtools_app_shared/lib/src/utils/auto_dispose.dart
  packages/devtools_app_shared/lib/src/utils/list.dart
Labels: release-notes-not-required

#8869 Fix broken comment references in devtools_app
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/framework/initializer.dart
  packages/devtools_app/lib/src/framework/scaffold/scaffold.dart
  packages/devtools_app/lib/src/screens/app_size/app_size_controller.dart
  packages/devtools_app/lib/src/screens/debugger/span_parser.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_data_models.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_tree_controller.dart
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/ui/utils.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_data_models.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_tree_controller.dart
  packages/devtools_app/lib/src/screens/inspector_v2/layout_explorer/box/box.dart
  packages/devtools_app/lib/src/screens/inspector_v2/layout_explorer/ui/utils.dart
  packages/devtools_app/lib/src/screens/memory/framework/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/diff_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/tracing/tracing_data.dart
Labels: release-notes-not-required

#8841 [Property Editor] Can use "tab" key to submit text field inputs
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
Labels: release-notes-not-required

#8860 Use previous HTTP profile timestamps instead of DateTime.now() when requesting HTTP profiles
  packages/devtools_app/lib/src/screens/network/network_controller.dart
  packages/devtools_app/lib/src/screens/network/network_service.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
Labels: autosubmit

#8808 Inspector infers correct pub root directory for widget previews
  packages/devtools_app/lib/src/shared/preferences/_inspector_preferences.dart
  packages/devtools_app/test/shared/preferences/preferences_controller_test.dart
Labels: release-notes-not-required

#8871 Reformat NetworkRequestInspector._generateTabs to be way less indented.
  packages/devtools_app/lib/src/screens/network/network_request_inspector.dart
Labels: release-notes-not-required

#8840 [Property Editor] Add analytics to the Property Editor
  packages/devtools_app/lib/src/shared/analytics/constants/_property_editor_sidebar_constants.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_panel.dart
Labels: release-notes-not-required

#8842 [Inspector V2] Align tree connection lines to widget icons
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_tree_controller.dart
  packages/devtools_app/lib/src/shared/console/eval/inspector_tree_v2.dart
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_errors_1_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_errors_2_error_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_hideable_widget_selected.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_hideable_widget_selected_from_search.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_implementation_widgets_collapsed.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_implementation_widgets_expanded.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_implementation_widgets_hidden.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_initial_load.png
  packages/devtools_app/test/test_infra/goldens/integration_inspector_v2_select_center.png
Labels: release-notes-not-required

#8862 Avoid a few non-null assertions in inspector
  packages/devtools_app/lib/src/screens/inspector/inspector_data_models.dart
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/flex/flex.dart
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/flex/utils.dart
  packages/devtools_app/lib/src/screens/inspector/layout_explorer/ui/free_space.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_data_models.dart
  packages/devtools_app/lib/src/screens/inspector_v2/layout_explorer/flex/flex.dart
  packages/devtools_app/lib/src/screens/inspector_v2/layout_explorer/flex/utils.dart
  packages/devtools_app/lib/src/screens/inspector_v2/layout_explorer/ui/free_space.dart
  packages/devtools_app/test/screens/inspector/layout_explorer/inspector_data_models_test.dart
  packages/devtools_app/test/screens/inspector_v2/layout_explorer/inspector_data_models_test.dart
Labels: release-notes-not-required

#8864 Enable all bots on Windows
  .github/workflows/build.yaml
  .github/workflows/flutter-prep.yaml
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/test/screens/memory/diff/controller/memory_footprint_test.dart
  packages/devtools_shared/lib/src/test/integration_test_runner.dart
  tool/ci/package_tests.sh
  tool/ci/setup.sh
Labels: release-notes-not-required

#8878 make ancestorIds an iterable, avoids n^2 allocations for sets
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart
Labels: release-notes-not-required

#8874 Don't load the JsonViewer with unparsable JSON
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
Labels: release-notes-not-required

#8893 Revert "Use `-O2` optimization for DevTools wasm build."
  flutter-candidate.txt
  tool/build_release.sh
  tool/lib/commands/build.dart
Labels: release-notes-not-required

#8892 Refactor BottomUpTransformer to do less deep copying
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_transformer.dart
  packages/devtools_app/lib/src/shared/constants.dart
  packages/devtools_app/lib/src/shared/utils/profiler_utils.dart
  packages/devtools_app/test/screens/cpu_profiler/cpu_profile_transformer_test.dart
Labels: release-notes-not-required

#8619 Utilize new `wait` extension methods
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/screens/debugger/breakpoint_manager.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart
  packages/devtools_app/lib/src/screens/debugger/program_explorer_controller.dart
  packages/devtools_app/lib/src/screens/debugger/variables.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/diff_pane_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/tracing/tracing_data.dart
  packages/devtools_app/lib/src/screens/network/network_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/enhance_tracing/enhance_tracing.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/class_hierarchy_explorer_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_ic_data_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_instance_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_statistics/vm_statistics_view_controller.dart
  packages/devtools_app/lib/src/shared/console/eval/auto_complete.dart
  packages/devtools_app/lib/src/shared/console/widgets/description.dart
  packages/devtools_app/lib/src/shared/console/widgets/expandable_variable.dart
  packages/devtools_app/lib/src/shared/diagnostics/tree_builder.dart
  packages/devtools_app/lib/src/shared/diagnostics/variable_factory.dart
  packages/devtools_app/lib/src/shared/editor/editor_client.dart
  packages/devtools_app/lib/src/shared/primitives/custom_pointer_scroll_view.dart
  packages/devtools_app/lib/src/shared/ui/common_widgets.dart
  packages/devtools_app/test/test_infra/flutter_test_driver.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/editor_service/simulated_editor.dart
  packages/devtools_app_shared/lib/src/service/connected_app.dart
  packages/devtools_app_shared/lib/src/service/isolate_manager.dart
  packages/devtools_app_shared/lib/src/service/service_extension_manager.dart
  packages/devtools_app_shared/lib/src/service/service_manager.dart
  packages/devtools_app_shared/lib/src/service/service_utils.dart
  packages/devtools_shared/lib/src/server/handlers/_general.dart
  packages/devtools_shared/lib/src/test/cli_test_driver.dart
  packages/devtools_shared/lib/src/test/io_utils.dart
  packages/devtools_test/lib/src/helpers/utils.dart
Labels: release-notes-not-required

#8900 [Inspector V2] Fix bug preventing us from capturing initial load time for the V2 inspector
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_screen_body.dart
Labels: release-notes-not-required

#8891 [Property Editor] Indicate default option in dropdown input
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_types.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
Labels: release-notes-not-required

#8883 [Property Editor] Display the name and documentation for the selected widget
  packages/devtools_app/lib/src/shared/analytics/constants/_property_editor_sidebar_constants.dart
  packages/devtools_app/lib/src/shared/editor/api_classes.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/utils/utils.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/property_editor_test.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/utils_test.dart
Labels: release-notes-not-required

#8908 Use new ScreenControllers class for controller lifecycle management
  packages/devtools_app/benchmark/test_infra/automators/devtools_automator.dart
  packages/devtools_app/integration_test/test/live_connection/app_test.dart
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/screens/app_size/app_size_controller.dart
  packages/devtools_app/lib/src/screens/app_size/app_size_screen.dart
  packages/devtools_app/lib/src/screens/debugger/breakpoints.dart
  packages/devtools_app/lib/src/screens/debugger/call_stack.dart
  packages/devtools_app/lib/src/screens/debugger/codeview.dart
  packages/devtools_app/lib/src/screens/debugger/controls.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/select_project_view.dart
  packages/devtools_app/lib/src/screens/inspector_shared/inspector_screen.dart
  packages/devtools_app/lib/src/screens/inspector_shared/inspector_screen_controller.dart
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/logging/logging_controls.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen.dart
  packages/devtools_app/lib/src/screens/memory/framework/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/screen_body.dart
  packages/devtools_app/lib/src/screens/network/network_controller.dart
  packages/devtools_app/lib/src/screens/network/network_request_inspector.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/screens/performance/tabbed_performance_view.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_inspector_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_tools_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_tools_screen.dart
  packages/devtools_app/lib/src/shared/analytics/prompt.dart
  packages/devtools_app/lib/src/shared/framework/screen.dart
  packages/devtools_app/lib/src/shared/framework/screen_controllers.dart
  packages/devtools_app/lib/src/shared/globals.dart
  packages/devtools_app/lib/src/shared/offline/offline_data.dart
  packages/devtools_app/lib/src/shared/ui/search.dart
  packages/devtools_app/lib/src/shared/utils/utils.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/framework/scaffold/scaffold_debugger_test.dart
  packages/devtools_app/test/framework/scaffold/scaffold_debugging_controls_test.dart
  packages/devtools_app/test/framework/scaffold/scaffold_no_app_test.dart
  packages/devtools_app/test/framework/scaffold/scaffold_profile_test.dart
  packages/devtools_app/test/framework/scaffold/scaffold_test.dart
  packages/devtools_app/test/screens/network/network_request_inspector_test.dart
  packages/devtools_app/test/shared/framework/screen_controllers_test.dart
  packages/devtools_app/test/shared/framework/screens_test.dart
  packages/devtools_app/test/shared/primitives/utils_test.dart
  packages/devtools_test/lib/src/helpers/actions.dart
  packages/devtools_test/lib/src/helpers/wrappers.dart
Labels: release-notes-not-required

#8916 Fix a bug with screen controller initialization
  packages/devtools_app/lib/src/app.dart
Labels: release-notes-not-required

#8914 Add `DisposableController.init` method and `DisposableController.disposed` getter.
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/extensions/embedded/controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_connection.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/enhance_tracing/enhance_tracing_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/perfetto_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_inspector_view_controller.dart
  packages/devtools_app/lib/src/shared/framework/screen_controllers.dart
  packages/devtools_app/lib/src/shared/preferences/_cpu_profiler_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_extension_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_inspector_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_logging_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_memory_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_network_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_performance_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/preferences.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/extensions_view.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/sidebar_extensions_controller.dart
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/example/utils/auto_dispose_example.dart
  packages/devtools_app_shared/lib/src/service/eval_on_dart_library.dart
  packages/devtools_app_shared/lib/src/utils/auto_dispose.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_controller.dart
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required

#8931 Correct more broken comment references
  packages/devtools_app/lib/src/shared/diagnostics/generic_instance_reference.dart
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/lib/src/shared/framework/screen.dart
  packages/devtools_app/lib/src/shared/http/http_request_data.dart
  packages/devtools_app/lib/src/shared/log_storage.dart
  packages/devtools_app/lib/src/shared/managers/survey.dart
  packages/devtools_app/lib/src/shared/primitives/collapsible_mixin.dart
Labels: release-notes-not-required

#8945 [Property Editor] Fix text input state retention issues
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/property_editor_test.dart
Labels: release-notes-not-required

#8951 [Property Editor] Do not trigger edits if there have been no changes to a property
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/property_editor_test.dart
Labels: release-notes-not-required

#8940 handle null functions key in cpu samples
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart
  packages/devtools_app/test/screens/cpu_profiler/cpu_profile_model_test.dart
Labels: release-notes-not-required

#8958 [Property Editor] Fix text input state retention issues follow-up
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
Labels: release-notes-not-required

#8957 [Property Editor] Add workaround for embedded `TextField` focus issues
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/utils/_utils_desktop.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/utils/_utils_web.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/utils/utils.dart
Labels: release-notes-not-required
