Repository flutter/devtools, pull requests merged in 2025-01, with the labels that each got.

#8668 Fix dropdown overflow for enums
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
Labels: release-notes-not-required

#8684 [Inspector V2] Fix inspector analytics
  packages/devtools_app/lib/src/screens/inspector/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_screen_body.dart
  packages/devtools_app/lib/src/screens/inspector/inspector_tree_controller.dart
  packages/devtools_app/lib/src/screens/inspector_shared/inspector_settings_dialog.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_controller.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_screen_body.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_tree_controller.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/metrics.dart
Labels: release-notes-not-required

#8687 Optimize stack traces for analytics
  packages/devtools_app/lib/src/shared/analytics/_analytics_stub.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/analytics_common.dart
  packages/devtools_app/lib/src/shared/framework/app_error_handling.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/test/shared/analytics/analytics_test.dart
  packages/devtools_app/test/shared/primitives/utils_test.dart
Labels: release-notes-not-required

#8669 License update - Batch 1
  BETA_TESTING.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DOCUMENTATION.md
  README.md
  STYLE.md
  TESTING.md
  TRIAGE.md
  analysis_options.yaml
  devtools_options.yaml
  docs/README.md
  pubspec.yaml
Labels: release-notes-not-required

#8700 Add onDevToolsInitialized parameter to initialization logic
  packages/devtools_app/lib/initialization.dart
Labels: release-notes-not-required

#8670 License update - Batch 2
  case_study/code_size/optimized/README.md
  case_study/code_size/optimized/code_size_images/README.md
  case_study/code_size/optimized/code_size_images/android/app/build.gradle
  case_study/code_size/optimized/code_size_images/android/app/src/debug/AndroidManifest.xml
  case_study/code_size/optimized/code_size_images/android/app/src/main/AndroidManifest.xml
  case_study/code_size/optimized/code_size_images/android/app/src/main/res/drawable/launch_background.xml
  case_study/code_size/optimized/code_size_images/android/app/src/main/res/values/styles.xml
  case_study/code_size/optimized/code_size_images/android/app/src/profile/AndroidManifest.xml
  case_study/code_size/optimized/code_size_images/android/build.gradle
  case_study/code_size/optimized/code_size_images/android/settings.gradle
  case_study/code_size/optimized/code_size_images/ios/Runner/AppDelegate.swift
  case_study/code_size/optimized/code_size_images/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  case_study/code_size/optimized/code_size_images/ios/Runner/Runner-Bridging-Header.h
  case_study/code_size/optimized/code_size_images/lib/animals.dart
  case_study/code_size/optimized/code_size_images/lib/main.dart
  case_study/code_size/optimized/code_size_images/macos/Flutter/GeneratedPluginRegistrant.swift
  case_study/code_size/optimized/code_size_images/macos/Runner/AppDelegate.swift
  case_study/code_size/optimized/code_size_images/macos/Runner/MainFlutterWindow.swift
  case_study/code_size/optimized/code_size_images/pubspec.yaml
  case_study/code_size/optimized/code_size_images/test/widget_test.dart
  case_study/code_size/optimized/code_size_images/web/index.html
  case_study/code_size/optimized/code_size_package/README.md
  case_study/code_size/optimized/code_size_package/android/app/build.gradle
  case_study/code_size/optimized/code_size_package/android/app/src/debug/AndroidManifest.xml
  case_study/code_size/optimized/code_size_package/android/app/src/main/AndroidManifest.xml
  case_study/code_size/optimized/code_size_package/android/app/src/main/res/drawable/launch_background.xml
  case_study/code_size/optimized/code_size_package/android/app/src/main/res/values/styles.xml
  case_study/code_size/optimized/code_size_package/android/app/src/profile/AndroidManifest.xml
  case_study/code_size/optimized/code_size_package/android/build.gradle
  case_study/code_size/optimized/code_size_package/android/settings.gradle
  case_study/code_size/optimized/code_size_package/ios/Runner/AppDelegate.swift
  case_study/code_size/optimized/code_size_package/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  case_study/code_size/optimized/code_size_package/ios/Runner/Runner-Bridging-Header.h
  case_study/code_size/optimized/code_size_package/lib/main.dart
  case_study/code_size/optimized/code_size_package/macos/Flutter/GeneratedPluginRegistrant.swift
  case_study/code_size/optimized/code_size_package/macos/Runner/AppDelegate.swift
  case_study/code_size/optimized/code_size_package/macos/Runner/MainFlutterWindow.swift
  case_study/code_size/optimized/code_size_package/pubspec.yaml
  case_study/code_size/optimized/code_size_package/test/widget_test.dart
  case_study/code_size/optimized/code_size_package/web/index.html
Labels: release-notes-not-required

#8674 License update - Batch 3
  case_study/code_size/unoptimized/README.md
  case_study/code_size/unoptimized/code_size_images/README.md
  case_study/code_size/unoptimized/code_size_images/android/app/build.gradle
  case_study/code_size/unoptimized/code_size_images/android/app/src/debug/AndroidManifest.xml
  case_study/code_size/unoptimized/code_size_images/android/app/src/main/AndroidManifest.xml
  case_study/code_size/unoptimized/code_size_images/android/app/src/main/res/drawable/launch_background.xml
  case_study/code_size/unoptimized/code_size_images/android/app/src/main/res/values/styles.xml
  case_study/code_size/unoptimized/code_size_images/android/app/src/profile/AndroidManifest.xml
  case_study/code_size/unoptimized/code_size_images/android/build.gradle
  case_study/code_size/unoptimized/code_size_images/android/settings.gradle
  case_study/code_size/unoptimized/code_size_images/ios/Runner/AppDelegate.swift
  case_study/code_size/unoptimized/code_size_images/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  case_study/code_size/unoptimized/code_size_images/ios/Runner/Runner-Bridging-Header.h
  case_study/code_size/unoptimized/code_size_images/lib/animals.dart
  case_study/code_size/unoptimized/code_size_images/lib/main.dart
  case_study/code_size/unoptimized/code_size_images/macos/Flutter/GeneratedPluginRegistrant.swift
  case_study/code_size/unoptimized/code_size_images/macos/Runner/AppDelegate.swift
  case_study/code_size/unoptimized/code_size_images/macos/Runner/MainFlutterWindow.swift
  case_study/code_size/unoptimized/code_size_images/pubspec.yaml
  case_study/code_size/unoptimized/code_size_images/test/widget_test.dart
  case_study/code_size/unoptimized/code_size_images/web/index.html
  case_study/code_size/unoptimized/code_size_package/README.md
  case_study/code_size/unoptimized/code_size_package/android/app/build.gradle
  case_study/code_size/unoptimized/code_size_package/android/app/src/debug/AndroidManifest.xml
  case_study/code_size/unoptimized/code_size_package/android/app/src/main/AndroidManifest.xml
  case_study/code_size/unoptimized/code_size_package/android/app/src/main/res/drawable/launch_background.xml
  case_study/code_size/unoptimized/code_size_package/android/app/src/main/res/values/styles.xml
  case_study/code_size/unoptimized/code_size_package/android/app/src/profile/AndroidManifest.xml
  case_study/code_size/unoptimized/code_size_package/android/build.gradle
  case_study/code_size/unoptimized/code_size_package/android/settings.gradle
  case_study/code_size/unoptimized/code_size_package/ios/Runner/AppDelegate.swift
  case_study/code_size/unoptimized/code_size_package/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  case_study/code_size/unoptimized/code_size_package/ios/Runner/Runner-Bridging-Header.h
  case_study/code_size/unoptimized/code_size_package/lib/main.dart
  case_study/code_size/unoptimized/code_size_package/macos/Flutter/GeneratedPluginRegistrant.swift
  case_study/code_size/unoptimized/code_size_package/macos/Runner/AppDelegate.swift
  case_study/code_size/unoptimized/code_size_package/macos/Runner/MainFlutterWindow.swift
  case_study/code_size/unoptimized/code_size_package/pubspec.yaml
  case_study/code_size/unoptimized/code_size_package/test/widget_test.dart
  case_study/code_size/unoptimized/code_size_package/web/index.html
Labels: release-notes-not-required

#8677 License update - Batch 4
  case_study/memory_leaks/images_1/README.md
  case_study/memory_leaks/images_1/analysis_options.yaml
  case_study/memory_leaks/images_1/android/app/build.gradle
  case_study/memory_leaks/images_1/android/app/src/debug/AndroidManifest.xml
  case_study/memory_leaks/images_1/android/app/src/main/AndroidManifest.xml
  case_study/memory_leaks/images_1/android/app/src/main/res/drawable-v21/launch_background.xml
  case_study/memory_leaks/images_1/android/app/src/main/res/drawable/launch_background.xml
  case_study/memory_leaks/images_1/android/app/src/main/res/values-night/styles.xml
  case_study/memory_leaks/images_1/android/app/src/main/res/values/styles.xml
  case_study/memory_leaks/images_1/android/app/src/profile/AndroidManifest.xml
  case_study/memory_leaks/images_1/android/build.gradle
  case_study/memory_leaks/images_1/android/settings.gradle
  case_study/memory_leaks/images_1/ios/Runner/AppDelegate.swift
  case_study/memory_leaks/images_1/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  case_study/memory_leaks/images_1/ios/Runner/Runner-Bridging-Header.h
  case_study/memory_leaks/images_1/lib/main.dart
  case_study/memory_leaks/images_1/macos/Runner/AppDelegate.swift
  case_study/memory_leaks/images_1/macos/Runner/MainFlutterWindow.swift
  case_study/memory_leaks/images_1/pubspec.yaml
  case_study/memory_leaks/images_1/web/README.md
  case_study/memory_leaks/images_1/web/index.html
  case_study/memory_leaks/images_1/windows/runner/flutter_window.cpp
  case_study/memory_leaks/images_1/windows/runner/flutter_window.h
  case_study/memory_leaks/images_1/windows/runner/main.cpp
  case_study/memory_leaks/images_1/windows/runner/resource.h
  case_study/memory_leaks/images_1/windows/runner/utils.cpp
  case_study/memory_leaks/images_1/windows/runner/utils.h
  case_study/memory_leaks/images_1/windows/runner/win32_window.cpp
  case_study/memory_leaks/images_1/windows/runner/win32_window.h
Labels: release-notes-not-required

#8678 License update - Batch 5
  case_study/memory_leaks/leaking_counter_1/README.md
  case_study/memory_leaks/leaking_counter_1/analysis_options.yaml
  case_study/memory_leaks/leaking_counter_1/android/app/build.gradle
  case_study/memory_leaks/leaking_counter_1/android/app/src/debug/AndroidManifest.xml
  case_study/memory_leaks/leaking_counter_1/android/app/src/main/AndroidManifest.xml
  case_study/memory_leaks/leaking_counter_1/android/app/src/main/res/drawable-v21/launch_background.xml
  case_study/memory_leaks/leaking_counter_1/android/app/src/main/res/drawable/launch_background.xml
  case_study/memory_leaks/leaking_counter_1/android/app/src/main/res/values-night/styles.xml
  case_study/memory_leaks/leaking_counter_1/android/app/src/main/res/values/styles.xml
  case_study/memory_leaks/leaking_counter_1/android/app/src/profile/AndroidManifest.xml
  case_study/memory_leaks/leaking_counter_1/android/build.gradle
  case_study/memory_leaks/leaking_counter_1/android/settings.gradle
  case_study/memory_leaks/leaking_counter_1/ios/Runner/AppDelegate.swift
  case_study/memory_leaks/leaking_counter_1/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  case_study/memory_leaks/leaking_counter_1/ios/Runner/Runner-Bridging-Header.h
  case_study/memory_leaks/leaking_counter_1/lib/main.dart
  case_study/memory_leaks/leaking_counter_1/linux/main.cc
  case_study/memory_leaks/leaking_counter_1/linux/my_application.cc
  case_study/memory_leaks/leaking_counter_1/linux/my_application.h
  case_study/memory_leaks/leaking_counter_1/macos/Runner/AppDelegate.swift
  case_study/memory_leaks/leaking_counter_1/macos/Runner/MainFlutterWindow.swift
  case_study/memory_leaks/leaking_counter_1/pubspec.yaml
  case_study/memory_leaks/leaking_counter_1/test/widget_test.dart
  case_study/memory_leaks/leaking_counter_1/web/index.html
  case_study/memory_leaks/leaking_counter_1/windows/runner/flutter_window.cpp
  case_study/memory_leaks/leaking_counter_1/windows/runner/flutter_window.h
  case_study/memory_leaks/leaking_counter_1/windows/runner/main.cpp
  case_study/memory_leaks/leaking_counter_1/windows/runner/resource.h
  case_study/memory_leaks/leaking_counter_1/windows/runner/utils.cpp
  case_study/memory_leaks/leaking_counter_1/windows/runner/utils.h
  case_study/memory_leaks/leaking_counter_1/windows/runner/win32_window.cpp
  case_study/memory_leaks/leaking_counter_1/windows/runner/win32_window.h
Labels: release-notes-not-required

#8680 License update - Batch 7
  case_study/platform_channel/README.md
  case_study/platform_channel/android/app/build.gradle
  case_study/platform_channel/android/app/src/debug/AndroidManifest.xml
  case_study/platform_channel/android/app/src/main/AndroidManifest.xml
  case_study/platform_channel/android/app/src/main/res/drawable/launch_background.xml
  case_study/platform_channel/android/app/src/main/res/values/styles.xml
  case_study/platform_channel/android/app/src/profile/AndroidManifest.xml
  case_study/platform_channel/android/build.gradle
  case_study/platform_channel/android/settings.gradle
  case_study/platform_channel/ios/Runner/AppDelegate.swift
  case_study/platform_channel/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  case_study/platform_channel/ios/Runner/Runner-Bridging-Header.h
  case_study/platform_channel/lib/channel_demo.dart
  case_study/platform_channel/lib/main.dart
  case_study/platform_channel/pubspec.yaml
  case_study/platform_channel/test/widget_test.dart
  case_study/platform_channel/web/index.html
Labels: release-notes-not-required

#8681 License update - Batch 8
  packages/devtools_app/README.md
  packages/devtools_app/analysis_options.yaml
  packages/devtools_app/dart_test.yaml
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/release_notes/README.md
  packages/devtools_app/release_notes/helpers/release_notes_template.md
  packages/devtools_app/test/README.md
  packages/devtools_app/test/integration_test_infra/in_file_args_test.dart
Labels: release-notes-not-required

#8682 License update - Batch 9
  packages/devtools_app/benchmark/README.md
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
  packages/devtools_app/benchmark/scripts/args.dart
  packages/devtools_app/benchmark/scripts/compare_benchmarks.dart
  packages/devtools_app/benchmark/scripts/dart2wasm_performance_diff.dart
  packages/devtools_app/benchmark/scripts/run_benchmarks.dart
  packages/devtools_app/benchmark/test_infra/automators/_cpu_profiler_automator.dart
  packages/devtools_app/benchmark/test_infra/automators/_performance_automator.dart
  packages/devtools_app/benchmark/test_infra/automators/devtools_automator.dart
  packages/devtools_app/benchmark/test_infra/client/client_js.dart
  packages/devtools_app/benchmark/test_infra/client/client_shared.dart
  packages/devtools_app/benchmark/test_infra/client/client_wasm.dart
  packages/devtools_app/benchmark/test_infra/common.dart
  packages/devtools_app/benchmark/test_infra/devtools_recorder.dart
  packages/devtools_app/benchmark/test_infra/project_root_directory.dart
  packages/devtools_app/benchmark/web_bundle_size_test.dart
Labels: release-notes-not-required

#8683 License update - Batch 10
  packages/devtools_app/integration_test/README.md
  packages/devtools_app/integration_test/run_tests.dart
  packages/devtools_app/integration_test/test/live_connection/app_test.dart
  packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart
  packages/devtools_app/integration_test/test/live_connection/devtools_extensions_test.dart
  packages/devtools_app/integration_test/test/live_connection/eval_and_browse_test.dart
  packages/devtools_app/integration_test/test/live_connection/eval_and_inspect_test.dart
  packages/devtools_app/integration_test/test/live_connection/eval_utils.dart
  packages/devtools_app/integration_test/test/live_connection/export_snapshot_test.dart
  packages/devtools_app/integration_test/test/live_connection/memory_screen_helpers.dart
  packages/devtools_app/integration_test/test/live_connection/performance_screen_event_recording_test.dart
  packages/devtools_app/integration_test/test/live_connection/service_connection_test.dart
  packages/devtools_app/integration_test/test/live_connection/service_extensions_test.dart
  packages/devtools_app/integration_test/test/offline/memory_offline_data_test.dart
  packages/devtools_app/integration_test/test/offline/perfetto_test.dart
Labels: release-notes-not-required

#8686 License update - Batch 11
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/initialization.dart
  packages/devtools_app/lib/main.dart
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/example/conditional_screen.dart
Labels: release-notes-not-required

#8689 License update - Batch 12
  packages/devtools_app/lib/src/extensions/embedded/_controller_desktop.dart
  packages/devtools_app/lib/src/extensions/embedded/_controller_web.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_desktop.dart
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/extensions/embedded/controller.dart
  packages/devtools_app/lib/src/extensions/embedded/view.dart
  packages/devtools_app/lib/src/extensions/extension_screen.dart
  packages/devtools_app/lib/src/extensions/extension_screen_controls.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/extensions/extension_service_helpers.dart
  packages/devtools_app/lib/src/extensions/extension_settings.dart
  packages/devtools_app/test/extensions/extension_analytics_test.dart
  packages/devtools_app/test/extensions/extension_screen_test.dart
  packages/devtools_app/test/extensions/extension_service_helpers_test.dart
  packages/devtools_app/test/extensions/extension_service_test.dart
  packages/devtools_app/test/extensions/extension_settings_test.dart
Labels: release-notes-not-required

#8691 License update - Batch 13
  packages/devtools_app/lib/src/framework/README.md
  packages/devtools_app/lib/src/framework/disconnect_observer.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/framework/home_screen.dart
  packages/devtools_app/lib/src/framework/initializer.dart
  packages/devtools_app/lib/src/framework/notifications_view.dart
  packages/devtools_app/lib/src/framework/release_notes.dart
  packages/devtools_app/lib/src/framework/scaffold/about_dialog.dart
  packages/devtools_app/lib/src/framework/scaffold/app_bar.dart
  packages/devtools_app/lib/src/framework/scaffold/report_feedback_button.dart
  packages/devtools_app/lib/src/framework/scaffold/scaffold.dart
  packages/devtools_app/lib/src/framework/scaffold/settings_dialog.dart
  packages/devtools_app/lib/src/framework/scaffold/status_line.dart
  packages/devtools_app/lib/src/framework/theme_manager.dart
  packages/devtools_app/test/framework/disconnect_observer_test.dart
  packages/devtools_app/test/framework/home_screen_test.dart
  packages/devtools_app/test/framework/initializer_test.dart
  packages/devtools_app/test/framework/notifications_test.dart
  packages/devtools_app/test/framework/release_notes_test.dart
  packages/devtools_app/test/framework/scaffold/about_dialog_test.dart
  packages/devtools_app/test/framework/scaffold/scaffold_debugger_test.dart
  packages/devtools_app/test/framework/scaffold/scaffold_debugging_controls_test.dart
  packages/devtools_app/test/framework/scaffold/scaffold_no_app_test.dart
  packages/devtools_app/test/framework/scaffold/scaffold_profile_test.dart
  packages/devtools_app/test/framework/scaffold/scaffold_test.dart
Labels: release-notes-not-required

#8692 License update - Batch 14
  packages/devtools_app/lib/src/screens/app_size/app_size_controller.dart
  packages/devtools_app/lib/src/screens/app_size/app_size_screen.dart
  packages/devtools_app/lib/src/screens/app_size/app_size_table.dart
  packages/devtools_app/lib/src/screens/app_size/code_size_attribution.dart
  packages/devtools_app/test/screens/app_size/app_size_screen_test.dart
  packages/devtools_app/test/screens/app_size/code_size_attribution_test.dart
Labels: release-notes-not-required

#8694 License update - Batch 16
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_model.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_screen.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_services.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/root_selector.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/select_project_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/test/screens/deep_link_vlidation/app_link_settings_test.dart
  packages/devtools_app/test/screens/deep_link_vlidation/deep_links_screen_test.dart
  packages/devtools_app/test/screens/deep_link_vlidation/select_project_view_test.dart
  packages/devtools_app/test/screens/deep_link_vlidation/universal_link_settings_test.dart
Labels: release-notes-not-required

#8699 License update - Batch 19
  packages/devtools_app/lib/src/screens/logging/_log_details.dart
  packages/devtools_app/lib/src/screens/logging/_logs_table.dart
  packages/devtools_app/lib/src/screens/logging/_message_column.dart
  packages/devtools_app/lib/src/screens/logging/_when_column.dart
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/logging/logging_controls.dart
  packages/devtools_app/lib/src/screens/logging/logging_screen.dart
  packages/devtools_app/lib/src/screens/logging/metadata.dart
  packages/devtools_app/test/screens/logging/logging_controller_test.dart
  packages/devtools_app/test/screens/logging/logging_screen_data_test.dart
  packages/devtools_app/test/screens/logging/logging_screen_test.dart
  packages/devtools_app/test/screens/logging/metadata_test.dart
Labels: release-notes-not-required

#8693 License update - Batch 15
  packages/devtools_app/lib/src/screens/debugger/breakpoint_manager.dart
  packages/devtools_app/lib/src/screens/debugger/breakpoints.dart
  packages/devtools_app/lib/src/screens/debugger/call_stack.dart
  packages/devtools_app/lib/src/screens/debugger/codeview.dart
  packages/devtools_app/lib/src/screens/debugger/codeview_controller.dart
  packages/devtools_app/lib/src/screens/debugger/common.dart
  packages/devtools_app/lib/src/screens/debugger/controls.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_model.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/screens/debugger/file_search.dart
  packages/devtools_app/lib/src/screens/debugger/key_sets.dart
  packages/devtools_app/lib/src/screens/debugger/program_explorer.dart
  packages/devtools_app/lib/src/screens/debugger/program_explorer_controller.dart
  packages/devtools_app/lib/src/screens/debugger/program_explorer_model.dart
  packages/devtools_app/lib/src/screens/debugger/span_parser.dart
  packages/devtools_app/lib/src/screens/debugger/syntax_highlighter.dart
  packages/devtools_app/lib/src/screens/debugger/variables.dart
  packages/devtools_app/test/screens/debugger/association_variable_test.dart
  packages/devtools_app/test/screens/debugger/debugger_codeview_statistics_test.dart
  packages/devtools_app/test/screens/debugger/debugger_codeview_test.dart
  packages/devtools_app/test/screens/debugger/debugger_console_test.dart
  packages/devtools_app/test/screens/debugger/debugger_controller_stdio_test.dart
  packages/devtools_app/test/screens/debugger/debugger_controller_test.dart
  packages/devtools_app/test/screens/debugger/debugger_evaluation_test.dart
  packages/devtools_app/test/screens/debugger/debugger_floating_test.dart
  packages/devtools_app/test/screens/debugger/debugger_screen_breakpoints_test.dart
  packages/devtools_app/test/screens/debugger/debugger_screen_call_stack_test.dart
  packages/devtools_app/test/screens/debugger/debugger_screen_dap_variables_test.dart
  packages/devtools_app/test/screens/debugger/debugger_screen_explorer_visibility_test.dart
  packages/devtools_app/test/screens/debugger/debugger_screen_paused_test.dart
  packages/devtools_app/test/screens/debugger/debugger_screen_test.dart
  packages/devtools_app/test/screens/debugger/debugger_screen_variables_test.dart
  packages/devtools_app/test/screens/debugger/debugger_scripts_test.dart
  packages/devtools_app/test/screens/debugger/eval_field_test.dart
  packages/devtools_app/test/screens/debugger/file_search_test.dart
  packages/devtools_app/test/screens/debugger/program_explorer_test.dart
  packages/devtools_app/test/screens/debugger/records_variable_test.dart
  packages/devtools_app/test/screens/debugger/span_parser_test.dart
  packages/devtools_app/test/screens/debugger/syntax_highlighter_test.dart
  packages/devtools_app/test/screens/debugger/typed_data_variable_test.dart
  packages/devtools_app/test/screens/debugger/variables_test.dart
Labels: release-notes-not-required

#8679 License update - Batch 6
  case_study/memory_leaks/memory_leak_app/README.md
  case_study/memory_leaks/memory_leak_app/android/app/build.gradle
  case_study/memory_leaks/memory_leak_app/android/app/src/main/AndroidManifest.xml
  case_study/memory_leaks/memory_leak_app/android/app/src/main/java/github/nisrulz/usingtabs/MainActivity.java
  case_study/memory_leaks/memory_leak_app/android/build.gradle
  case_study/memory_leaks/memory_leak_app/android/gradlew.bat
  case_study/memory_leaks/memory_leak_app/android/settings.gradle
  case_study/memory_leaks/memory_leak_app/ios/Runner/AppDelegate.h
  case_study/memory_leaks/memory_leak_app/lib/about.dart
  case_study/memory_leaks/memory_leak_app/lib/common.dart
  case_study/memory_leaks/memory_leak_app/lib/logging.dart
  case_study/memory_leaks/memory_leak_app/lib/main.dart
  case_study/memory_leaks/memory_leak_app/lib/restful_servers.dart
  case_study/memory_leaks/memory_leak_app/lib/tabs/http_data.dart
  case_study/memory_leaks/memory_leak_app/lib/tabs/logger.dart
  case_study/memory_leaks/memory_leak_app/lib/tabs/settings.dart
  case_study/memory_leaks/memory_leak_app/pubspec.yaml
  case_study/memory_leaks/memory_leak_app/test/widget_test.dart
Labels: release-notes-not-required

#8720 License update - Batch 22
  packages/devtools_app/lib/src/screens/performance/README.md
  packages/devtools_app/lib/src/screens/performance/panes/controls/enhance_tracing/enhance_tracing.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/enhance_tracing/enhance_tracing_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/enhance_tracing/enhance_tracing_model.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/more_debugging_options.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/performance_controls.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/performance_settings.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frame_model.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frames_chart.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frames_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_analysis.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_analysis_model.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_hints.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_time_visualizer.dart
  packages/devtools_app/lib/src/screens/performance/panes/rebuild_stats/rebuild_stats.dart
  packages/devtools_app/lib/src/screens/performance/panes/rebuild_stats/rebuild_stats_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/rebuild_stats/rebuild_stats_model.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_desktop.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_desktop.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/perfetto.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/perfetto_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/tracing/model.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_event_processor.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_view.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_model.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/screens/performance/performance_utils.dart
  packages/devtools_app/lib/src/screens/performance/tabbed_performance_view.dart
  packages/devtools_app/test/screens/performance/controls/enhance_tracing_test.dart
  packages/devtools_app/test/screens/performance/controls/performance_controls_test.dart
  packages/devtools_app/test/screens/performance/flutter_frames/flutter_frame_model_test.dart
  packages/devtools_app/test/screens/performance/flutter_frames/flutter_frames_chart_test.dart
  packages/devtools_app/test/screens/performance/flutter_frames/flutter_frames_controller_test.dart
  packages/devtools_app/test/screens/performance/frame_analysis/frame_analysis_model_test.dart
  packages/devtools_app/test/screens/performance/frame_analysis/frame_analysis_test.dart
  packages/devtools_app/test/screens/performance/frame_analysis/frame_hints_test.dart
  packages/devtools_app/test/screens/performance/performance_controller_test.dart
  packages/devtools_app/test/screens/performance/performance_model_test.dart
  packages/devtools_app/test/screens/performance/performance_screen_test.dart
  packages/devtools_app/test/screens/performance/rebuild_stats/widget_rebuild_counts_test.dart
  packages/devtools_app/test/screens/performance/tabbed_performance_view_test.dart
  packages/devtools_app/test/screens/performance/timeline_events/perfetto/tracing_model_test.dart
  packages/devtools_app/test/screens/performance/timeline_events/timeline_event_processor_test.dart
  packages/devtools_app/test/screens/performance/timeline_events/timeline_events_controller_test.dart
Labels: release-notes-not-required

#8721 License update - Batch 23
  packages/devtools_app/lib/src/screens/profiler/common.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_service.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_transformer.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profiler.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profiler_controller.dart
  packages/devtools_app/lib/src/screens/profiler/panes/bottom_up.dart
  packages/devtools_app/lib/src/screens/profiler/panes/call_tree.dart
  packages/devtools_app/lib/src/screens/profiler/panes/controls/cpu_profiler_controls.dart
  packages/devtools_app/lib/src/screens/profiler/panes/controls/profiler_screen_controls.dart
  packages/devtools_app/lib/src/screens/profiler/panes/cpu_flame_chart.dart
  packages/devtools_app/lib/src/screens/profiler/panes/cpu_profile_columns.dart
  packages/devtools_app/lib/src/screens/profiler/panes/method_table/method_table.dart
  packages/devtools_app/lib/src/screens/profiler/panes/method_table/method_table_controller.dart
  packages/devtools_app/lib/src/screens/profiler/panes/method_table/method_table_model.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen_controller.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_status.dart
  packages/devtools_app/lib/src/screens/profiler/sampling_rate.dart
  packages/devtools_app/lib/src/screens/provider/provider_screen.dart
Labels: release-notes-not-required

#8722 License update - Batch 24
  packages/devtools_app/lib/src/screens/vm_developer/isolate_statistics/isolate_statistics_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/isolate_statistics/isolate_statistics_view_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/class_hierarchy_explorer.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/class_hierarchy_explorer_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/inbound_references_tree.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_inspector_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_inspector_view_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_store.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_store_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/object_viewport.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_class_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_code_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_field_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_function_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_ic_data_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_instance_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_library_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_object_model.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_object_pool_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_script_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_simple_list_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/object_inspector/vm_unknown_object_display.dart
  packages/devtools_app/lib/src/screens/vm_developer/process_memory/process_memory_tree_columns.dart
  packages/devtools_app/lib/src/screens/vm_developer/process_memory/process_memory_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/process_memory/process_memory_view_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_common_widgets.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_tools_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_tools_screen.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_service_private_extensions.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_statistics/vm_statistics_view.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_statistics/vm_statistics_view_controller.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/class_hierarchy_explorer_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/object_inspector_view_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/object_viewport_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/vm_class_display_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/vm_code_display_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/vm_developer_common_widgets_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/vm_field_display_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/vm_function_display_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/vm_ic_data_display_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/vm_library_display_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/vm_object_pool_display_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/vm_script_display_test.dart
  packages/devtools_app/test/screens/vm_developer/object_inspector/vm_simple_list_display_test.dart
  packages/devtools_app/test/screens/vm_developer/vm_developer_test_utils.dart
Labels: release-notes-not-required

#8723 License update - Batch 25
  packages/devtools_app/lib/src/service/connected_app/connected_app.dart
  packages/devtools_app/lib/src/service/connected_app/connection_info.dart
  packages/devtools_app/lib/src/service/editor/api_classes.dart
  packages/devtools_app/lib/src/service/editor/editor_client.dart
  packages/devtools_app/lib/src/service/json_to_service_cache.dart
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
  packages/devtools_app/lib/src/service/service_extensions.dart
  packages/devtools_app/lib/src/service/service_manager.dart
  packages/devtools_app/lib/src/service/service_registrations.dart
  packages/devtools_app/lib/src/service/timeline_streams.dart
  packages/devtools_app/lib/src/service/vm_flags.dart
  packages/devtools_app/lib/src/service/vm_service_logger.dart
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
  packages/devtools_app/test/service/connection_info_test.dart
  packages/devtools_app/test/service/service_extension_widgets_test.dart
  packages/devtools_app/test/service/timeline_streams_test.dart
  packages/devtools_app/test/service/vm_flags_test.dart
Labels: release-notes-not-required

#8724 License update - Batch 26
  packages/devtools_app/lib/src/shared/README.md
  packages/devtools_app/lib/src/shared/constants.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/environment_parameters/environment_parameters_base.dart
  packages/devtools_app/lib/src/shared/environment_parameters/environment_parameters_external.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/lib/src/shared/globals.dart
  packages/devtools_app/lib/src/shared/log_storage.dart
  packages/devtools_app/lib/src/shared/title.dart
Labels: release-notes-not-required

#8725 License update - Batch 27
  packages/devtools_app/lib/src/shared/analytics/_analytics_stub.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/analytics/analytics.dart
  packages/devtools_app/lib/src/shared/analytics/analytics_common.dart
  packages/devtools_app/lib/src/shared/analytics/analytics_controller.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_cpu_profiler_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_debugger_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_deep_links_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_editor_sidebar_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_extension_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_inspector_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_logging_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_memory_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_network_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_performance_constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_property_editor_sidebar_constants.dart
  packages/devtools_app/lib/src/shared/analytics/gtags.dart
  packages/devtools_app/lib/src/shared/analytics/metrics.dart
  packages/devtools_app/lib/src/shared/analytics/prompt.dart
  packages/devtools_app/test/shared/analytics/analytics_prompt_test.dart
  packages/devtools_app/test/shared/analytics/analytics_test.dart
Labels: release-notes-not-required

#8628 Roll package:vm_service ^15.0.0
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_test/pubspec.yaml
Labels: autosubmit

#8727 License update - Batch 29
  packages/devtools_app/lib/src/shared/config_specific/copy_to_clipboard/_copy_to_clipboard_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/copy_to_clipboard/_copy_to_clipboard_web.dart
  packages/devtools_app/lib/src/shared/config_specific/copy_to_clipboard/copy_to_clipboard.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/_drag_and_drop_web.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/drag_and_drop.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_web.dart
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/framework_initialize.dart
  packages/devtools_app/lib/src/shared/config_specific/host_platform/_host_platform_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/host_platform/_host_platform_web.dart
  packages/devtools_app/lib/src/shared/config_specific/host_platform/host_platform.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/_export_web.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/_file_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/import_export/import_export.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_allowed_error_default.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_allowed_error_web.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_logger_io.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_logger_web.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/allowed_error.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/logger.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/logger_helpers.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/_notifications_desktop.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/_notifications_web.dart
  packages/devtools_app/lib/src/shared/config_specific/notifications/notifications.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/_post_message_stub.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/_post_message_web.dart
  packages/devtools_app/lib/src/shared/config_specific/post_message/post_message.dart
Labels: release-notes-not-required

#8730 Delete the example conditional screen
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/example/conditional_screen.dart
  packages/devtools_app/lib/src/shared/framework/screen.dart
Labels: release-notes-not-required

#8731 Update test.sh
  tool/flutter_customer_tests/test.sh
Labels: autosubmit

#8755 Move `editor/` files
  packages/devtools_app/lib/devtools_app.dart
  packages/devtools_app/lib/src/framework/theme_manager.dart
  packages/devtools_app/lib/src/shared/editor/api_classes.dart
  packages/devtools_app/lib/src/shared/editor/editor_client.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_panel.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devices.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/devtools_view.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/extensions_view.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/shared.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/sidebar_extensions_controller.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
  packages/devtools_app/test/standalone_ui/vs_code/debug_sessions_test.dart
  packages/devtools_app/test/standalone_ui/vs_code/devtools_test.dart
  packages/devtools_app/test/test_infra/scenes/standalone_ui/editor_service/simulated_editor.dart
  packages/devtools_app/test/test_infra/utils/sidebar_utils.dart
Labels: release-notes-not-required

#8762 Skip analytics tests for customer test registry
  packages/devtools_app/test/shared/analytics/analytics_test.dart
Labels: release-notes-not-required

#8732 License update - Batch 31
  packages/devtools_app/test/shared/ansi_output_test.dart
  packages/devtools_app/test/shared/development_helpers_test.dart
  packages/devtools_app/test/shared/environment_parameters/environment_parameters_external_test.dart
  packages/devtools_app/test/shared/eval_integration_test.dart
  packages/devtools_app/test/shared/import_export_test.dart
  packages/devtools_app/test/shared/log_storage_test.dart
  packages/devtools_app/test/shared/resolved_uri_manager_test.dart
Labels: release-notes-not-required

#8733 License update - Batch 32
  packages/devtools_app/lib/src/shared/diagnostics/dap_object_node.dart
  packages/devtools_app/lib/src/shared/diagnostics/dart_object_node.dart
  packages/devtools_app/lib/src/shared/diagnostics/diagnostics_node.dart
  packages/devtools_app/lib/src/shared/diagnostics/generic_instance_reference.dart
  packages/devtools_app/lib/src/shared/diagnostics/helpers.dart
  packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart
  packages/devtools_app/lib/src/shared/diagnostics/object_group_api.dart
  packages/devtools_app/lib/src/shared/diagnostics/primitives/README.md
  packages/devtools_app/lib/src/shared/diagnostics/primitives/instance_ref.dart
  packages/devtools_app/lib/src/shared/diagnostics/primitives/record_fields.dart
  packages/devtools_app/lib/src/shared/diagnostics/primitives/source_location.dart
  packages/devtools_app/lib/src/shared/diagnostics/references.dart
  packages/devtools_app/lib/src/shared/diagnostics/tree_builder.dart
  packages/devtools_app/lib/src/shared/diagnostics/variable_factory.dart
  packages/devtools_app/test/shared/diagnostics/dart_object_node_test.dart
  packages/devtools_app/test/shared/diagnostics/diagnostics_node_test.dart
  packages/devtools_app/test/shared/diagnostics/inspector_service_test.dart
Labels: release-notes-not-required

#8734 License update - Batch 33
  packages/devtools_app/lib/src/shared/framework/app_error_handling.dart
  packages/devtools_app/lib/src/shared/framework/framework_controller.dart
  packages/devtools_app/lib/src/shared/framework/routing.dart
  packages/devtools_app/lib/src/shared/framework/screen.dart
  packages/devtools_app/test/shared/framework/routing_test.dart
  packages/devtools_app/test/shared/framework/screens_test.dart
  packages/devtools_app/test/shared/framework/visible_screens_test.dart
Labels: release-notes-not-required

#8736 License update - Batch 35
  packages/devtools_app/lib/src/shared/managers/banner_messages.dart
  packages/devtools_app/lib/src/shared/managers/dtd_manager_extensions.dart
  packages/devtools_app/lib/src/shared/managers/error_badge_manager.dart
  packages/devtools_app/lib/src/shared/managers/notifications.dart
  packages/devtools_app/lib/src/shared/managers/script_manager.dart
  packages/devtools_app/lib/src/shared/managers/survey.dart
  packages/devtools_app/test/shared/managers/banner_messages_test.dart
  packages/devtools_app/test/shared/managers/error_badge_manager_test.dart
  packages/devtools_app/test/shared/managers/survey_test.dart
Labels: release-notes-not-required

#8738 License update - Batch 37
  packages/devtools_app/lib/src/shared/offline/offline_data.dart
  packages/devtools_app/lib/src/shared/offline/offline_screen.dart
  packages/devtools_app/lib/src/shared/preferences/_cpu_profiler_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_extension_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_inspector_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_logging_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_memory_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_network_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/_performance_preferences.dart
  packages/devtools_app/lib/src/shared/preferences/preferences.dart
  packages/devtools_app/test/shared/offline/review_history_on_disconnect_test.dart
  packages/devtools_app/test/shared/preferences/preferences_controller_test.dart
Labels: release-notes-not-required

#8739 License update - Batch 38
  packages/devtools_app/lib/src/shared/primitives/README.md
  packages/devtools_app/lib/src/shared/primitives/ansi_utils.dart
  packages/devtools_app/lib/src/shared/primitives/blocking_action_mixin.dart
  packages/devtools_app/lib/src/shared/primitives/byte_utils.dart
  packages/devtools_app/lib/src/shared/primitives/collapsible_mixin.dart
  packages/devtools_app/lib/src/shared/primitives/custom_pointer_scroll_view.dart
  packages/devtools_app/lib/src/shared/primitives/diagnostics_text_styles.dart
  packages/devtools_app/lib/src/shared/primitives/encoding.dart
  packages/devtools_app/lib/src/shared/primitives/enum_utils.dart
  packages/devtools_app/lib/src/shared/primitives/extent_delegate_list.dart
  packages/devtools_app/lib/src/shared/primitives/flutter_widgets/README.md
  packages/devtools_app/lib/src/shared/primitives/flutter_widgets/linked_scroll_controller.dart
  packages/devtools_app/lib/src/shared/primitives/graph.dart
  packages/devtools_app/lib/src/shared/primitives/history_manager.dart
  packages/devtools_app/lib/src/shared/primitives/list_queue_value_notifier.dart
  packages/devtools_app/lib/src/shared/primitives/listenable.dart
  packages/devtools_app/lib/src/shared/primitives/math_utils.dart
  packages/devtools_app/lib/src/shared/primitives/message_bus.dart
  packages/devtools_app/lib/src/shared/primitives/query_parameters.dart
  packages/devtools_app/lib/src/shared/primitives/simple_items.dart
  packages/devtools_app/lib/src/shared/primitives/storage.dart
  packages/devtools_app/lib/src/shared/primitives/syntax_highlighting.dart
  packages/devtools_app/lib/src/shared/primitives/trace_event.dart
  packages/devtools_app/lib/src/shared/primitives/trees.dart
  packages/devtools_app/lib/src/shared/primitives/url_utils.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/test/shared/primitives/byte_utils_test.dart
  packages/devtools_app/test/shared/primitives/encoding_test.dart
  packages/devtools_app/test/shared/primitives/enum_utils_test.dart
  packages/devtools_app/test/shared/primitives/extent_delegate_list_view_test.dart
  packages/devtools_app/test/shared/primitives/extent_delegate_test.dart
  packages/devtools_app/test/shared/primitives/feature_flags_test.dart
  packages/devtools_app/test/shared/primitives/graph_test.dart
  packages/devtools_app/test/shared/primitives/history_manager_test.dart
  packages/devtools_app/test/shared/primitives/linked_scroll_controller_test.dart
  packages/devtools_app/test/shared/primitives/list_queue_value_notifier_test.dart
  packages/devtools_app/test/shared/primitives/math_utils_test.dart
  packages/devtools_app/test/shared/primitives/message_bus_test.dart
  packages/devtools_app/test/shared/primitives/query_parameters_test.dart
  packages/devtools_app/test/shared/primitives/simple_items_test.dart
  packages/devtools_app/test/shared/primitives/trees_test.dart
  packages/devtools_app/test/shared/primitives/url_utils_test.dart
  packages/devtools_app/test/shared/primitives/utils_test.dart
Labels: release-notes-not-required

#8740 License update - Batch 39
  packages/devtools_app/lib/src/shared/server/_analytics_api.dart
  packages/devtools_app/lib/src/shared/server/_app_size_api.dart
  packages/devtools_app/lib/src/shared/server/_deep_links_api.dart
  packages/devtools_app/lib/src/shared/server/_dtd_api.dart
  packages/devtools_app/lib/src/shared/server/_extensions_api.dart
  packages/devtools_app/lib/src/shared/server/_preferences_api.dart
  packages/devtools_app/lib/src/shared/server/_release_notes_api.dart
  packages/devtools_app/lib/src/shared/server/_survey_api.dart
  packages/devtools_app/lib/src/shared/server/server.dart
  packages/devtools_app/lib/src/shared/server/server_api_client.dart
  packages/devtools_app/test/shared/server/server_api_client_test.dart
  packages/devtools_app/test/shared/service/json_to_service_cache_test.dart
Labels: release-notes-not-required

#8741 License update - Batch 40
  packages/devtools_app/lib/src/shared/table/_flat_table.dart
  packages/devtools_app/lib/src/shared/table/_table_column.dart
  packages/devtools_app/lib/src/shared/table/_table_row.dart
  packages/devtools_app/lib/src/shared/table/_tree_table.dart
  packages/devtools_app/lib/src/shared/table/column_widths.dart
  packages/devtools_app/lib/src/shared/table/table.dart
  packages/devtools_app/lib/src/shared/table/table_controller.dart
  packages/devtools_app/lib/src/shared/table/table_data.dart
  packages/devtools_app/test/shared/table/table_test.dart
Labels: release-notes-not-required

#8742 License update - Batch 41
  packages/devtools_app/lib/src/shared/ui/colors.dart
  packages/devtools_app/lib/src/shared/ui/common_widgets.dart
  packages/devtools_app/lib/src/shared/ui/dialogs.dart
  packages/devtools_app/lib/src/shared/ui/drop_down_button.dart
  packages/devtools_app/lib/src/shared/ui/editable_list.dart
  packages/devtools_app/lib/src/shared/ui/file_import.dart
  packages/devtools_app/lib/src/shared/ui/filter.dart
  packages/devtools_app/lib/src/shared/ui/history_viewport.dart
  packages/devtools_app/lib/src/shared/ui/hover.dart
  packages/devtools_app/lib/src/shared/ui/icons.dart
  packages/devtools_app/lib/src/shared/ui/search.dart
  packages/devtools_app/lib/src/shared/ui/side_panel.dart
  packages/devtools_app/lib/src/shared/ui/tab.dart
  packages/devtools_app/lib/src/shared/ui/tree_view.dart
  packages/devtools_app/lib/src/shared/ui/utils.dart
  packages/devtools_app/lib/src/shared/ui/vm_flag_widgets.dart
  packages/devtools_app/test/shared/ui/auto_complete_test.dart
  packages/devtools_app/test/shared/ui/common_widgets_test.dart
  packages/devtools_app/test/shared/ui/editable_list_test.dart
  packages/devtools_app/test/shared/ui/filter_test.dart
  packages/devtools_app/test/shared/ui/hover_test.dart
  packages/devtools_app/test/shared/ui/search_test.dart
  packages/devtools_app/test/shared/ui/ui_utils_test.dart
  packages/devtools_app/test/shared/ui/vm_flag_widgets_test.dart
Labels: release-notes-not-required

#8743 License update - Batch 42
  packages/devtools_app/lib/src/shared/utils/future_work_tracker.dart
  packages/devtools_app/lib/src/shared/utils/profiler_utils.dart
  packages/devtools_app/lib/src/shared/utils/utils.dart
  packages/devtools_app/lib/src/shared/utils/vm_utils.dart
  packages/devtools_app/test/shared/utils/future_work_tracker_test.dart
  packages/devtools_app/test/shared/utils/utils_test.dart
Labels: release-notes-not-required

#8744 License update - Batch 43
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_panel.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/lib/src/standalone_ui/standalone_screen.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/debug_sessions.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devices.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/devtools_view.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/extensions_view.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/shared.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/sidebar_extensions_controller.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/flutter_panel.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
  packages/devtools_app/test/standalone_ui/vs_code/debug_sessions_test.dart
  packages/devtools_app/test/standalone_ui/vs_code/devtools_test.dart
Labels: release-notes-not-required

#8746 license update - batch 44
  packages/devtools_app/macos/Flutter/GeneratedPluginRegistrant.swift
  packages/devtools_app/macos/README.md
  packages/devtools_app/macos/Runner/AppDelegate.swift
  packages/devtools_app/macos/Runner/MainFlutterWindow.swift
  packages/devtools_app/macos/RunnerTests/RunnerTests.swift
Labels: release-notes-not-required

#8747 License update - Batch 45
  packages/devtools_app/test/legacy_integration_tests/app.dart
  packages/devtools_app/test/legacy_integration_tests/debugger.dart
  packages/devtools_app/test/legacy_integration_tests/integration.dart
  packages/devtools_app/test/legacy_integration_tests/integration_test.dart
  packages/devtools_app/test/legacy_integration_tests/logging.dart
  packages/devtools_app/test/legacy_integration_tests/readme.md
  packages/devtools_app/test_driver/integration_test.dart
Labels: release-notes-not-required

#8748 License update - Batch 46
  packages/devtools_app/test/screens/cpu_profiler/cpu_profile_model_test.dart
  packages/devtools_app/test/screens/cpu_profiler/cpu_profile_transformer_test.dart
  packages/devtools_app/test/screens/cpu_profiler/cpu_profiler_controller_test.dart
  packages/devtools_app/test/screens/cpu_profiler/cpu_profiler_test.dart
  packages/devtools_app/test/screens/cpu_profiler/method_table/method_table_controller_test.dart
  packages/devtools_app/test/screens/cpu_profiler/method_table/method_table_model_test.dart
  packages/devtools_app/test/screens/cpu_profiler/method_table/method_table_test.dart
  packages/devtools_app/test/screens/cpu_profiler/profiler_screen_controller_test.dart
  packages/devtools_app/test/screens/cpu_profiler/profiler_screen_test.dart
Labels: release-notes-not-required

#8750 License update - Batch 48
  packages/devtools_app/web/index.html
  packages/devtools_app/web/styles.css
  packages/devtools_app/web/unsupported-browser.html
Labels: release-notes-not-required

#8751 License update - Batch 49
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/README.md
  packages/devtools_app_shared/lib/shared.dart
  packages/devtools_app_shared/lib/src/shared/embed_mode.dart
  packages/devtools_app_shared/lib/ui.dart
  packages/devtools_app_shared/lib/utils.dart
  packages/devtools_app_shared/lib/web_utils.dart
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_app_shared/test/shared/embed_mode_test.dart
  packages/devtools_app_shared/test/test_utils.dart
Labels: release-notes-not-required

#8752 License update - Batch 50
  packages/devtools_app_shared/example/service_example.dart
  packages/devtools_app_shared/example/ui/common_example.dart
  packages/devtools_app_shared/example/ui/dialog_example.dart
  packages/devtools_app_shared/example/ui/split_example.dart
  packages/devtools_app_shared/example/utils/auto_dispose_example.dart
  packages/devtools_app_shared/example/utils/globals_example.dart
  packages/devtools_app_shared/example/utils/list_example.dart
  packages/devtools_app_shared/example/utils/utils_example.dart
Labels: release-notes-not-required

#8753 License update - Batch 51
  packages/devtools_app_shared/lib/service.dart
  packages/devtools_app_shared/lib/service_extensions.dart
  packages/devtools_app_shared/lib/src/service/connected_app.dart
  packages/devtools_app_shared/lib/src/service/constants.dart
  packages/devtools_app_shared/lib/src/service/dtd_manager.dart
  packages/devtools_app_shared/lib/src/service/eval_on_dart_library.dart
  packages/devtools_app_shared/lib/src/service/flutter_version.dart
  packages/devtools_app_shared/lib/src/service/isolate_manager.dart
  packages/devtools_app_shared/lib/src/service/isolate_state.dart
  packages/devtools_app_shared/lib/src/service/resolved_uri_manager.dart
  packages/devtools_app_shared/lib/src/service/service_extension_manager.dart
  packages/devtools_app_shared/lib/src/service/service_extensions.dart
  packages/devtools_app_shared/lib/src/service/service_manager.dart
  packages/devtools_app_shared/lib/src/service/service_utils.dart
  packages/devtools_app_shared/test/service/flutter_version_test.dart
Labels: release-notes-not-required

#8754 License update - Batch 52
  packages/devtools_app_shared/lib/src/ui/buttons.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
  packages/devtools_app_shared/lib/src/ui/dialogs.dart
  packages/devtools_app_shared/lib/src/ui/flex_split_column.dart
  packages/devtools_app_shared/lib/src/ui/icons.dart
  packages/devtools_app_shared/lib/src/ui/split_pane.dart
  packages/devtools_app_shared/lib/src/ui/text_field.dart
  packages/devtools_app_shared/lib/src/ui/theme/_ide_theme_desktop.dart
  packages/devtools_app_shared/lib/src/ui/theme/_ide_theme_web.dart
  packages/devtools_app_shared/lib/src/ui/theme/ide_theme.dart
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
  packages/devtools_app_shared/lib/src/ui/ui_utils.dart
  packages/devtools_app_shared/test/ui/common_test.dart
  packages/devtools_app_shared/test/ui/flex_split_column_test.dart
  packages/devtools_app_shared/test/ui/ide_theme_test.dart
  packages/devtools_app_shared/test/ui/split_pane_test.dart
  packages/devtools_app_shared/test/ui/theme_test.dart
Labels: release-notes-not-required

#8637 [Property Editor] Emphasize properties the user has set in their code
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
  packages/devtools_app_shared/lib/src/ui/common.dart
Labels: release-notes-not-required

#8765 License update - Batch 53
  packages/devtools_app_shared/lib/src/utils/auto_dispose.dart
  packages/devtools_app_shared/lib/src/utils/globals.dart
  packages/devtools_app_shared/lib/src/utils/list.dart
  packages/devtools_app_shared/lib/src/utils/url/_launch_url_vs_code_stub.dart
  packages/devtools_app_shared/lib/src/utils/url/_launch_url_vs_code_web.dart
  packages/devtools_app_shared/lib/src/utils/url/_url_stub.dart
  packages/devtools_app_shared/lib/src/utils/url/_url_web.dart
  packages/devtools_app_shared/lib/src/utils/url/url.dart
  packages/devtools_app_shared/lib/src/utils/utils.dart
  packages/devtools_app_shared/lib/src/utils/web_utils.dart
  packages/devtools_app_shared/test/utils/auto_dispose_mixin_test.dart
  packages/devtools_app_shared/test/utils/list_test.dart
  packages/devtools_app_shared/test/utils/utils_test.dart
Labels: release-notes-not-required

#8766 License update - Batch 54
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/README.md
  packages/devtools_extensions/bin/_build_and_copy.dart
  packages/devtools_extensions/bin/_validate.dart
  packages/devtools_extensions/bin/devtools_extensions.dart
  packages/devtools_extensions/extension_config_spec.md
  packages/devtools_extensions/integration_test/run_tests.dart
  packages/devtools_extensions/integration_test/test/simulated_environment_test.dart
  packages/devtools_extensions/pubspec.yaml
  packages/devtools_extensions/test/api_test.dart
  packages/devtools_extensions/test/validate_test.dart
  packages/devtools_extensions/test/web/devtools_extension_test.dart
  packages/devtools_extensions/test_driver/integration_test.dart
Labels: release-notes-not-required

#8767 License update - Batch 55
  packages/devtools_extensions/example/README.md
  packages/devtools_extensions/example/app_that_uses_foo/README.md
  packages/devtools_extensions/example/app_that_uses_foo/bin/script.dart
  packages/devtools_extensions/example/app_that_uses_foo/devtools_options.yaml
  packages/devtools_extensions/example/app_that_uses_foo/integration_test/example_integration_test.dart
  packages/devtools_extensions/example/app_that_uses_foo/ios/Runner/AppDelegate.swift
  packages/devtools_extensions/example/app_that_uses_foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  packages/devtools_extensions/example/app_that_uses_foo/ios/Runner/Runner-Bridging-Header.h
  packages/devtools_extensions/example/app_that_uses_foo/ios/RunnerTests/RunnerTests.swift
  packages/devtools_extensions/example/app_that_uses_foo/lib/main.dart
  packages/devtools_extensions/example/app_that_uses_foo/pubspec.yaml
  packages/devtools_extensions/example/app_that_uses_foo/test/flutter_test_1.dart
  packages/devtools_extensions/example/app_that_uses_foo/test/flutter_test_2.dart
  packages/devtools_extensions/example/app_that_uses_foo/test/nested/dart_test_1.dart
  packages/devtools_extensions/example/app_that_uses_foo/test/nested/dart_test_2.dart
Labels: release-notes-not-required

#8768 Property editor validation and nullable argument fixes
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
  packages/devtools_app_shared/lib/src/utils/utils.dart
Labels: release-notes-not-required

#8770 License update - Batch 56
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo/README.md
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo/extension/devtools/build/index.html
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo/extension/devtools/config.yaml
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo/lib/dart_foo.dart
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo/pubspec.yaml
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo_devtools_extension/README.md
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo_devtools_extension/lib/main.dart
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo_devtools_extension/pubspec.yaml
  packages/devtools_extensions/example/packages_with_extensions/dart_foo/packages/dart_foo_devtools_extension/web/index.html
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo/README.md
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo/extension/devtools/build/index.html
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo/extension/devtools/config.yaml
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo/lib/foo.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo/lib/src/foo_controller.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo/lib/src/foo_widget.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo/pubspec.yaml
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/README.md
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/lib/main.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/lib/src/common/ui.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/lib/src/feature_examples/devtools_event_example.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/lib/src/feature_examples/devtools_extension_api_example.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/lib/src/feature_examples/dtd_example.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/lib/src/feature_examples/expression_evaluation_example.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/lib/src/feature_examples/service_extension_example.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/lib/src/foo_devtools_extension.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/pubspec.yaml
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/web/index.html
  packages/devtools_extensions/example/packages_with_extensions/standalone_extension/README.md
  packages/devtools_extensions/example/packages_with_extensions/standalone_extension/extension/devtools/build/index.html
  packages/devtools_extensions/example/packages_with_extensions/standalone_extension/extension/devtools/config.yaml
  packages/devtools_extensions/example/packages_with_extensions/standalone_extension/lib/main.dart
  packages/devtools_extensions/example/packages_with_extensions/standalone_extension/pubspec.yaml
  packages/devtools_extensions/example/packages_with_extensions/standalone_extension/web/index.html
Labels: release-notes-not-required

#8771 License update - Batch 57
  packages/devtools_extensions/lib/api.dart
  packages/devtools_extensions/lib/devtools_extensions.dart
  packages/devtools_extensions/lib/src/api/README.md
  packages/devtools_extensions/lib/src/api/api.dart
  packages/devtools_extensions/lib/src/api/model.dart
  packages/devtools_extensions/lib/src/template/README.md
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_controller.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/connection_ui/_connect.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/connection_ui/_dtd_connect.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/connection_ui/_vm_service_connect.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_extensions/lib/src/utils.dart
  packages/devtools_extensions/lib/utils.dart
Labels: release-notes-not-required

#8778 License update - Batch 63
  packages/devtools_shared/lib/src/utils/compare.dart
  packages/devtools_shared/lib/src/utils/file_utils.dart
  packages/devtools_shared/lib/src/utils/retry.dart
  packages/devtools_shared/lib/src/utils/semantic_version.dart
  packages/devtools_shared/lib/src/utils/serialization.dart
  packages/devtools_shared/lib/src/utils/utils.dart
  packages/devtools_shared/test/utils/file_utils_test.dart
  packages/devtools_shared/test/utils/retry_test.dart
  packages/devtools_shared/test/utils/serialization_test.dart
  packages/devtools_shared/test/utils/utils_test.dart
Labels: release-notes-not-required

#8773 License update - Batch 59
  packages/devtools_shared/lib/devtools_deeplink.dart
  packages/devtools_shared/lib/devtools_deeplink_io.dart
  packages/devtools_shared/lib/src/deeplink/app_link_settings.dart
  packages/devtools_shared/lib/src/deeplink/deeplink_manager.dart
  packages/devtools_shared/lib/src/deeplink/universal_link_settings.dart
  packages/devtools_shared/lib/src/deeplink/xcode_build_options.dart
  packages/devtools_shared/test/deeplink/deeplink_manager_test.dart
Labels: release-notes-not-required

#8776 License update - Batch 61
  packages/devtools_shared/lib/src/memory/adb_memory_info.dart
  packages/devtools_shared/lib/src/memory/class_heap_detail_stats.dart
  packages/devtools_shared/lib/src/memory/event_sample.dart
  packages/devtools_shared/lib/src/memory/heap_sample.dart
  packages/devtools_shared/lib/src/memory/heap_space.dart
  packages/devtools_shared/lib/src/memory/memory_json.dart
  packages/devtools_shared/test/memory/heap_sample_test.dart
Labels: release-notes-not-required

#8772 License update - Batch 58
  packages/devtools_shared/CHANGELOG.md
  packages/devtools_shared/README.md
  packages/devtools_shared/lib/devtools_shared.dart
  packages/devtools_shared/lib/devtools_test_utils.dart
  packages/devtools_shared/lib/src/common.dart
  packages/devtools_shared/lib/src/devtools_api.dart
  packages/devtools_shared/lib/src/test/chrome.dart
  packages/devtools_shared/lib/src/test/chrome_driver.dart
  packages/devtools_shared/lib/src/test/cli_test_driver.dart
  packages/devtools_shared/lib/src/test/integration_test_runner.dart
  packages/devtools_shared/lib/src/test/io_utils.dart
  packages/devtools_shared/lib/src/test/test_utils.dart
  packages/devtools_shared/pubspec.yaml
  packages/devtools_shared/test/fakes.dart
  packages/devtools_shared/test/helpers/helpers.dart
  packages/devtools_shared/test/semantic_version_test.dart
Labels: release-notes-not-required

#8780 License update - Batch 65
  tool/README.md
  tool/RELEASE_INSTRUCTIONS.md
  tool/analysis_options.yaml
  tool/bin/devtools_tool.bat
  tool/bin/dt.bat
  tool/bin/dt.dart
  tool/build_release.sh
  tool/ci/benchmark_performance.sh
  tool/ci/benchmark_size.sh
  tool/ci/bots.sh
  tool/ci/package_tests.sh
  tool/ci/setup.sh
  tool/cpu_sample_intervals.dart
  tool/flutter_customer_tests/README.md
  tool/flutter_customer_tests/analyze.sh
  tool/flutter_customer_tests/setup.sh
  tool/flutter_customer_tests/test.sh
  tool/json_to_map.dart
  tool/latest_flutter_candidate.sh
  tool/lib/commands/analyze.dart
  tool/lib/commands/build.dart
  tool/lib/commands/fix_goldens.dart
  tool/lib/commands/generate_code.dart
  tool/lib/commands/list.dart
  tool/lib/commands/pub_get.dart
  tool/lib/commands/release_helper.dart
  tool/lib/commands/release_notes_helper.dart
  tool/lib/commands/repo_check.dart
  tool/lib/commands/rollback.dart
  tool/lib/commands/run.dart
  tool/lib/commands/serve.dart
  tool/lib/commands/shared.dart
  tool/lib/commands/sync.dart
  tool/lib/commands/tag_version.dart
  tool/lib/commands/update_dart_sdk_deps.dart
  tool/lib/commands/update_flutter_sdk.dart
  tool/lib/commands/update_perfetto.dart
  tool/lib/commands/update_version.dart
  tool/lib/devtools_command_runner.dart
  tool/lib/model.dart
  tool/lib/utils.dart
  tool/pubspec.yaml
Labels: release-notes-not-required

#8781 [Property Editor] Handle `null` text document / text document version in `ActiveLocationChangedEvent`
  packages/devtools_app/lib/src/shared/editor/api_classes.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
Labels: release-notes-not-required

#8784 Remove legacy integration tests and address several TODOs
  packages/devtools_app/lib/src/screens/logging/_message_column.dart
  packages/devtools_app/lib/src/screens/logging/metadata.dart
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/screens/profiler/panes/controls/profiler_screen_controls.dart
  packages/devtools_app/lib/src/shared/framework/screen.dart
  packages/devtools_app/macos/Flutter/GeneratedPluginRegistrant.swift
  packages/devtools_app/test/legacy_integration_tests/app.dart
  packages/devtools_app/test/legacy_integration_tests/debugger.dart
  packages/devtools_app/test/legacy_integration_tests/integration.dart
  packages/devtools_app/test/legacy_integration_tests/integration_test.dart
  packages/devtools_app/test/legacy_integration_tests/logging.dart
  packages/devtools_app/test/legacy_integration_tests/readme.md
  packages/devtools_app/test/screens/logging/metadata_test.dart
  packages/devtools_app/web/index.html
  packages/devtools_app/web/styles.css
  packages/devtools_app_shared/lib/src/ui/theme/theme.dart
  packages/devtools_app_shared/lib/src/utils/utils.dart
Labels: release-notes-not-required

#8786 remove some stale todos
  packages/devtools_app/lib/src/shared/table/table.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  tool/lib/commands/update_version.dart
Labels: release-notes-not-required

#8735 License update - Batch 34
  packages/devtools_app/lib/src/shared/http/_http_cookies.dart
  packages/devtools_app/lib/src/shared/http/curl_command.dart
  packages/devtools_app/lib/src/shared/http/http.dart
  packages/devtools_app/lib/src/shared/http/http_request_data.dart
  packages/devtools_app/lib/src/shared/http/http_service.dart
  packages/devtools_app/test/http/curl_command_test.dart
Labels: release-notes-not-required

#8775 License update - Batch 60
  packages/devtools_shared/lib/devtools_extensions.dart
  packages/devtools_shared/lib/devtools_extensions_io.dart
  packages/devtools_shared/lib/src/extensions/constants.dart
  packages/devtools_shared/lib/src/extensions/extension_enablement.dart
  packages/devtools_shared/lib/src/extensions/extension_manager.dart
  packages/devtools_shared/lib/src/extensions/extension_model.dart
  packages/devtools_shared/lib/src/extensions/yaml_utils.dart
  packages/devtools_shared/test/extensions/extension_enablement_test.dart
  packages/devtools_shared/test/extensions/extension_model_test.dart
  packages/devtools_shared/test/helpers/extension_test_manager.dart
  packages/devtools_shared/test/helpers/extension_test_manager_test.dart
Labels: release-notes-not-required

#8777 License update - Batch 62
  packages/devtools_shared/lib/devtools_server.dart
  packages/devtools_shared/lib/service.dart
  packages/devtools_shared/lib/src/server/devtools_store.dart
  packages/devtools_shared/lib/src/server/file_system.dart
  packages/devtools_shared/lib/src/server/flutter_store.dart
  packages/devtools_shared/lib/src/server/handlers/_app_size.dart
  packages/devtools_shared/lib/src/server/handlers/_deeplink.dart
  packages/devtools_shared/lib/src/server/handlers/_devtools_extensions.dart
  packages/devtools_shared/lib/src/server/handlers/_dtd.dart
  packages/devtools_shared/lib/src/server/handlers/_general.dart
  packages/devtools_shared/lib/src/server/handlers/_preferences.dart
  packages/devtools_shared/lib/src/server/handlers/_release_notes.dart
  packages/devtools_shared/lib/src/server/handlers/_storage.dart
  packages/devtools_shared/lib/src/server/handlers/_survey.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_shared/lib/src/service/service.dart
  packages/devtools_shared/lib/src/service_utils.dart
  packages/devtools_shared/lib/src/sse/_fake_sse.dart
  packages/devtools_shared/lib/src/sse/sse_shim.dart
  packages/devtools_shared/test/server/deeplink_api_test.dart
  packages/devtools_shared/test/server/devtools_extensions_api_test.dart
  packages/devtools_shared/test/server/dtd_api_test.dart
  packages/devtools_shared/test/server/general_api_test.dart
  packages/devtools_shared/test/service_utils_test.dart
Labels: release-notes-not-required

#8788 [Property Editor] Check for registered LSP service methods before calling them
  packages/devtools_app/lib/src/shared/editor/api_classes.dart
  packages/devtools_app/lib/src/shared/editor/editor_client.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
Labels: release-notes-not-required

#8797 [Property Editor] Refactor Property Editor for better code sharing
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_types.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
Labels: release-notes-not-required

#8801 Update when deeplink appid and bundle id are collected
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_deep_links_constants.dart
Labels: autosubmit, release-notes-not-required

#8803 [Property Editor] Densify Property Editor inputs
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_types.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
Labels: release-notes-not-required

#8805 [Property Editor] Remove non-experimental LSP method support
  packages/devtools_app/lib/src/shared/editor/editor_client.dart
Labels: release-notes-not-required

#8814 Use `-O2` optimization for DevTools wasm build.
  tool/build_release.sh
  tool/lib/commands/build.dart
Labels: release-notes-not-required

#8820 Fix build failure
  tool/build_release.sh
Labels: release-notes-not-required

#8823 Fix customer test scripts
  tool/flutter_customer_tests/analyze.sh
  tool/flutter_customer_tests/setup.sh
  tool/flutter_customer_tests/test.sh
Labels: release-notes-not-required

#8825 [CQ] cleanup `unnecessary_ignore`s
  packages/devtools_app/benchmark/test_infra/automators/devtools_automator.dart
  packages/devtools_app/integration_test/test/live_connection/eval_and_inspect_test.dart
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_app/lib/src/screens/debugger/variables.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/enhance_tracing/enhance_tracing_controller.dart
  packages/devtools_app/lib/src/shared/charts/chart_controller.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_allowed_error_default.dart
  packages/devtools_app/lib/src/shared/config_specific/logger/_allowed_error_web.dart
  packages/devtools_app/lib/src/shared/framework/screen.dart
  packages/devtools_app/lib/src/shared/http/_http_cookies.dart
  packages/devtools_app/lib/src/shared/http/_http_date.dart
  packages/devtools_app/lib/src/shared/ui/hover.dart
  packages/devtools_app/test/test_infra/fixtures/flutter_app/lib/main.dart
  packages/devtools_app/test/test_infra/flutter_test_environment.dart
  packages/devtools_app_shared/lib/src/utils/list.dart
  packages/devtools_extensions/lib/src/template/extension_manager.dart
  packages/devtools_shared/lib/src/server/server_api.dart
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
  packages/devtools_test/lib/src/mocks/fake_service_extension_manager.dart
  packages/devtools_test/lib/src/mocks/mocks.dart
Labels: release-notes-not-required

#8819 [Property Editor] Label should always be at the top of the input
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
Labels: release-notes-not-required

#8826 Fix a bug with detecting the base path for DevTools assets
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/test/shared/primitives/utils_test.dart
Labels: release-notes-not-required

#8818 [Property Editor] Handle errors from the Analysis Server
  packages/devtools_app/benchmark/web_bundle_size_test.dart
  packages/devtools_app/lib/src/shared/editor/api_classes.dart
  packages/devtools_app/lib/src/shared/editor/editor_client.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor_test.dart
Labels: release-notes-not-required

#8827 [Property Editor] Increase label font size
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
Labels: release-notes-not-required

#8832 Reenable Code based profiling when VM Developer Mode is enabled
  flutter-candidate.txt
  packages/devtools_app/lib/src/screens/debugger/program_explorer_controller.dart
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
  packages/devtools_app/pubspec.yaml
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/pubspec.yaml
  packages/devtools_extensions/CHANGELOG.md
  packages/devtools_extensions/pubspec.yaml
Labels: release-notes-not-required
