Repository flutter/devtools, pull requests merged in 2025-03, with the labels that each got.

#8965 Prepare for release 2.44.0
  flutter-candidate.txt
  packages/devtools_app/lib/devtools.dart
  packages/devtools_app/pubspec.yaml
Labels: autosubmit, release-notes-not-required

#8979 Add a comment about TextPainter etiquette
  packages/devtools_app/lib/src/shared/charts/chart.dart
Labels: release-notes-not-required

#8984 Format the integration_test README
  packages/devtools_app/integration_test/README.md
Labels: release-notes-not-required

#8987 Refactor BannerMessages to use widgets instead of data classes
  packages/devtools_app/lib/src/extensions/embedded/_view_web.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart
  packages/devtools_app/lib/src/screens/inspector_v2/inspector_screen_body.dart
  packages/devtools_app/lib/src/screens/memory/framework/screen_body.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frames_chart.dart
  packages/devtools_app/lib/src/screens/performance/performance_screen.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen.dart
  packages/devtools_app/lib/src/shared/managers/banner_messages.dart
  packages/devtools_app/lib/src/shared/ui/vm_flag_widgets.dart
  packages/devtools_app/test/shared/managers/banner_messages_test.dart
Labels: release-notes-not-required

#8995 Add support for universal banner messages
  packages/devtools_app/lib/src/shared/managers/banner_messages.dart
  packages/devtools_app/test/shared/managers/banner_messages_test.dart
Labels: release-notes-not-required

#8990 [Property Editor] Add non-experimental LSP method support
  packages/devtools_app/lib/src/shared/editor/editor_client.dart
Labels: release-notes-not-required

#8996 Tidy some code in the integration testing. Namely:
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_shared/lib/src/test/integration_test_runner.dart
Labels: release-notes-not-required

#8989 Add `MemoryObserver` to monitor the memory usage of DevTools
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/framework/framework_core.dart
  packages/devtools_app/lib/src/framework/observer/_memory_desktop.dart
  packages/devtools_app/lib/src/framework/observer/_memory_web.dart
  packages/devtools_app/lib/src/framework/observer/disconnect_observer.dart
  packages/devtools_app/lib/src/framework/observer/memory_observer.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/lib/src/shared/managers/banner_messages.dart
  packages/devtools_app/test/framework/observer/disconnect_observer_test.dart
  packages/devtools_app/test/framework/observer/memory_observer_test.dart
  packages/devtools_app/test/screens/debugger/debugger_codeview_test.dart
  packages/devtools_app/test/shared/managers/banner_messages_test.dart
  packages/devtools_app/test/test_infra/goldens/codeview_scrollbars.png
  tool/lib/commands/fix_goldens.dart
Labels: release-notes-not-required

#8997 Add `releaseMemory` functionality to DevTools screen controllers
  packages/devtools_app/lib/src/screens/app_size/app_size_controller.dart
  packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/inspector_shared/inspector_screen_controller.dart
  packages/devtools_app/lib/src/screens/logging/logging_controller.dart
  packages/devtools_app/lib/src/screens/memory/framework/memory_controller.dart
  packages/devtools_app/lib/src/screens/memory/panes/diff/controller/diff_pane_controller.dart
  packages/devtools_app/lib/src/screens/network/network_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frames_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/rebuild_stats/rebuild_stats_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_controller.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/profiler/profiler_screen_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_developer_tools_controller.dart
  packages/devtools_app/lib/src/shared/framework/screen_controllers.dart
  packages/devtools_app/lib/src/shared/primitives/byte_utils.dart
  packages/devtools_app/test/screens/cpu_profiler/profiler_screen_controller_test.dart
  packages/devtools_app/test/screens/logging/logging_controller_test.dart
  packages/devtools_app/test/screens/memory/framework/memory_controller_test.dart
  packages/devtools_app/test/screens/network/network_controller_test.dart
  packages/devtools_app/test/screens/performance/flutter_frames/flutter_frames_controller_test.dart
  packages/devtools_app/test/screens/performance/timeline_events/timeline_events_controller_test.dart
  packages/devtools_app/test/shared/primitives/byte_utils_test.dart
Labels: release-notes-not-required

#9005 Simplify the TestFileArgs constructors
  packages/devtools_app/integration_test/test_infra/run/_in_file_args.dart
  packages/devtools_app/test/integration_test_infra/in_file_args_test.dart
Labels: release-notes-not-required

#9003 Add an integration test for the Network screen
  packages/devtools_app/integration_test/test/live_connection/network_screen_test.dart
  packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart
  packages/devtools_app/integration_test/test_infra/run/run_test.dart
  packages/devtools_app/test/test_infra/fixtures/networking_app/bin/main.dart
  packages/devtools_app/test/test_infra/fixtures/networking_app/pubspec.yaml
  packages/devtools_test/lib/src/integration_test/integration_test_utils.dart
Labels: release-notes-not-required

#9020 Don't connect the SSE API when running embedded
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_web.dart
  packages/devtools_app/lib/src/shared/server/server_api_client.dart
Labels: release-notes-not-required

#9018 Update to latest Flutter SDK version
  flutter-candidate.txt
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
Labels: release-notes-not-required

#9015 Simplify in_file_args_test
  packages/devtools_app/test/integration_test_infra/in_file_args_test.dart
Labels: release-notes-not-required

#9016 Add package:http requests to network integration test
  packages/devtools_app/integration_test/test/live_connection/network_screen_test.dart
  packages/devtools_app/test/test_infra/fixtures/networking_app/bin/main.dart
Labels: release-notes-not-required

#9024 Switch isDevToolsServerAvailable to not depend on the SSE connection
  packages/devtools_app/lib/src/shared/config_specific/framework_initialize/_framework_initialize_web.dart
  packages/devtools_app/lib/src/shared/server/_server_api.dart
  packages/devtools_app/lib/src/shared/server/server.dart
  packages/devtools_app/lib/src/shared/server/server_api_client.dart
Labels: release-notes-not-required

#8973 Correct some broken comment references
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/screens/debugger/codeview_controller.dart
  packages/devtools_app/lib/src/screens/network/network_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/enhance_tracing/enhance_tracing.dart
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frames_controller.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_hints.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_controller_web.dart
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_web.dart
  packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart
  packages/devtools_app/lib/src/screens/profiler/panes/controls/cpu_profiler_controls.dart
Labels: release-notes-not-required

#9027 Fix deep links page displaying incorrect Windows path formats + a crash if no iOS config
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/root_selector.dart
  packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md
  packages/devtools_app/test/screens/deep_link_validation/deep_links_screen_test.dart
  packages/devtools_shared/lib/src/deeplink/xcode_build_options.dart
Labels: autosubmit

#9017 [Property Editor] Debounce calls to the Analysis Server for `editableArguments`
  packages/devtools_app/lib/src/framework/observer/memory_observer.dart
  packages/devtools_app/lib/src/screens/memory/panes/chart/controller/chart_connection.dart
  packages/devtools_app/lib/src/screens/network/network_controller.dart
  packages/devtools_app/lib/src/shared/utils/utils.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/test/shared/utils/utils_test.dart
Labels: release-notes-not-required

#9037 Fix some broken comment references.
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/vm_developer/vm_service_private_extensions.dart
  packages/devtools_app/lib/src/service/service_extension_widgets.dart
  packages/devtools_app/lib/src/service/vm_service_wrapper.dart
  packages/devtools_app/lib/src/shared/analytics/analytics_common.dart
  packages/devtools_app/lib/src/shared/analytics/constants.dart
  packages/devtools_app/lib/src/shared/analytics/constants/_extension_constants.dart
  packages/devtools_app/lib/src/shared/analytics/metrics.dart
  packages/devtools_app/lib/src/shared/charts/flame_chart.dart
  packages/devtools_app/lib/src/shared/charts/treemap.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/drag_and_drop.dart
  packages/devtools_app/lib/src/shared/console/eval/inspector_tree.dart
  packages/devtools_app/lib/src/shared/development_helpers.dart
  packages/devtools_app/lib/src/shared/primitives/graph.dart
  packages/devtools_app/lib/src/shared/primitives/trees.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/lib/src/shared/table/_tree_table.dart
  packages/devtools_app/lib/src/shared/table/table_controller.dart
  packages/devtools_app/lib/src/shared/utils/future_work_tracker.dart
  packages/devtools_app/lib/src/shared/utils/profiler_utils.dart
Labels: release-notes-not-required

#9050 Update performance benchmark tests
  packages/devtools_app/benchmark/devtools_benchmarks_test.dart
Labels: release-notes-not-required

#9043 [Property Editor] Show reconnection overlay when disconnection detected
  packages/devtools_app/lib/src/screens/performance/panes/timeline_events/timeline_events_view.dart
  packages/devtools_app/lib/src/shared/editor/editor_client.dart
  packages/devtools_app/lib/src/shared/ui/common_widgets.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_panel.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/reconnecting_overlay.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/utils/_utils_desktop.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/utils/_utils_web.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/utils/utils.dart
Labels: release-notes-not-required

#9022 [Property Editor] Can filter properties in the Property Editor
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_types.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/property_editor_test.dart
Labels: release-notes-not-required

#9052 Remove obsolete feature flags
  packages/devtools_app/lib/src/app.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_link_list_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/deep_links_controller.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/project_root_selection/select_project_view.dart
  packages/devtools_app/lib/src/screens/deep_link_validation/validation_details_view.dart
  packages/devtools_app/lib/src/screens/performance/panes/controls/more_debugging_options.dart
  packages/devtools_app/lib/src/screens/performance/panes/frame_analysis/frame_analysis.dart
  packages/devtools_app/lib/src/screens/performance/performance_controller.dart
  packages/devtools_app/lib/src/screens/performance/tabbed_performance_view.dart
  packages/devtools_app/lib/src/shared/feature_flags.dart
  packages/devtools_app/lib/src/shared/framework/screen.dart
  packages/devtools_app/test/screens/deep_link_validation/deep_links_screen_test.dart
  packages/devtools_app/test/shared/primitives/feature_flags_test.dart
  packages/devtools_app/test/test_infra/scenes/performance/default.dart
Labels: release-notes-not-required

#9053 Fix remaining license headers
  .github/workflows/build.yaml
  .github/workflows/flutter-prep.yaml
  packages/devtools_app/benchmark/scripts/utils.dart
  packages/devtools_app/lib/src/screens/network/constants.dart
  packages/devtools_app/lib/src/screens/network/har_builder.dart
  packages/devtools_app/lib/src/screens/network/har_data_entry.dart
  packages/devtools_app/lib/src/screens/network/har_network_data.dart
  packages/devtools_app/lib/src/screens/network/network_controller.dart
  packages/devtools_app/lib/src/screens/network/network_model.dart
  packages/devtools_app/lib/src/screens/network/network_request_inspector.dart
  packages/devtools_app/lib/src/screens/network/network_request_inspector_views.dart
  packages/devtools_app/lib/src/screens/network/network_screen.dart
  packages/devtools_app/lib/src/screens/network/network_service.dart
  packages/devtools_app/lib/src/screens/network/offline_network_data.dart
  packages/devtools_app/lib/src/screens/network/utils/http_utils.dart
  packages/devtools_app/lib/src/shared/http/constants.dart
  packages/devtools_app/test/integration_test_infra/in_file_args_test.dart
  packages/devtools_app/test/screens/network/har_network_test.dart
  packages/devtools_app/test/screens/network/network_controller_test.dart
  packages/devtools_app/test/screens/network/network_model_test.dart
  packages/devtools_app/test/screens/network/network_profiler_test.dart
  packages/devtools_app/test/screens/network/network_request_inspector_test.dart
  packages/devtools_app/test/screens/network/network_screen_test.dart
  packages/devtools_app/test/screens/network/network_table_test.dart
  packages/devtools_app/test/screens/network/offline_data_test.dart
  packages/devtools_app/test/screens/network/utils/network_test_utils.dart
  third_party/packages/perfetto_ui_compiled/lib/dist/devtools/devtools_dark.css
  third_party/packages/perfetto_ui_compiled/lib/dist/devtools/devtools_light.css
  third_party/packages/perfetto_ui_compiled/lib/dist/devtools/devtools_shared.css
  third_party/packages/widget_icons/example/lib/main.dart
  third_party/packages/widget_icons/lib/widget_icons.dart
  third_party/packages/widget_icons/lib/widget_theme.dart
  third_party/packages/widget_icons/test/widget_theme_test.dart
  tool/json_to_map.dart
Labels: release-notes-not-required

#9054 Fix alignment issues in `DevToolsClearableTextField`
  packages/devtools_app/test/test_infra/goldens/memory/load_offline_data_profile_tab.png
  packages/devtools_app/test/test_infra/goldens/memory/load_offline_data_trace_tab.png
  packages/devtools_app_shared/CHANGELOG.md
  packages/devtools_app_shared/lib/src/ui/text_field.dart
Labels: release-notes-not-required

#9051 [PropertyEditor] Do not send requests to `getEditableArguments` for non-Dart files
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/property_editor_test.dart
Labels: release-notes-not-required

#9055 [Property Editor] Miscellaneous small polish items
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/utils/utils.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/utils_test.dart
Labels: release-notes-not-required

#9057 Correct some broken comment references
  packages/devtools_app/lib/src/screens/performance/panes/flutter_frames/flutter_frame_model.dart
  packages/devtools_app/lib/src/shared/charts/treemap.dart
  packages/devtools_app/lib/src/shared/config_specific/copy_to_clipboard/copy_to_clipboard.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/drag_and_drop.dart
  packages/devtools_app/lib/src/shared/console/primitives/scope.dart
  packages/devtools_app/lib/src/shared/console/widgets/description.dart
  packages/devtools_app/lib/src/shared/diagnostics/dart_object_node.dart
  packages/devtools_app/lib/src/shared/diagnostics/diagnostics_node.dart
  packages/devtools_app/lib/src/shared/offline/offline_data.dart
  packages/devtools_app/lib/src/shared/primitives/utils.dart
  packages/devtools_app/lib/src/shared/server/_survey_api.dart
  packages/devtools_app/lib/src/shared/table/_flat_table.dart
  packages/devtools_app/lib/src/shared/table/_tree_table.dart
  packages/devtools_app/lib/src/shared/table/column_widths.dart
Labels: release-notes-not-required

#9062 [Property Editor] Handle deprecated widget arguments
  packages/devtools_app/lib/src/shared/editor/api_classes.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_types.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/property_editor_test.dart
Labels: release-notes-not-required

#9058 [Property Editor] Add a tooltip for the property's default value and documentation
  packages/devtools_app/lib/src/shared/editor/api_classes.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_inputs.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_types.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/utils/utils.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/property_editor_test.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/utils_test.dart
Labels: release-notes-not-required

#9066 [Property Editor] Use new DTD api to check if the connection is closed
  packages/devtools_app/lib/src/shared/editor/editor_client.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_controller.dart
  packages/devtools_app/pubspec.yaml
Labels: release-notes-not-required

#9070 Remove unused field FilterDialog.filteredName
  packages/devtools_app/lib/src/screens/profiler/cpu_profiler.dart
  packages/devtools_app/lib/src/shared/ui/filter.dart
Labels: release-notes-not-required

#9074 Resolve all remaining broken comment references
  analysis_options.yaml
  packages/devtools_app/lib/src/extensions/extension_service.dart
  packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart
  packages/devtools_app/lib/src/shared/config_specific/drag_and_drop/drag_and_drop.dart
  packages/devtools_app/lib/src/shared/offline/offline_data.dart
  packages/devtools_app/lib/src/shared/primitives/graph.dart
  packages/devtools_app/lib/src/shared/table/table.dart
  packages/devtools_app/lib/src/shared/table/table_controller.dart
  packages/devtools_app/lib/src/shared/table/table_data.dart
  packages/devtools_app/lib/src/shared/ui/common_widgets.dart
  packages/devtools_app/lib/src/shared/ui/drop_down_button.dart
  packages/devtools_app/lib/src/shared/ui/filter.dart
  packages/devtools_app/lib/src/shared/ui/icons.dart
  packages/devtools_app/lib/src/shared/ui/search.dart
  packages/devtools_app/lib/src/shared/ui/utils.dart
  packages/devtools_app/lib/src/shared/utils/profiler_utils.dart
  packages/devtools_app/lib/src/shared/utils/utils.dart
  packages/devtools_app/lib/src/standalone_ui/vs_code/devtools/sidebar_extensions_controller.dart
  packages/devtools_app/test/test_infra/test_data/performance/sample_performance_data.dart
  packages/devtools_app/test/test_infra/utils/rendering_tester.dart
  packages/devtools_app/test/test_infra/utils/test_utils.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo/lib/src/foo_controller.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/lib/src/feature_examples/devtools_extension_api_example.dart
  packages/devtools_extensions/example/packages_with_extensions/foo/packages/foo_devtools_extension/lib/src/feature_examples/service_extension_example.dart
  packages/devtools_extensions/lib/src/api/api.dart
  packages/devtools_extensions/lib/src/template/_simulated_devtools_environment/_simulated_devtools_environment.dart
  packages/devtools_extensions/lib/src/template/devtools_extension.dart
  packages/devtools_test/lib/src/helpers/actions.dart
  packages/devtools_test/lib/src/helpers/wrappers.dart
Labels: release-notes-not-required

#9072 Simplify QueryFilter.parse
  packages/devtools_app/lib/src/shared/ui/filter.dart
Labels: release-notes-not-required

#9076 [Property Editor] Better messages when panel is empty
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_messages.dart
  packages/devtools_app/lib/src/standalone_ui/ide_shared/property_editor/property_editor_view.dart
  packages/devtools_app/test/standalone_ui/ide_shared/property_editor/property_editor_test.dart
Labels: release-notes-not-required
